<template>
	<div class="kc-home flex-layout-styles">
		<div class="search-wrapper f-col align-h-center">
            <div class="logo"><img src="https://hugeampkpncms.org/sites/default/files/users/user32/cfde_kc_logo_c.svg"></div>
            <h1 class="kc">Explore Common Fund Knowledge</h1>
            <div class="f-col fill-width">
                <research-single-search
                    :single-search-config="sectionConfigs['content']"
                    :phenotypes="phenotypesInUse"
                    :utils="utilsBox"
                ></research-single-search> 
                <div class="search-extras f-row spread-out">
                    <div>See examples of CFDE knowledge by:</div>
                    <div class="f-row" style="gap:5px">
                        Gene: <a href="/research.html?entity=gene&gene=BDH2&pageid=kc_entity&tissue=blood">BDH2</a>
                        Disease: <a href="/research.html?disease=MONDO%3A0004985&entity=disease&pageid=kc_entity&tissue=blood">Bipolar disorder</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="hero-wrapper f-col" v-if="this.parsedData">
            <div class="hero-q" style="right:40px" @click="this.toggleCFinfo">What is the Common Fund?</div>
            <div class="cf-intro f-col align-h-center">
                <h2 class="kc">{{ Object.keys(this.parsedData).length }} Common Fund Programs</h2>
                <div>Conducting ground-breaking research generating multi-omics data across diverse fields.</div>
            </div>
            <div class="cf-info" style="display:none">
                <h2 class="kc">The Common Fund</h2>
                <div><b>The Common Fund (CF)</b> is a program within the National Institutes of Health (NIH) designed to support innovative, high-impact research that transcends the mission of any single NIH institute or center.</div>
            </div>
            <div class="cfp-info f-col fill-width">
                <div class="dcc-info" style="display:none">
                    <h3 class="kc">Common Fund Programs and Data Coordination Centers</h3>
                    <div><b>CF Programs</b> are large-scale, trans-NIH research initiatives designed to address significant biomedical challenges that no single NIH institute or center can tackle alone.</div>
                    <div><b>Data Coordination Centers (DCCs)</b> are focused on the management, integration, and dissemination of data generated by CF Programs.</div>
                </div>
                <div class="dcc-icons-contain">
                    <div class="dcc-icons f-row">
                        <template v-for="(value, key, index) in this.parsedData">
                            <div 
                                class="dcc-icon"
                                data-group="dccs"
                                :data-value="key"
                                @mouseover="hoverHandler($event)"
								@mouseout="outHandler($event)"
                            >
                                <img :src="value['logo']">
                            </div>
                        </template>
                    </div>
                </div>
            </div>
            <!--<div class="paths"></div>-->
            <div class="cfde-info f-col fill-width align-h-center">
                <div class="arrw">➤</div>
                <div class="hero-q" @click="this.toggleCFDEinfo">What is the CDFE?</div>
                <div class="cfde-title f-col align-h-center">
                    <h2 class="kc">1 Data Ecosystem</h2>
                    <div>Allowing researchers to easily find, access, and integrate Common Fund datasets.</div>
                </div>
                <div class="what-cfde-info" style="display:none">
                    <h3 class="kc">Common Fund Data Ecosystem</h3>
                    <div><b>The Common Fund Data Ecosystem (CFDE)</b> is an initiative under the NIH Common Fund that aims to enhance the accessibility, interoperability, and usability of data generated by Common Fund programs.</div>
                </div>
                <!--
                <div class="cfde-stats f-row fill-width spread-out">
                    <div class="f-col align-h-center">
                        <div>50k+</div>
                        <div>subjects</div>
                    </div>
                    <div class="f-col align-h-center">
                        <div>350+</div>
                        <div>tissues</div>
                    </div>
                    <div class="f-col align-h-center">
                        <div>1.5m+</div>
                        <div>biosamples</div>
                    </div>
                    <div class="f-col align-h-center">
                        <div>100+</div>
                        <div>assays</div>
                    </div>
                    <div class="f-col align-h-center">
                        <div>2k+</div>
                        <div>diseases</div>
                    </div>
                </div>
                -->
                <div class="f-col" style="gap:10px">
                    <div class="eco-row f-col">
                        <div class="eco-title">Resources</div>
                        <div class="resources f-row fill-width spread-out" style="gap:5px">
                            <div v-for="(value, key) in this.parsedData[Object.keys(this.parsedData)[0]]['resources']"
                                class="resource"
                                data-group="resources"
                                :data-value="key"
                                @mouseover="hoverHandler2($event)"
                                @mouseout="outHandler($event)">
                                <span>{{ key.replace('-', ' ') }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="eco-row f-col">
                        <div class="eco-title">Omics</div>
                        <div class="omics f-row fill-width spread-out" style="gap:5px">
                            <div v-for="(value, key) in this.parsedData[Object.keys(this.parsedData)[0]]['omics']"
                                class="omic"
                                data-group="omics"
                                :data-value="key"
                                @mouseover="hoverHandler2($event)"
                                @mouseout="outHandler($event)">
                                <span>{{ key }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="eco-row f-col">
                        <div class="eco-title">Entities</div>
                        <div class="entities f-row fill-width spread-out" style="gap:5px">
                            <div v-for="(value, key) in this.parsedData[Object.keys(this.parsedData)[0]]['entities']"
                                class="entity"
                                data-group="entities"
                                :data-value="key"
                                @mouseover="hoverHandler2($event)"
                                @mouseout="outHandler($event)">
                                <span>{{ key }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="fold f-col align-h-center">
            <h1>What you can do with the CFDE</h1>
            <div class="fold-arrow">
                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#7c7c7c" stroke-width="1.2">
                    <path d="M5.707 9.71a1 1 0 0 0 0 1.415l4.892 4.887a2 2 0 0 0 2.828 0l4.89-4.89a1 1 0 1 0-1.414-1.415l-4.185 4.186a1 1 0 0 1-1.415 0L7.121 9.71a1 1 0 0 0-1.414 0Z" fill="#7c7c7c"/>
                </svg>
            </div>
        </div>



        <div class="home-section-wrap" style="display:none">
            <h1>Access Canonical Data Resources</h1>
            <div class="home-section f-col">
                <div>
                    <div>
                        <h2>Molecular Signatures</h2>
                        <div>Explore comprehensive gene expression signatures, protein markers, and methylation profiles—essential tools for biomarker discovery and pathway analysis.</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
                <div>
                    <div>
                        <h2>Biomedical Aggregators</h2>
                        <div>Lorem Ipsum - need copy here to explain biomedical aggregators</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
                <div>
                    <div>
                        <h2>Reference Maps</h2>
                        <div>Dive into single-cell reference maps, offering fine-resolution insights into cellular diversity and tissue-specific functions.</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>



        <div class="home-section-wrap">
            <h1>Data Integration for Advanced Discovery</h1>
            <div class="home-section f-row">
                <div>
                    <div>
                        <h2>Gene Set Analysis</h2>
                        <div>Uncover gene set patterns across integrated Common Fund programs—designed for advanced cross-dataset exploration.</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
                <div>
                    <div>
                        <h2>Differential Expression Analysis</h2>
                        <div>Compare differentially expressed genes across tissues and diseases, driving insights into gene regulation and disease mechanisms.</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="home-section-wrap">
            <h1>Common Fund Program Spotlight</h1>
            <div class="home-section">
                <div>
                    <h2>Program</h2>
                    <div>
                        <div>Program Name</div>
                        <div>Program highlights</div>
                    </div>
                    <div>Learn More</div>
                    <div>Prev</div>
                    <div>Next</div>
                </div>
            </div>
        </div>
	</div>
</template>

<script>
import Vue from "vue";
import { BootstrapVueIcons } from "bootstrap-vue";

Vue.use(BootstrapVueIcons);

export default Vue.component("cfde-landing", {
	props: ["sectionConfigs", "phenotypesInUse", "utilsBox", "keyParams"],
	data() {
		return {
			parsedData: null,
			currPov: null,
			currHoverGroup: null,
			freezeSelection: false,
            cfInfoToggle: false,
            cfdeInfoToggle: false,
            lines: [],
		};
	},
	mounted() {
        window.addEventListener('resize', this.handleResize);
        this.init();
	},
    beforeDestroy(){
        window.removeEventListener('resize', this.handleResize);
    },
	computed: {},
	watch: {
	},
	updated() {
	},
	methods: {
        async init(){
            const data = await this.loadFile(this.sectionConfigs["content"]["custom"]["viz data"])
		    this.parsedData = await this.parseEntities(data);
            console.log('parsedData', this.parsedData)
            setTimeout(() => {
                const edges = this.getNodePoints();
                this.renderEdges(edges);
            }, 0);
            setTimeout(() => {
                this.simulateMouseOverSequence();
            }, 500)
        },
        async loadFile(src){
			//must use dataset endpoint to load csv file from hugeampkpncms (otherwise CORS error)
			const fetchUrl = "https://hugeampkpncms.org/servedata/dataset?dataset=" + src;
			//however, dataset enpoint parses the original csv and escapes special characters
			let data = await fetch(fetchUrl).then(resp => resp.text(fetchUrl));
			//we must undo all of that to get the original data
			data = data.replace(/\\u0022/g, '"'); 		//quotes
			data = data.replace(/\\\//g, '/');			//slashes
			data = data.replace(/\\n/g, '\n');			//line breaks
			data = data.replace(/\\r/g, '\r');			//carriage returns
			data = data.substring(1, data.length - 1);	//remove surrounding quotes
			return data;
		},
        async parseEntities(data){
			const lines = data.split('\n');
            const headers = lines[0].split(',');
            const result = {};

            for (let i = 1; i < lines.length; i++) {
                const values = lines[i].match(/(".*?"|[^",\r\n]+|(?<=,)(?=,))/g);//.split(',');
                const dcc = values[0];
                result[dcc] = { entities: {}, omics: {}, resources: {}, povs: {}, logo: '', info: {} };

                for (let j = 1; j < headers.length; j++) {
                const [prefix, key] = headers[j].split('_');
                if (prefix && key) {
                    let group;
                    if (prefix === 'a') {
                        group = 'entities';
                    } else if (prefix === 'b') {
                        group = 'omics';
                    } else if (prefix === 'c') {
                        group = 'povs';
                    } else if (prefix === 'd') {
                        group = 'logo';
                        result[dcc][group] = values[j];
                        continue;
                    }else if (prefix === 'e') {
                        group = 'resources';
                    }else if (prefix === 'r'){
                        group = 'info';
                        result[dcc][group][key.trim()] = values[j];
                        continue;
                    }
                    result[dcc][group][key.trim()] = values[j] ? parseInt(values[j]): null;
                }
                }
            }

			return result;
			//this.parsedData = result;
			//console.log(this.parsedData);
		},
        drawEdge(from, to, thickness, value){
            let nodeConnectOffset = 20;

            //start and end point offsets
            let startX = from.x;
            let endX = to.x;
            let startY = from.y;
            let endY = to.y;

            let curveDirX = startX < endX ? -1 : 1;
            let curveDirY = startY < endY ? -1 : 1;
            const curveSize = startX === endX ? 0 : nodeConnectOffset;

            //if the endX point is more left than startX point
            //swap them
            if(to.x < from.x){
                startX = to.x;
                endX = from.x;
                curveDirX = endX < startX ? -1 : 1;
            }

            startX -= thickness;
            endX += thickness;

            // Create an SVG element
            const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
            const svgWidth = Math.abs(startX - endX);
            const svgHeight = Math.abs(startY - endY);
            svg.style.position = 'absolute';
            svg.style.left = startX+'px';
            svg.style.top = startY+'px';
            svg.style.width = svgWidth+'px';
            svg.style.height = svgHeight+'px';
            svg.setAttribute('viewBox', `0 0 ${svgWidth} ${svgHeight}`);
            svg.classList.add('line-svg');
            document.body.append(svg);

            //create the path element
            const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
            let sX = thickness;
            let eX = endX - startX - thickness;
            let sY = 0;
            let eY = endY - startY;
            let midY = ((eY - sY) / 2);

            if(to.x < from.x){
                sX = endX - startX - thickness;
                eX = thickness;
            }

            // Draw path
            let d = `M ${sX} ${sY}`;
            d += ` V ${midY - curveSize}`;
            d += ` Q ${sX} ${midY}, ${sX - curveSize * curveDirX} ${midY}`;
            d += ` H ${eX + curveSize * curveDirX}`;
            d += ` Q ${eX} ${midY}, ${eX} ${midY - curveSize * curveDirY}`;
            d += ` V ${eY}`; 

            // Set path attributes
            path.setAttribute("data-value", value);
            path.setAttribute("d", d);
            path.setAttribute("stroke", "#f26822");
            path.setAttribute("fill", "transparent");
            path.setAttribute("stroke-width", thickness);

            svg.appendChild(path);

            this.lines.push(path);
        },
        renderEdges(edges){
            document.querySelectorAll('.line-svg').forEach(el=>{
                el.remove();
            })
            edges.forEach(edge => {
                this.drawEdge(edge.from_point, edge.to_point, 1, edge.value);
            });
            document.querySelector('.arrw').style.display = 'block';
        },
        getNodePoints(){
            const from_nodes = document.querySelectorAll('.dcc-icon');
            const to_node = document.querySelector('.cfde-info');

            function getBottomCenter(element){
                const rect = element.getBoundingClientRect();
                return {
                    x: rect.left + (rect.width / 2),
                    y: rect.bottom + window.scrollY
                };
            };

            function getTopCenter(element) {
                const rect = element.getBoundingClientRect();
                return {
                    x: rect.left + (rect.width / 2),
                    y: rect.top + window.scrollY
                };
            };

            const to_point = getTopCenter(to_node);

            const edges = Array.from(from_nodes).map(from_node => ({
                value: from_node.dataset.value,
                from_point: getBottomCenter(from_node),
                to_point: to_point
            }));

            return edges;
        },
        handleResize(){
            const edges = this.getNodePoints();
            this.renderEdges(edges);
        },
        toggleCFinfo(e){
            if(!this.cfInfoToggle){
                e.target.innerHTML = 'close ✖';
                document.querySelector('.cf-intro').style.display = 'none';
                //document.querySelector('.cfp-info').classList.add('active');
                document.querySelector('.cf-info').style.display = 'block';
                document.querySelector('.dcc-info').style.display = 'block';
                this.cfInfoToggle = true;
            }else{
                e.target.innerHTML = 'What is the Common Fund?';
                document.querySelector('.cf-intro').style.display = 'flex';
                //document.querySelector('.cfp-info').classList.remove('active');
                document.querySelector('.cf-info').style.display = 'none';
                document.querySelector('.dcc-info').style.display = 'none';
                this.cfInfoToggle = false;
            }
            this.handleResize();
        },
        toggleCFDEinfo(e){
            if(!this.cfdeInfoToggle){
                e.target.innerHTML = 'close ✖';
                document.querySelector('.cfde-title').style.display = 'none';
                document.querySelector('.what-cfde-info').style.display = 'block';
                this.cfdeInfoToggle = true;
            }else{
                e.target.innerHTML = 'What is the CFDE?';
                document.querySelector('.cfde-title').style.display = 'flex';
                document.querySelector('.what-cfde-info').style.display = 'none';
                this.cfdeInfoToggle = false; 
            }
            this.handleResize();
        },
        outHandler(e){
            if(this.freezeSelection){
                document.querySelectorAll(`[data-group]`).forEach(item => item.classList.remove('on', 'on2', 'on3'));
				const targetElement = document.querySelector(`[data-value="${this.currPov}"]`);
				if (targetElement) targetElement.dispatchEvent(new Event('mouseover'));
            }else{
                document.querySelectorAll(`[data-group]`).forEach(item => item.classList.remove('on', 'on2', 'on3', 'onA', 'on2A', 'on3A'));
                this.lines.forEach(line => {
                    line.setAttribute("stroke", "#f26822");
                    line.parentNode.style.zIndex = 0;
                })
            }
            this.currHoverGroup = null;
        },
		hoverHandler(e){
            const val = e.target.dataset.value;

            console.log('lines', this.lines);

            this.lines.forEach(line => {
                if(line.dataset.value !== val){
                    line.setAttribute("stroke", "#ddd");
                }else{
                    line.parentNode.style.zIndex = 1;
                }
            })

            //highlight resources
            if(this.currHoverGroup!=='resources'){
                for (const [key, value] of Object.entries(this.parsedData[val]['resources'])) {
                    if(value){
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }

            //highlight entities
            if(this.currHoverGroup!=='entities'){
                for (const [key, value] of Object.entries(this.parsedData[val]['entities'])) {
                    if(value){
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }
            
            //highlight omics
            if(this.currHoverGroup!=='omics'){
                for (const [key, value] of Object.entries(this.parsedData[val]['omics'])) {
                    if(value){
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }
        },
        hoverHandler2(e){	
            const group = e.target.dataset.group;
            let val = e.target.dataset.value;
            this.currHoverGroup = group;

            //un-hilight lines from DCCs
            this.lines.forEach(line => {
                line.setAttribute("stroke", "#ddd");
            })
			
            //highlight dccs
            for (const [key, value] of Object.entries(this.parsedData)) {
                const el = document.querySelector(`[data-value="${key}"]`);
                if(value[group][val]===1){
                    //highlight DCC
                    el.classList.add('on');
                    //hilighlight lines from DCC
                    const line = this.lines.find(element => element.dataset.value === key);
                    line.setAttribute("stroke", "#f26822");
                    line.parentNode.style.zIndex = 1;
                }
                //ununsed
                if(value[group][val]===2){
                    el.classList.add('on2');
                }
                if(value[group][val]===3){
                    el.classList.add('on3');
                }
            }
        },
        simulateMouseOverSequence() {
            const delay = 100;
            const elements = document.querySelectorAll('.dcc-icon');

            function triggerMouseEvent(element, eventType) {
                const event = new MouseEvent(eventType, {
                    bubbles: true,
                    cancelable: true,
                    view: window
                });
                element.dispatchEvent(event);
                eventType==='mouseover' ? element.classList.add('on') : element.classList.remove('on');
            }

            let lastEl = null;

            elements.forEach((element, index) => {
                setTimeout(() => {
                    if(lastEl) triggerMouseEvent(element, 'mouseout');
                    triggerMouseEvent(element, 'mouseover');
                    lastEl = element;
                    if(index===elements.length-1){
                        setTimeout(() => {
                            triggerMouseEvent(element, 'mouseout');
                        }, delay);
                    }
                    
                }, index * delay);
            });
        }
	}
});
</script>
<style>
.line-svg{
    pointer-events: none;
}
.kc-home{
    display:flex;
    flex-direction: column;
    align-items: center;
    background: #f7f6f6;
    margin: -15px;
    padding: 15px;
    color: #7c7c7c;

    h1{
        font-size: 22px;
        font-weight: bold;
        line-height: 22px;
    }
    h2{
        font-size: 18px;
        font-weight: bold;
        line-height: 18px;
    }
    h3{
        font-size: 16px;
        font-weight: bold;
        line-height: 16px;
    }
    h1.kc,
    h2.kc,
    h3.kc{
        text-transform: uppercase;
        color:#f26822;
    }
    h1.kc{
        font-size: 20px;
    }
    h2.kc{
        font-size: 18px;
    }
    h3.kc{
        font-size: 16px;
    }
    .logo img {
        width: 70px;
    }
    .search-wrapper {
        width: 900px;
        margin: 0px 0 30px 0;
        gap: 10px;
    }
    #byor_single_search {
        border-radius: 10px;
        padding: 25px;
        font-size: 16px;
    }
    .search-extras {
        gap: 5px;
        background: #e6e6e6;
        padding: 5px 25px;
        margin: 0 25px;
        border-radius: 0 0 10px 10px;
    }
    .search-extras a,
    .search-extras a:visited{
        color: #f26822 !important;
    }
    .hero-wrapper {
        width: 900px;
        background: #f8f6f6;
        padding: 20px;
        gap:20px;
        position: relative;
        border-radius: 10px;
    }
    .cf-info{
        padding: 0px 0px 0px 0px;
    }
    .cfp-info {
        width: fit-content;
        padding: 0px 20px 20px 20px;
        gap: 30px;
    }
    .cfp-info.active{
        padding-top: 20px;
        background: #ebebeb;
    }
    .cfde-info {
        margin-top: 30px;
        padding: 20px 20px 20px 20px;
        gap: 20px;
        background: #ebebeb;
        position: relative;
        border-radius: 10px;
    }
    .dcc-icons-contain{
        position:relative;
        height: 70px;
    }
    .dcc-icons{
        gap:10px;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    .dcc-icon {
        width: 75px;
        aspect-ratio: 1;
        background: #ebebeb;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 10px;
        transition: .1s all linear;
    }
    .dcc-icon img {
        width: 75%;
        pointer-events: none;
        mix-blend-mode: darken;
    }
    .dcc-icon.on, .dcc-icon:hover{
        /*outline: 2px solid #ff6600;*/
        background: #ff660050
        /*border-bottom:3px solid #ff6600;*/
    }
    .eco-row{
        position: relative;
    }
    .eco-title {
        font-size: 12px;
        font-weight: bold;
        position: absolute;
        left: calc(100% + 50px);
        top: 50%;
        transform: translateY(-50%);
    }
    .resource,
    .omic,
    .entity {
        display: flex;
        flex: 1 1 auto;
        align-items: center;
        justify-content: center;
        aspect-ratio: unset;
        height: 20px;
        text-transform: uppercase;
        font-size: 11px;
        padding: 0 5px;
        letter-spacing: 1px;
        font-weight: 600;
        background: #ddd;
        filter: grayscale(1);
        cursor: default;
        transition: .1s all linear;
    }
    .resource.on, .resource:hover,
    .omic.on, .omic:hover,
    .entity.on, .entity:hover{
        background: #ff802c;
        filter: none;
        color: white;
    }
    .resource span,
    .omic span,
    .entity span{
        pointer-events: none;
    }
    .paths {
        height:50px;
    }
    .cfde-stats{
        gap:5px;
    }
    .hero-q{
        align-self: flex-end;
        font-size: 12px;
        /*color: #f26822;*/
        font-weight: bold;
        position: absolute;
        top: 20px;
        right: 20px;
        cursor: pointer;
        user-select: none;
        background: white;
        padding: 0 10px;
        border-radius: 10px;
    }
    .fold{
        margin:30px 0;
    }
    .fold-arrow {
        line-height: 0;
        margin: -10px 0 0;
    }
    .fold-arrow svg{
        height:30px;
    }
    .home-section-wrap {
        width: 900px;
        margin: 0 0 40px;
    }
    .home-section {
        background: #eee;
        padding: 20px;
        gap:10px;
    }
    .arrw {
        position: absolute;
        top: -10px;
        transform: rotate(90deg);
        display:none;
        font-size: 12px;
        align-self: center;
        color:#f26822;
    }
}
.flex-layout-styles{
    /* LAYOUT STYLES */
    .no-events{
        pointer-events: none;
    }
    .f-col{
        display: flex;
        flex-direction: column;
    }
    .f-row{
        display: flex;
        flex-direction: row;
    }
    .f-col.align-v-center{
        justify-content: center;
    }
    .f-row.align-v-center{
        align-items: center;
    }
    .f-col.align-h-center{
        align-items: center;
    }
    .f-row.align-h-center{
        justify-content: center;
    }
    .f-col.align-v-bottom{
        justify-content: flex-end;
    }
    .f-row.align-v-bottom{
        align-items: flex-end;
    }
    .f-col.align-h-bottom{
        align-items: flex-end;
    }
    .f-row.align-h-bottom{
        justify-content: flex-end;
    }
    .f-col.spread-out,
    .f-row.spread-out{
        justify-content: space-between;
    }
    .fill-height{
        /*height: -moz-available;
        height: -webkit-fill-avaiilable;*/
        height: stretch;
        height: 100%;
    }
    .fill-width{
        /*width: -moz-available;
        width: -webkit-fill-avaiilable;*/
        width: stretch;
        width: 100%;
    }
    .hug-height{
        height: fit-content;
    }
    .hug-width{
        width: fit-content
    }
    .grow-children>*{
        flex-grow: 1;
    }
}
</style> 

