<template>
	<div>
		<div class="kc-hero">
			<div class="kc-wrap">
				<div class="blurb">
					<div class="logo"><img src="https://hugeampkpncms.org/sites/default/files/users/user32/cfde_kc_logo_c.svg"></div>
					<div><span>The Knowledge Center</span> integrates curated knowledge<br>generated by ground-breaking research programs<br>in the NIH Common Fund Data Ecosystem. 
						<span style="display:none">Explore the diagram to see connections between research programs, the omics data types and biological entities that they span, and their relevance to different research contexts.</span>
					</div>
					<!--<div><span>Explore</span> the diverse range of omics data<br> generated by Common Fund Programs.</div>
					<div><span>Gain knowledge</span>, tools and other digital resources to enable hypothesis testng and new discoveries.</div>-->
				</div>
				<!--
				<div class="kc-title">The Common Fund Data Ecosystem</div>
				<div class="blurbA">
					<p>
						The CFDE Data Resource and Knowledge Centers aim to unify access to the 
						varied, large-scale data generated by Common Fund Programs, 
						and to provide knowledge, tools and other digital resources to enable hypothesis testng and new discoveries.
					</p>
					Explore the diverse range of omics data generated by Common Fund Programs. 
					Gain knowledge, tools and other digital resources to enable hypothesis testng and new discoveries.
				</div>
				-->
				<div class="blurbA"></div>
			</div>
			<div class="map-bg">
				<div class="map-title hideable">set search context:<span>Explore connections between research programs, their omics data types and biological entities, with relevance to different research contexts.</span></div>
				<div class="map" v-if="this.parsedData">
					<div class="povs">
						<div class="map-label hideable"><div>Research Context</div></div>
						<div v-for="(value, key) in this.parsedData[Object.keys(this.parsedData)[0]]['povs']"
							class="pov"
							data-group="povs"
							:data-value="key"
							@mouseover="hoverHandler2($event)"
							@mouseout="outHandler($event)"
							@click="povHandler($event)">
							<div class="img">
								<img :src="`https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/${key}.svg`">
							</div>
							<span>{{ key }}</span>
						</div>
					</div>
					<div class="line2">
						<div class="map-label hideable">
							<div>
								<div>Relevance</div>
								<div class="relevance-legend">
									<div class="relevance-hi">high</div>
									<div class="relevance-md">med</div>
									<div class="relevance-lo">low</div>
								</div>
							</div>
						</div>
						<div class="line2info"></div>
						<div class="line2note"></div>
					</div>
					<div class="dccs">
						<div class="map-label hideable"><div>Common Fund Programs</div></div>
						<div v-for="(value, key) in this.parsedData"
							class="dcc"
							data-group="dccs"
							:data-value="key"
							@mouseover="hoverHandler($event)"
							@mouseout="outHandler($event)">
							<img :src="value['logo']">
						</div>
					</div>
					<div class="omics">
						<div class="map-label hideable"><div>Omics Data</div></div>
						<div v-for="(value, key) in this.parsedData[Object.keys(this.parsedData)[0]]['omics']"
							class="omic"
							data-group="omics"
							:data-value="key"
							@mouseover="hoverHandler2($event)"
							@mouseout="outHandler($event)">
							<span>{{ key }}</span>
						</div>
					</div>
					<div class="entities">
						<div class="map-label hideable"><div>Searchable Entities</div></div>
						<div v-for="(value, key) in this.parsedData[Object.keys(this.parsedData)[0]]['entities']"
							class="entity"
							data-group="entities"
							:data-value="key"
							@mouseover="hoverHandler2($event)"
							@mouseout="outHandler($event)">
							<span>{{ key }}</span>
						</div>
					</div>
				</div>
			</div>
		
		
			<div class="section">
				<div class="map-title v2 hideable">search knowledge:<span>Use the KC to get curated, synthesized, analyzed results from Common Fund data.</span></div>
				<research-single-search
					:single-search-config="sectionConfigs['content']"
					:phenotypes="phenotypesInUse"
					:utils="utilsBox"
				></research-single-search> 
				<div class="search-try"><span>Try</span><span>PCSK9</span><span>Cardiovasular Disease</span></div>
				<!--<div class="search-icon"><img src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/geneticist.svg"></div>-->
			</div>
		</div>

		<div id="kc-section-a" class="section">
			<div class="section-title">Scientifically valid, integrated knowledge</div>
			<div class="section-wrap">
				<div class="section-col">
					<div class="section-subtitle">Genes</div>
					<div class="placeholder">Genes</div>
				</div>
				<div class="section-col">
					<div class="section-subtitle">Diseases</div>
					<div class="placeholder">Diseases</div>
				</div>
			</div>
		</div>

		<div id="kc-section-b" class="section">
			<div class="section-title">Knowledge about CFDE programs and partnerships</div>
			<div class="section-wrap">
				<div class="section-col">
					<div class="section-subtitle">CFDE programs</div>
					<div class="placeholder">
						<div class="mini-card-video">
                        	<video 
								@ended="minVidEnd($event)" 
								@mouseover="minVidHover($event)"
								@mouseout="minVidHoverOut($event)"
								data-loop-max="1"
								data-loop-count="0"
								src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_tools/Landing_DCCs_480.mp4" 
								poster="https://hugeampkpncms.org/sites/default/files/users/user32/kc_tools/Landing_DCCs.jpg" 
								autoplay muted playsinline 
							/>
                        </div>
					</div>
				</div>
				<div class="section-col">
					<div class="section-subtitle">Partnerships</div>
					<div class="placeholder">Partnerships</div>
				</div>
			</div>
		</div>

		<div id="kc-section-c" class="section">
			<div class="section-title">CFDE Workbench</div>
			<div class="section-wrap">
				<div class="section-col">
					<div class="section-subtitle">Visit our sister resource to query, access, and compute Common Fund datasets.</div>
					<ul>
						<li>Search across all Common Fund metadata and processed data.</li>
						<li>Cloud tools to interrogate data sets from various Common Fund programs.</li>
						<li>Training and outreach to highlight Common Fund data and how to use it effectively.</li>
					</ul>
				</div>
			</div>
		</div>
			
		<!--
		<div class="section" style="background: #f7f6f6;">
			<div class="a quick">
				<div class="b">
					<div class="c-title"><p>Knowledge Center</p></div>
					<div class="c-body">Use the Knowledge Center to see <span class="bold">curated</span>, 
						<span class="bold">synthesized</span>, and <span class="bold"> analyzed</span> results from Common 
						Fund data in a research context.
					</div>
					<a href="/research.html?pageid=kc_landing">Learn More</a>
				</div>
				<div class="c">
					
				</div>
				<div class="b">
					<div class="c-title"><p>Data Resource Center</p></div>
					<div class="c-body">Use the Data Resource Center to <span class="bold">query</span>, 
						<span class="bold">access</span>, and <span class="bold"> compute</span> Common Fund datasets
						and metadata for your research.
					</div>
					<a href="/research.html?pageid=kc_landing">Visit DRC</a>
				</div>
				
				
			</div>
		</div>

		<div class="section">
			<div class="kc-title">Foundational Knowledge</div>
			<div style="display:flex; flex-direction: row; gap: 20px;">
				<div style="width:100%; height:220px; background:#f7f6f6; display:flex; align-items: center; justify-content: center;">
					Foundation Page vid
				</div>
				<div class="c-body" style="display: flex; flex-direction: column; align-items: center; justify-content: flex-end; gap:10px">
					In-depth summaries for each Common Fund program including its research focus, 
					omics data types, tools, resources and more.
					<a href="/research.html?pageid=kc_landing" style="align-self: flex-start;">Explore Foundational Knowledge</a>
				</div>
				
			</div>
		</div>
		
		<div class="section">
			<div class="kc-title">Partnerships</div>
			<div class="partnerships">
				<div class="partner">
					<img src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/NIH_logo.png">
				</div>
				<div class="partner">
					<img src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/CFDE_logo.png">
				</div>
			</div>
		</div>
		-->
		
	</div>
</template>

<script>
import Vue from "vue";
import $ from "jquery";
import ResearchSingleSearch from "@/components/researchPortal/ResearchSingleSearch.vue";
//import uiUtils from "@/utils/uiUtils";
import { BootstrapVueIcons } from "bootstrap-vue";

Vue.use(BootstrapVueIcons);

export default Vue.component("cfde-eco-system", {
	props: ["sectionConfigs", "phenotypesInUse", "utilsBox"],
	data() {
		return {
			parsedData: null,
			currPov: null,
			currHoverGroup: null,
			freezeSelection: false,
			entitiesDATA: `DCC,a_Species,a_Disease,a_BodySite,a_Organ,a_Tissue,a_Region,a_Gene,a_Variant,a_Transcript,a_Protein,a_Pathway,a_Metabolite,a_Ligand,b_Epigenomics,b_Genomics,b_Transcriptomics,b_Proteomics,b_Metabolomics,c_experimental-biology,c_genetics,c_drug-development,c_computational-biology,d_logo,r_experimental-biology,r_genetics,r_drug-development,r_computational-biology
4DN,,,,,,1,,,,,,,,1,1,,,,3,2,2,3,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/4DN.png,"Provides data on the 3D organization of the nucleus, crucial for understanding cellular mechanisms experimentally.","While focused on nuclear organization, it offers insights into genomic architecture that can have implications for genetic research.","Provides insights into the 3D organization of the nucleus, relevant for understanding disease mechanisms at a genomic level for drug targeting.","Facilitates understanding of the 3D genome organization, providing critical data for computational modeling of genomic interactions and dynamics."
GTEx,,,,,1,1,1,1,1,,,,,,1,1,,,1,3,2,3,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/GTEx.png,"Primarily a genomics database, its relevance is more for genetic analysis than direct experimental biology.","Provides extensive gene expression data across tissues, crucial for understanding genetic variations and their phenotypic impacts.",Gene expression data across tissues can inform drug target selection and understand drug effects in different biological contexts.,"Offers a comprehensive dataset of gene expression across human tissues, invaluable for computational genetic studies and disease modeling."
ExRNA,,1,,,,,,,1,,,,,,,1,,,1,2,2,2,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/exRNA.png,"Offers extracellular RNA data, useful for hypothesis generation but less so for direct experimental methodologies.","Offers data on extracellular RNAs, which can be used in genetic studies related to gene regulation and non-coding RNA functions.","Offers data on extracellular RNAs, which can be relevant for drug development in terms of biomarkers or therapeutic targets.","Offers data on extracellular RNAs, supporting computational studies on non-coding RNA functions and gene regulation."
HuBMAP,,,,,1,,,,,,,,,,1,1,1,,3,2,2,3,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/HuBMAP.png,"Directly supports experimental biology by mapping the human body at a molecular level, offering valuable data for in vitro and in vivo studies.","Maps the human body at a molecular level, providing data that can be valuable for understanding genetic expression patterns in tissues.","By mapping the human body at a molecular level, it offers valuable data for identifying disease mechanisms and potential drug targets.","Maps the human body at a molecular level, offering rich datasets for computational studies in tissue-specific gene expression and organ systems."
IDG,,1,,,1,,1,,,1,,,1,,1,,1,,1,2,3,2,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/IDG.png,"Focused on drugable genome elements, more relevant for drug discovery and computational biology than direct experimental work.","Provides data on the druggable genome, useful for geneticists interested in genetic factors that influence drug responses.","Directly supports drug discovery by illuminating the druggable genome, providing crucial data on potential drug targets.","Provides information on druggable genome elements, useful for computational drug target identification and validation."
LINCS,,,,,,,1,,,,,,,,,1,1,,3,1,3,3,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/LINCS.gif,Offers a large-scale database of cellular signatures that can guide experimental studies on cellular responses to various perturbations.,"Focuses on cellular responses to perturbations, more relevant to cellular biology but indirectly useful for understanding genetic influence on cell behavior.","Offers cellular response data to various perturbations, essential for understanding drug effects and mechanisms of action at a cellular level.","Provides extensive cellular signature datasets ideal for computational analysis, modeling, and simulation in systems biology."
GlyGen,,1,,,1,1,1,,,1,,,,,,,1,,2,1,1,2,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/Glycoscience.png,"Offers glycoscience data relevant for experimental studies on carbohydrate biology, although more niche.","Provides glycoscience data, which has genetic components but is more niche in its direct application to genetic research.","Provides glycoscience data, which can be relevant for drug development but in more niche areas like carbohydrate-targeted therapies.","Offers glycoscience data, useful for computational studies on carbohydrate biology, albeit more niche in scope."
Metabolomics Workbench,,1,,,,,1,,,1,1,1,,,,,,1,2,1,1,2,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/Metabolomics.png,Provides metabolomics data that can be used for hypothesis testing in experimental metabolism studies.,"Metabolomics data is more indirectly related to genetic research, useful for understanding the phenotypic outcomes of genetic variations.",Offers metabolomics data that can support drug efficacy and toxicity studies but is more indirectly related to the initial stages of drug development.,"Provides metabolomics data, supporting computational analysis for understanding metabolic pathways and their alterations in diseases."
MoTrPAC,1,,,,1,1,1,,,1,1,1,,,1,,1,1,2,1,1,2,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/MoTrPAC.png,"While focused on physical activity's molecular transducers, it offers data that can be valuable for experimental studies on metabolism and physiology.","Focuses on the molecular transducers of physical activity, which can be linked to genetics but is more focused on physiological outcomes.","While it focuses on physical activity's molecular transducers, its direct relevance to drug development, outside of exercise mimetics, is limited.","Focuses on the molecular transducers of physical activity, providing data that can support computational physiological and metabolic studies."
Kids First,,1,1,,1,1,1,1,,,1,,,,1,,,,1,3,1,1,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/Kids%20First.png,Pediatric genomic data is more specific to geneticists and less directly applicable to broad experimental biology.,"Offers genomic data focused on pediatric diseases, directly supporting genetic research into hereditary diseases and genetic disorders.","While providing valuable pediatric disease genomic data, its direct application to drug development is more indirect, focusing on genetic research.","While it offers pediatric genomic data, its direct application to computational biology is more specific to genetic analysis than broader computational modeling."
SPARC,,,1,1,1,,,,,,1,,,,,,,,2,1,2,1,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/SPARC.svg,"Offers data on peripheral nervous system's role in organ function, relevant for experimental studies but with a specific focus.","Aimed at understanding the peripheral nervous system, its relevance to genetics is indirect and more focused on physiological research.","Provides insights into the peripheral nervous system's role in diseases, potentially guiding drug development for conditions like chronic pain.","Provides data on the peripheral nervous system, more applicable to specific computational studies in neuroscience and less to broad computational biology."
SenNet,1,,,1,1,,1,,,,,,,,1,1,1,,1,1,1,1,https://hugeampkpncms.org/sites/default/files/users/user32/dcc_logos/SenNet.png,"Focuses on cellular senescence, offering niche data that might not broadly apply to general experimental biology.","Focuses on cellular senescence, which has genetic components but is not directly focused on genetic research or genetic variation analysis.","Focuses on cellular senescence, providing niche data that might inform drug development targeting aging or senescence-associated diseases.","Focuses on cellular senescence, providing niche data that may support specific computational aging studies but not a wide range of computational biology applications."`
		};
	},
	mounted() {
		
		this.loadScript('https://cdn.jsdelivr.net/npm/leader-line@1.0.7/leader-line.min.js', ()=>{
			this.parsedData = this.parseEntities();
			console.log(this.parsedData);
			setTimeout(function () {
				const targetElement = document.querySelector('[data-value="genetics"]');
				console.log(targetElement);
				if (targetElement) {
					targetElement.dispatchEvent(new Event('mouseover'));
					targetElement.dispatchEvent(new Event('click'));
				}
			}, 1000);
		});	
		
		
	},
	computed: {},
	watch: {
	},
	updated() {
	},
	methods: {
		loadScript(src, callback) {
			return new Promise((resolve, reject) => {
				const script = document.createElement('script');
				script.src = src;
				script.async = true;
				script.onload = () => {
					if (callback) callback();
					resolve();
				};
				script.onerror = reject;
				document.head.appendChild(script);
			});
		},
		parseEntities(){
			//console.log(this.entitiesDATA);
			const lines = this.entitiesDATA.split('\n');
            const headers = lines[0].split(',');
            const result = {};

            for (let i = 1; i < lines.length; i++) {
                const values = lines[i].match(/(".*?"|[^",\r\n]+|(?<=,)(?=,))/g);//.split(',');
                const dcc = values[0];
                result[dcc] = { entities: {}, omics: {}, povs: {}, logo: '', info: {} };

                for (let j = 1; j < headers.length; j++) {
                const [prefix, key] = headers[j].split('_');
                if (prefix && key) {
                    let group;
                    if (prefix === 'a') {
                        group = 'entities';
                    } else if (prefix === 'b') {
                        group = 'omics';
                    } else if (prefix === 'c') {
                        group = 'povs';
                    } else if (prefix === 'd') {
                        group = 'logo';
                        result[dcc][group] = values[j];
                        continue;
                    }else if (prefix === 'r'){
                        group = 'info';
                        result[dcc][group][key.trim()] = values[j];
                        continue;
                    }
                    result[dcc][group][key.trim()] = values[j] ? parseInt(values[j]): null;
                }
                }
            }

			return result;
			//this.parsedData = result;
			//console.log(this.parsedData);
		},
		outHandler(e){
            if(this.freezeSelection){
                document.querySelectorAll(`[data-group]`).forEach(item => item.classList.remove('on', 'on2', 'on3'));
				const targetElement = document.querySelector(`[data-value="${this.currPov}"]`);
				if (targetElement) targetElement.dispatchEvent(new Event('mouseover'));
            }else{
                document.querySelectorAll(`[data-group]`).forEach(item => item.classList.remove('on', 'on2', 'on3', 'onA', 'on2A', 'on3A'));
                document.querySelectorAll('.leader-line').forEach(item => item.remove());
                document.querySelector('.dccs').classList.remove('active');
            }
            document.querySelector(`.omics`).classList.remove('active');
            this.currHoverGroup = null;
            document.querySelector('.line2info').innerHTML = '';
			document.querySelector('.line2note').classList.remove('hidden')
        },
		hoverHandler(e){
            const val = e.target.dataset.value;

			document.querySelector('.line2note').classList.add('hidden');

            //console.log(parsedData[val]['info'][this.currPov]);
            if(this.currPov) document.querySelector('.line2info').innerHTML = `<div><span style="font-weight:bold">${val}</span> ${this.parsedData[val]['info'][this.currPov].replace(/['"]+/g, '')}</div>`;

            //highlight entities
            if(this.currHoverGroup!=='entities'){
                for (const [key, value] of Object.entries(this.parsedData[val]['entities'])) {
                    if(value){
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }
            
            //highlight omics
            if(this.currHoverGroup!=='omics'){
                document.querySelector(`.omics`).classList.add('active');
                for (const [key, value] of Object.entries(this.parsedData[val]['omics'])) {
                    if(value){
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }
            //highlight povs
            if(this.currHoverGroup!=='povs'){
                for (const [key, value] of Object.entries(this.parsedData[val]['povs'])) {
                    //console.log(value, key);
                    if(value){
                        const el = document.querySelector(`[data-value="${key}"]`);
                        if(value===1){
                            if(!this.freezeSelection){
                                const l = new LeaderLine(
                                    e.target,
                                    document.querySelector(`[data-value="${key}"]`),
                                    {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', endPlug: 'behind', endSocketGravity: 100, 
                                    path: 'fluid', gradient: {endColor: '#ff7f5090', startColor:'#ff7f5090'}, dash: {len: 2, gap: 1, animation: true},  size: 1}
                                );
                            }
                        }
                        if(value===2){
                            if(!this.freezeSelection){
                                const l = new LeaderLine(
                                    e.target,
                                    document.querySelector(`[data-value="${key}"]`),
                                    {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', endPlug: 'behind', endSocketGravity: 80, 
                                    path: 'fluid', gradient: {endColor: '#ff7f5090', startColor:'#ff7f5090'}, dash: {len: 4, gap: 2, animation: true},  size: 2}
                                );
                            }
                        }
                        if(value===3){
                            if(!this.freezeSelection){
                                const l = new LeaderLine(
                                    e.target,
                                    document.querySelector(`[data-value="${key}"]`),
                                    {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', endPlug: 'behind', endSocketGravity: 60, 
                                    path: 'fluid', gradient: {endColor: '#ff7f5090', startColor:'#ff7f5090'}, dash: {len: 6, gap: 3, animation: true},  size: 3}
                                );
                            }
                        }
                        //el.classList.add(value===2 && !el.classList.contains('on')?'on2':'on');
                    }
                }
            }
        },
		hoverHandler2(e){
            console.log('this.currHoverGroup', this.currHoverGroup);
            //if(this.currHoverGroup) return;	
            const group = e.target.dataset.group;
            let val = e.target.dataset.value;
			console.log('continuing', group, val);
            this.currHoverGroup = group;
            console.log('---this.currHoverGroup', this.currHoverGroup);
            if(group==='povs') {
				document.querySelector('.dccs').classList.add('active');
				document.querySelector('.line2note').classList.add('hidden');
				if(this.freezeSelection) document.querySelectorAll('.leader-line').forEach(item => item.remove());
			}
			
            //highlight dccs
            for (const [key, value] of Object.entries(this.parsedData)) {
                const el = document.querySelector(`[data-value="${key}"]`);
                if(value[group][val]===1){
                    //el.classList.add('on');
                    if (group==='povs'){
						console.log(group, val, this.currPov)
                        //if(this.freezeSelection){
                            el.classList.add('onA');
                            const l = new LeaderLine(
                                document.querySelector(`[data-value="${key}"]`),
                                e.target,
                                {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', startPlugColor: '#34679a', endPlug: 'behind', endSocketGravity: 100, 
                                path: 'fluid', gradient: {startColor: '#ff7f5090', endColor:'#ff7f5090'}, dash: {len: 2, gap: 1, animation: true},  size: 1}
                            );
						//}
                    }else{
                        el.classList.add('on');
                    }
                    //el.classList.add('on');
                    //el.dispatchEvent(new Event('mouseover'));
                }
                if(value[group][val]===2){
                    //el.classList.add('on2');
                    if (group==='povs'){
                        //if(!this.freezeSelection){
                            el.classList.add('on2A');
                            const l = new LeaderLine(
                                document.querySelector(`[data-value="${key}"]`),
                                e.target,
                                {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', startPlugColor: '#34679a', endPlug: 'behind', endSocketGravity: 80, 
                                path: 'fluid', gradient: {startColor: '#ff7f5090', endColor:'#ff7f5090'}, dash: {len: 4, gap: 2, animation: true},  size: 2}
                            );
                        //}
                    }else{
                        el.classList.add('on2');
                    }
                }
                if(value[group][val]===3){
                    //el.classList.add('on3');
                    if (group==='povs'){
                        //if(!this.freezeSelection){
                            el.classList.add('on3A');
                            const l = new LeaderLine(
                                document.querySelector(`[data-value="${key}"]`),
                                e.target,
                                {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', startPlugColor: '#34679a', endPlug: 'behind', endSocketGravity: 60, 
                                path: 'fluid', gradient: {startColor: '#ff7f5090', endColor:'#ff7f5090'}, dash: {len: 6, gap: 3, animation: true},  size: 3}
                            );
                        //}
                    }else{
                        el.classList.add('on3');
                    }
                }
            }
        },
		povHandler(e){
            const group = e.target.dataset.group;
            const val = e.target.dataset.value;
            if(!e.target.classList.contains('selected')){
				document.querySelectorAll('[data-group="povs"]').forEach(el => {el.classList.remove('selected')});
                e.target.classList.add('selected');
                document.querySelector('.line2').classList.add('open');
                document.querySelector('.dccs').classList.add('active');
                this.currPov = val;
                this.freezeSelection = true;
            }else{
				e.target.classList.remove('selected');
                document.querySelector('.line2').classList.remove('open');
                document.querySelector('.dccs').classList.remove('active');
                this.currPov = null;
                this.freezeSelection = false;
            }
        },


		async loadCSV(url) {
			await fetch(url)
			.then(response => {
				if (!response.ok) {
					throw new Error('Network response was not ok');
				}
				console.log(response.text());
			})
			.catch(error => {
				console.error('Error loading CSV:', error);
			});
		},

		minVidEnd(e){
			e.target.dataset.loopCount++;
			if(e.target.dataset.loopCount < e.target.dataset.loopMax){
				e.target.play();
			}else{
				e.target.classList.add('paused');
			}
		},
		minVidHover(e){
			if(e.target.classList.contains('paused')){
				e.target.play();
			}
		},
		minVidHoverOut(e){
			if(e.target.classList.contains('paused')){
				e.target.pause();
			}
		}
	}
});

$(function () {
});
</script>
<style>
.mdkp-body.flex-body.front-page {
    overflow-x: visible;
	flex: none;
}
.mdkp-body.flex-body:has(.kc-wrap){
	padding-top: 0;
}
.fp-search-section {
    margin: 50px 0 20px;
}
.multi-section.wrapper-section-0:has(.col-md-12.wrapper-section-0:empty){
	display: none;
}
#byor_single_search {
    border: 2px solid #ff6600;
    padding: 20px;
}
.col-md-12:has(.kc-wrap) {
    padding: 0;
}
.kc-hero {
    background: #f7f6f6;
}
.blurb {
    display: flex;
    align-items: center;
	justify-content: center;
	padding: 30px 20px;
    gap: 20px;
}
.blurb div {
	font-size: 18px;
    color: #7c7c7c;
}
.blurb span {
	color: #f26822;
}
.blurb .logo {
    width: 100px;
    flex: unset;
}
.blurb .logo img {
    width: -webkit-fill-available;
    object-fit: contain;
}
.map-bg{
	 /*background: #f7f6f6;*/
	 display: flex;
    flex-direction: column;
    align-items: center;
	/*box-shadow: inset 0px 10px 10px -10px #00000010, inset 0px -10px 10px -10px #00000010;*/
}
.map-title {
    margin: 20px 0 0 0;
    text-transform: uppercase;
    font-size: 12px;
    font-weight: bold;
    letter-spacing: 1px;
	margin: 0 auto;
    position: absolute;
    left: 0;
    padding: 0 20px;
    width: 250px;
    margin-top: 25px;
    display: flex;
    flex-direction: column;
    color: #ff6600;
}
.map-title.v2 {
    margin-top: -10px;
}
.map-title span{
	text-transform: none;
    font-weight: normal;
    letter-spacing: normal;
	color: #7c7c7c;
}
.map {
	display: flex;
	flex-direction: column;
	gap: 0px;
	width: 770px;
	margin: 0 auto;
	padding: 0px 0 40px 0;
}
.povs,
.dccs,
.omics,
.entities{
	display: flex;
	justify-content: center;
	gap: 10px;
	position: relative;
}
.povs{
	gap: 30px;
}
.pov {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: space-between;
	gap: 0px;

	/*width: 170px;
	width: 50px;
	aspect-ratio: 1;*/

	background: none;
	cursor: pointer;
	
	text-align: center;   
}
.pov:hover {
	background: none !important;
}
.pov.selected {
	/*border-bottom: solid 3px #ff6600;*/
}
.pov span {
	background: none;
	padding: 3px 0 1px 0;
	flex: 1 1 auto;
	color: black;
	display: flex;
	align-items: center;
	justify-content: center;
	pointer-events: none;
	text-transform: uppercase;
	font-size: 10px;
	font-weight: bold;
	letter-spacing: 1px;
}
.pov span{
	border-bottom: 1px solid transparent;
}
.pov:hover span,
.pov.selected span {
	background: none;
	color: #ff6600;
}
.pov img {
	width: -webkit-fill-available;
	height: auto;
	aspect-ratio: 1;
	object-fit: contain;
	pointer-events: none;
	padding: 5px;
}
.povs .img {
    width: 50px;
    height: 50px;
	pointer-events: none;
	border-radius: 5px;
}

.dccs, .omics, .entities{
	margin: 0 0 15px -25% !important;
    width: 150% !important;
	/*margin: 0 0 15px 0;
    width: 100%;*/
}
.dcc {
	display: flex;
	flex: 1 1 auto;
	align-items: center;
	justify-content: center; 

	width: 50px;
	aspect-ratio: 1;

	background: none;
	border-top: 3px solid transparent;
	cursor: default;
	   
	transition: .2s all ease-out;
}
.dcc:hover {
	background: none !important;
	border-top: solid 3px #ff6600;
}
.dcc img {
	width: -webkit-fill-available;
	height: auto;
	object-fit: contain;
	margin: 0 10px;
	pointer-events: none;
	mix-blend-mode: darken;
}
.dcc.onA, .dcc.on2A, .dcc.on3A{
	border-top: solid 1px transparent;
	padding-top: 2px;
}
.dcc.on{
	border-top:3px solid #ff6600 !important;
	/*background: #f0f0f0;
	outline: 5px solid white;
	outline-offset: -5px;*/
}
.dcc.on2{
	/*background: #f0f0f0;
	outline: 2.5px solid #e6e6e6;*/
}
.dcc.on3{
	/*background: #f0f0f0;
	outline: 10px solid #e6e6e6;*/
}
.dccs.active .dcc:hover{
	border-top:3px solid #ff6600;
}

.omics {
	display: flex;
	gap: 0;
	align-items: center;
	justify-content: center; 

	margin: 0 0 10px 0;

	background: #eaeaea;
	cursor: default;
}
.omic{
	display: flex;
	flex: 1 1 auto;
	align-items: center;
	justify-content: center;

	aspect-ratio: unset;
	height: 20px;
	
	text-transform: uppercase;
	font-size: 10px;
	letter-spacing: 1px;
	font-weight: 600;

	cursor: default;
	transition: .2s all linear;
}
.omic:hover{
	filter: saturate(5);
}
.omics.active .omic{
	min-width: 100px;
	flex: 0 0 auto;
	overflow: hidden;
	filter: grayscale(100%);
}
.omic span,
.entity span{
	pointer-events: none;
}
.omics.active .omic.on{
	flex: 1 1 auto;
	filter: saturate(5);
}
.omics [data-value="Epigenomics"]{
	background: #ffadad50;
}
.omics [data-value="Genomics"]{
	background: #ffd6a550;
}
.omics [data-value="Transcriptomics"]{
	background: #fdffb650;
}
.omics [data-value="Proteomics"]{
	background: #caffbf50;
}
.omics [data-value="Metabolomics"]{
	background: #9bf6ff50;
}

.entity {
	display: flex;
	flex: 1 1 auto;
	align-items: center;
	justify-content: center; 
	
	width: auto;
	height: 50px;

	background: none;   
	border-bottom: 3px solid transparent;
	cursor: default;

	text-transform: uppercase;
	font-size: 10px;
	font-weight: bold;
	letter-spacing: 1px;
}
.entity:hover,
.entity.on{
	/*background:#ffa600;*/
	border-bottom: 3px solid #ff6600;
}

.line2 {
	font-size: 14px;
	height: 100px;
	display: flex;
	align-items: center;
	justify-content: center;
	width: 150%;
    padding: 0 300px;
    text-align: center;
    margin: 0 0 0 -25%;
	text-align: center;
	transition: .2s all ease-out;
	z-index: 2;
	position: relative;
}
.line2.open:has(.line2info:not(:empty)){
	backdrop-filter: blur(2px);
}
.hidden{
	display:none;
}

.map-label {
	position: absolute;
    right: 50%;
    transform: translateX(50%);
    line-height: 12px;
    width: 100vw;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    text-align: right;
    font-size: 11px;
    height: 100%;
    padding: 0 10px 0 0;
    border-right: 5px solid #dddddd;
    color: #8f8f8f;
	pointer-events: none;
}
.map-label>div {
    width: 70px;
}

.line2 .map-label{
	height: calc(100% - 20px);
	flex-direction: column;
    align-items: end;
    justify-content: center;
}
.relevance-legend {
    display: flex;
    flex-direction: column;
	gap: 0px;
	margin: 5px 0 0 0;
}
.relevance-legend>div {
    padding: 0 20px 0 0;
	position: relative;
}
.relevance-legend>div:after {
	position: absolute;
    content: '';
    width: 15px;
    height: 0;
    right: 0;
    top: 50%;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
    
}
.relevance-hi:after{
	border-top: 3px dashed #ff6600;
}
.relevance-md:after{
	border-top: 2px dashed #ff6600;
}
.relevance-lo:after{
	border-top: 1px dashed #ff6600;
}


.kc-wrap {
    width: 770px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap: 20px;
}
.kc-title {
    font-size: 22px;
    margin: 10px 0 20px;
    text-transform: uppercase;
}
.a {
    width: 100%;
    display: flex;
    gap: 20px;
    justify-content: space-between;
	/*background: linear-gradient(0deg, transparent, #f7f6f6);*/
}
.b {
    max-width: 50%;
    background: #f6f6f6;
    min-height: 500px;
    display: flex;
    align-items: flex-start;
    justify-content: flex-start;
    flex: 1 1 auto;
	flex-direction: column;
    padding: 40px 0 40px 40px;
}
.quick .b {
    min-height: 0;
	align-items:center;
    justify-content: flex-start;
	flex: 1 1 auto;
    width: 40%;
	background: #f7f6f6;
    border-radius: 20px 0 0 50px;
    border-radius: 20px;
	padding: 30px 0px 30px 30px;
}
.c-title {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 0 0 10px 0;
}
.b p {
    font-size: 22px;
	margin:0;
}
.b a,
.section a {
    color: black !important;
	background: white;
    text-decoration: none;
    align-self: flex-end;
    border: 1px solid #ccc;
    padding: 3px 10px;
    border-radius: 5px;
	margin: 10px 0 0 0;
}
.b ul {
    padding: 0;
    list-style-type: none;
}
.b li {
    margin: 0 0 10px 0;
}
.b li p{
	font-size: 16px;
	margin: 0;
}

.blurbA {
    width: 100%;
    align-self: center;
    margin: 0;
}
.b:nth-child(1) {
    /*border-radius: 0 20px 50px 0;
	padding: 40px 40px 40px 0;*/
	padding: 30px 30px 30px 0;
}
.b:nth-child(1) li {
    text-align: right;
}

.c{
    display: flex;
    align-items: center;
    padding: 0 1px;
	background: white;
}
.c-body {
    margin: 0 0 10px 0;
}

.bold{
	font-weight: bold;
	color:#ff6600;
}

.section {
    min-height: 200px;
    width: 100%;
    margin: 0 auto;
	padding: 30px calc((100% - 770px) / 2);
	display: flex;
    flex-direction: column;
}
.section-title {
    font-size: 20px;
    letter-spacing: .2px;
}
.section-subtitle {
    text-transform: uppercase;
    font-size: 14px;
	margin: 5px 0 10px;
}
.section-wrap {
    display: flex;
    flex-direction: row;
}
.section-col {
    display: flex;
    flex-direction: column;
    flex: 1 1 auto;
    padding: 10px;
}
.section .placeholder {
    background: #f7f6f6;
    width: 365px;
    height: 215px;
	display: flex;
	align-items: center;
	justify-content: center;
	text-transform: uppercase;
    font-size: 14px;
	cursor: pointer;
	color: #ccc;
}
.partnerships{
	display:flex;
	flex-direction: row;
	gap: 20px;
}
.partner {
    height: 70px;
    padding: 5px;
    padding: 5px;
    display: flex;
    align-items: center;
}
.partner img {
    height: 100%;
    width: auto;
    object-fit: contain;
}

.section:has(.byor-single-search-wrapper) {
    min-height: auto;
	padding-bottom: 60px;
}
.byor-single-search-wrapper h3 {
    display: none;
}

.section.cdfe-centers {
    min-height: auto;
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    font-weight: bold;
	display:none;
}

.search-try {
    font-size: 14px;
    display: flex;
    gap: 10px;
    color: #7c7c7c;
    padding: 3px 5px 0;
    justify-content: center;
}
.search-try span {
    cursor: pointer;
}
.search-try span:first-child {
    color: #ff6600;
    cursor: default;
}

.hideable{
	opacity:0;
	transition: 0.2s all linear;
}
.map-bg:hover .hideable,
.section:hover .hideable{
	opacity: 1;
}

.mini-card-video {
    width: -webkit-fill-available;
    background: white;
}
.mini-card-video video {
    width: -webkit-fill-available;
    display: block;
}
</style> 

