<template>
	<div>
		<div class="kc-hero">
			<div class="kc-wrap">
				<div class="blurb">
					<div class="logo"><img src="https://hugeampkpncms.org/sites/default/files/users/user32/cfde_kc_logo_c.svg"></div>
					<div><span class="highlight">The Knowledge Center</span> integrates data and knowledge generated by ground-breaking research programs in the NIH Common Fund Data Ecosystem.
						<span>Use the KC to see curated and precomputed analyses of data within and across Common Fund projects.</span>
					</div>
					<!--<div><span>Explore</span> the diverse range of omics data<br> generated by Common Fund Programs.</div>
					<div><span>Gain knowledge</span>, tools and other digital resources to enable hypothesis testng and new discoveries.</div>-->
				</div>
				<!--
				<div class="kc-title">The Common Fund Data Ecosystem</div>
				<div class="blurbA">
					<p>
						The CFDE Data Resource and Knowledge Centers aim to unify access to the 
						varied, large-scale data generated by Common Fund Programs, 
						and to provide knowledge, tools and other digital resources to enable hypothesis testng and new discoveries.
					</p>
					Explore the diverse range of omics data generated by Common Fund Programs. 
					Gain knowledge, tools and other digital resources to enable hypothesis testng and new discoveries.
				</div>
				-->
				<div class="blurbA"></div>
			</div>
			<div class="overlay-window context-info">
				<div class="overlay-window-close" data-info-el="context-info" @click="hideInfoContent($event)">&#10005;</div>
				We defined <a href="/research.html?pageid=KC_research_contexts">four research contexts</a> and then used a combination of Large Language Models (LLM) and manual curation to weight the relevance of the knowledge produced by each CFDE program to each context (for details, <a href="/research.html?pageid=kc_documentation">see here</a>). <br>&nbsp;&nbsp;Setting a research context will change the ordering of DCCs on each of the KC pages and also modify the text describing and contextualizing the results shown. <br>&nbsp;&nbsp;You can change or remove a research context on any page.
			</div>
			<div class="map-bg">
				<div class="map-title boxed" style="display:none"><span>> </span>Explore the diagram with your mouse to see connections between research programs, their omics data types and biological entities, with relevance to different research contexts.
					<div class="how">Source<span class="btn-icon">?</span></div>
				</div>
				<div class="map-title2">
					<span>SET RESEARCH CONTEXT
						<span class="btn-icon" 
							data-info-el="context-info"
							@click="showInfoContent($event)"
						>
						?
						</span>
					</span>
					To tailor information shown throughout the KC to a selected research area.
				</div>
				<div class="map-pov-message">Click to set context</div>
				<div class="map" v-if="this.parsedData">
					<div class="povs">
						<div class="map-label hideable"><div>Research Context</div></div>
						<div v-for="(value, key) in this.parsedData[Object.keys(this.parsedData)[0]]['povs']"
							class="pov"
							data-group="povs"
							:data-value="key"
							@mouseover="hoverHandler2($event)"
							@mousemove="povMoveHandler($event)"
							@mouseout="outHandler($event)"
							@click="povHandler($event)">
							<div class="img">
								<img :src="`https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/${key}.svg`">
							</div>
							<span>{{ key.replace('-', ' ') }}</span>
						</div>
					</div>
					<div class="line2">
						<div class="map-label hideable">
							<div>
								<div>Relevance</div>
								<div class="relevance-legend">
									<div class="relevance-hi">high</div>
									<div class="relevance-md">med</div>
									<div class="relevance-lo">low</div>
								</div>
							</div>
						</div>
						<div class="line2info"></div>
						<div class="line2note"></div>
					</div>
					<div class="dccs">
						<div class="map-label hideable"><div>Common Fund Programs</div></div>
						<template v-for="(value, key, index) in this.parsedData">
							<div 
								class="dcc"
								data-group="dccs"
								:data-value="key"
								@mouseover="hoverHandler($event)"
								@mouseout="outHandler($event)"
							>
								<img :src="value['logo']">
							</div>
							<div class="dcc-separator"></div>
						</template>
					</div>
					<div class="omics">
						<div class="map-label hideable"><div>Omics Data</div></div>
						<div v-for="(value, key) in this.parsedData[Object.keys(this.parsedData)[0]]['omics']"
							class="omic"
							data-group="omics"
							:data-value="key"
							@mouseover="hoverHandler2($event)"
							@mouseout="outHandler($event)">
							<span>{{ key }}</span>
						</div>
					</div>
					<div class="entities">
						<div class="map-label hideable"><div>Searchable Entities</div></div>
						<div v-for="(value, key) in this.parsedData[Object.keys(this.parsedData)[0]]['entities']"
							class="entity"
							data-group="entities"
							:data-value="key"
							@mouseover="hoverHandler2($event)"
							@mouseout="outHandler($event)">
							<span>{{ key }}</span>
						</div>
					</div>
				</div>
			</div>
		
		
			<div class="section section-search-drc">
				<div class="section-title"><div class="drc-logo"><img src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/DRC_logo.png"></div>CFDE WORKBENCH</div>
				<div class="section-wrap">
					<div class="section-col">
						<div class="section-subtitle">Visit our sister resource to query, access, and compute Common Fund datasets.</div>
						<a href="https://data.cfde.cloud/" target="_blank">Visit CFDE WORKBENCH</a>
					</div>
				</div>
			</div>
			<div class="section section-search-kc">
				<div class="map-title2 v2">
					<span>SEARCH THE KC</span>
					<div class="search-context notset">Set <span class="search-context-label">genetics</span> context?<button @click="setContext()">yes</button></div>
					<div class="search-context set">Help text and results order will be tailored to a  <span class="search-context-label">genetics</span> use case.</div>
				</div>
				<research-single-search
					:single-search-config="sectionConfigs['content']"
					:phenotypes="phenotypesInUse"
					:utils="utilsBox"
				></research-single-search> 
				<div class="search-extras">
					<div class="search-try"><span>Try</span><a href="/research.html?entity=gene&gene=BDH2&pageid=kc_entity&tissue=blood">BDH2</a><a href="/research.html?disease=MONDO%3A0004985&entity=disease&pageid=kc_entity&tissue=blood">Bipolar disorder</a></div>
				</div>
				<!--<div class="search-icon"><img src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/geneticist.svg"></div>-->
			</div>
		</div>

		<div id="kc-section-a" class="section">
			<div class="section-title">See curated summaries of knowledge from CFDE programs</div>
			<div class="section-wrap">
				<div class="section-col">
					<div class="section-subtitle">Genes</div>
					<div class="placeholder">
						<div class="mini-card-video">
							<video 
								@ended="minVidEnd($event)" 
								@mouseover="minVidHover($event)"
								@mouseout="minVidHoverOut($event)"
								data-loop-max="1"
								data-loop-count="0"
								src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_tools/KC_gene_page_480.mp4" 
								poster="https://hugeampkpncms.org/sites/default/files/users/user32/kc_tools/KC_gene_page.jpg" 
								autoplay muted playsinline 
							/>
                        </div>
					</div>
				</div>
				<div class="section-col">
					<div class="section-subtitle">Diseases</div>
					<div class="placeholder">
						<div class="mini-card-video">
                        	<video 
								@ended="minVidEnd($event)" 
								@mouseover="minVidHover($event)"
								@mouseout="minVidHoverOut($event)"
								data-loop-max="1"
								data-loop-count="0"
								src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_tools/KC_disease_page_480.mp4" 
								poster="https://hugeampkpncms.org/sites/default/files/users/user32/kc_tools/KC_disease_page.jpg" 
								autoplay muted playsinline 
							/>
                        </div>
					</div>
				</div>
			</div>
		</div>

		<div id="kc-section-b" class="section">
			<div class="section-title">Knowledge about CFDE programs and partnerships</div>
			<div class="section-wrap">
				<div class="section-col">
					<div class="section-subtitle">CFDE programs</div>
					<div class="placeholder">
						<div class="mini-card-video">
							<a href="/research.html?pageid=kc_dccs">
								<video 
									@ended="minVidEnd($event)" 
									@mouseover="minVidHover($event)"
									@mouseout="minVidHoverOut($event)"
									data-loop-max="1"
									data-loop-count="0"
									src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_tools/Landing_DCCs_480.mp4" 
									poster="https://hugeampkpncms.org/sites/default/files/users/user32/kc_tools/Landing_DCCs.jpg" 
									autoplay muted playsinline 
								/>
							</a>
                        </div>
					</div>
				</div>
				<div class="section-col">
					<div class="section-subtitle">Partnerships</div>
					<div class="placeholder">(coming soon)</div>
				</div>
			</div>
		</div>

		<div id="kc-section-c" class="section">
			<div class="section-title"><div class="drc-logo"><img src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/DRC_logo.png"></div>CFDE WORKBENCH</div>
			<div class="section-wrap">
				<div class="section-col">
					<div class="section-subtitle">Visit our sister resource to query, access, and compute Common Fund datasets.</div>
					<ul>
						<li>Search across all Common Fund metadata and processed data.</li>
						<li>Cloud tools to interrogate data sets from various Common Fund programs.</li>
						<li>Training and outreach to highlight Common Fund data and how to use it effectively.</li>
					</ul>
					<a href="https://data.cfde.cloud/" target="_blank">Visit CFDE WORKBENCH</a>
				</div>
			</div>
		</div>

		<div id="kc-section-d" class="section">
			<div class="section-title">Funding</div>
			<div class="section-wrap">
				<div class="section-col">
					<div class="section-subtitle"></div>	
					<div class="logo"><img src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/NIH_logo.png"></div>
				</div>
			</div>
		</div>
			
		<!--
		<div class="section" style="background: #f7f6f6;">
			<div class="a quick">
				<div class="b">
					<div class="c-title"><p>Knowledge Center</p></div>
					<div class="c-body">Use the Knowledge Center to see <span class="bold">curated</span>, 
						<span class="bold">synthesized</span>, and <span class="bold"> analyzed</span> results from Common 
						Fund data in a research context.
					</div>
					<a href="/research.html?pageid=kc_landing">Learn More</a>
				</div>
				<div class="c">
					
				</div>
				<div class="b">
					<div class="c-title"><p>Data Resource Center</p></div>
					<div class="c-body">Use the Data Resource Center to <span class="bold">query</span>, 
						<span class="bold">access</span>, and <span class="bold"> compute</span> Common Fund datasets
						and metadata for your research.
					</div>
					<a href="/research.html?pageid=kc_landing">Visit DRC</a>
				</div>
				
				
			</div>
		</div>

		<div class="section">
			<div class="kc-title">Foundational Knowledge</div>
			<div style="display:flex; flex-direction: row; gap: 20px;">
				<div style="width:100%; height:220px; background:#f7f6f6; display:flex; align-items: center; justify-content: center;">
					Foundation Page vid
				</div>
				<div class="c-body" style="display: flex; flex-direction: column; align-items: center; justify-content: flex-end; gap:10px">
					In-depth summaries for each Common Fund program including its research focus, 
					omics data types, tools, resources and more.
					<a href="/research.html?pageid=kc_landing" style="align-self: flex-start;">Explore Foundational Knowledge</a>
				</div>
				
			</div>
		</div>
		
		<div class="section">
			<div class="kc-title">Partnerships</div>
			<div class="partnerships">
				<div class="partner">
					<img src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/NIH_logo.png">
				</div>
				<div class="partner">
					<img src="https://hugeampkpncms.org/sites/default/files/users/user32/kc_icons/CFDE_logo.png">
				</div>
			</div>
		</div>
		-->
		
	</div>
</template>

<script>
import Vue from "vue";
import $ from "jquery";
import ResearchSingleSearch from "@/components/researchPortal/ResearchSingleSearch.vue";
//import uiUtils from "@/utils/uiUtils";
import { BootstrapVueIcons } from "bootstrap-vue";

Vue.use(BootstrapVueIcons);

export default Vue.component("cfde-eco-system", {
	props: ["sectionConfigs", "phenotypesInUse", "utilsBox", "keyParams"],
	data() {
		return {
			parsedData: null,
			currPov: null,
			currHoverGroup: null,
			freezeSelection: false
		};
	},
	mounted() {
		
		this.loadScript('https://cdn.jsdelivr.net/npm/leader-line@1.0.7/leader-line.min.js', async () => {
			const data = await this.loadFile(this.sectionConfigs["content"]["custom"]["viz data"])
			this.parsedData = await this.parseEntities(data);
			setTimeout(function () {
				const params = new URLSearchParams(document.location.search);
				const ctxtParam = params.get('context');
				const ctxt = ctxtParam ? ctxtParam.replace('_', '-') : 'genetics';
				const targetElement = document.querySelector(`[data-value="${ctxt}"]`);
				console.log(targetElement);
				if (targetElement) {
					targetElement.dispatchEvent(new Event('mouseover'));
					targetElement.dispatchEvent(new Event('click'));
					targetElement.dispatchEvent(new Event('mouseout'));
				}
			}, 100);
		});	
		
		
	},
	computed: {},
	watch: {
	},
	updated() {
	},
	methods: {
		loadScript(src, callback) {
			return new Promise((resolve, reject) => {
				const script = document.createElement('script');
				script.src = src;
				script.async = true;
				script.onload = () => {
					if (callback) callback();
					resolve();
				};
				script.onerror = reject;
				document.head.appendChild(script);
			});
		},
		async loadFile(src){
			//must use dataset endpoint to load csv file from hugeampkpncms (otherwise CORS error)
			const fetchUrl = "https://hugeampkpncms.org/servedata/dataset?dataset=" + src;
			//however, dataset enpoint parses the original csv and escapes special characters
			let data = await fetch(fetchUrl).then(resp => resp.text(fetchUrl));
			//we must undo all of that to get the original data
			data = data.replace(/\\u0022/g, '"'); 		//quotes
			data = data.replace(/\\\//g, '/');			//slashes
			data = data.replace(/\\n/g, '\n');			//line breaks
			data = data.replace(/\\r/g, '\r');			//carriage returns
			data = data.substring(1, data.length - 1);	//remove surrounding quotes
			return data;
		},
		async parseEntities(data){
			const lines = data.split('\n');
            const headers = lines[0].split(',');
            const result = {};

            for (let i = 1; i < lines.length; i++) {
                const values = lines[i].match(/(".*?"|[^",\r\n]+|(?<=,)(?=,))/g);//.split(',');
                const dcc = values[0];
                result[dcc] = { entities: {}, omics: {}, povs: {}, logo: '', info: {} };

                for (let j = 1; j < headers.length; j++) {
                const [prefix, key] = headers[j].split('_');
                if (prefix && key) {
                    let group;
                    if (prefix === 'a') {
                        group = 'entities';
                    } else if (prefix === 'b') {
                        group = 'omics';
                    } else if (prefix === 'c') {
                        group = 'povs';
                    } else if (prefix === 'd') {
                        group = 'logo';
                        result[dcc][group] = values[j];
                        continue;
                    }else if (prefix === 'r'){
                        group = 'info';
                        result[dcc][group][key.trim()] = values[j];
                        continue;
                    }
                    result[dcc][group][key.trim()] = values[j] ? parseInt(values[j]): null;
                }
                }
            }

			return result;
			//this.parsedData = result;
			//console.log(this.parsedData);
		},
		outHandler(e){
            if(this.freezeSelection){
                document.querySelectorAll(`[data-group]`).forEach(item => item.classList.remove('on', 'on2', 'on3'));
				const targetElement = document.querySelector(`[data-value="${this.currPov}"]`);
				if (targetElement) targetElement.dispatchEvent(new Event('mouseover'));
            }else{
                document.querySelectorAll(`[data-group]`).forEach(item => item.classList.remove('on', 'on2', 'on3', 'onA', 'on2A', 'on3A'));
                document.querySelectorAll('.leader-line').forEach(item => item.remove());
                document.querySelector('.dccs').classList.remove('active');
            }
            document.querySelector(`.omics`).classList.remove('active');
            this.currHoverGroup = null;
            document.querySelector('.line2info').innerHTML = '';
			document.querySelector('.line2note').classList.remove('hidden');
			document.querySelector('.map-pov-message').style.display = 'none';
        },
		hoverHandler(e){
            const val = e.target.dataset.value;

			document.querySelector('.line2note').classList.add('hidden');

            //console.log(parsedData[val]['info'][this.currPov]);
            if(this.currPov) document.querySelector('.line2info').innerHTML = `<div><span style="font-weight:bold">${val}</span> ${this.parsedData[val]['info'][this.currPov].replace(/['"]+/g, '')}</div>`;

            //highlight entities
            if(this.currHoverGroup!=='entities'){
                for (const [key, value] of Object.entries(this.parsedData[val]['entities'])) {
                    if(value){
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }
            
            //highlight omics
            if(this.currHoverGroup!=='omics'){
                document.querySelector(`.omics`).classList.add('active');
                for (const [key, value] of Object.entries(this.parsedData[val]['omics'])) {
                    if(value){
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }
            //highlight povs
            if(this.currHoverGroup!=='povs'){
                for (const [key, value] of Object.entries(this.parsedData[val]['povs'])) {
                    //console.log(value, key);
                    if(value){
                        const el = document.querySelector(`[data-value="${key}"]`);
                        if(value===1){
                            if(!this.freezeSelection){
                                const l = new LeaderLine(
                                    e.target,
                                    document.querySelector(`[data-value="${key}"]`),
                                    {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', endPlug: 'behind', endSocketGravity: 100, 
                                    path: 'fluid', gradient: {endColor: '#ff7f5090', startColor:'#ff7f5090'}, dash: {len: 2, gap: 1, animation: true},  size: 1}
                                );
                            }
                        }
                        if(value===2){
                            if(!this.freezeSelection){
                                const l = new LeaderLine(
                                    e.target,
                                    document.querySelector(`[data-value="${key}"]`),
                                    {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', endPlug: 'behind', endSocketGravity: 80, 
                                    path: 'fluid', gradient: {endColor: '#ff7f5090', startColor:'#ff7f5090'}, dash: {len: 4, gap: 2, animation: true},  size: 2}
                                );
                            }
                        }
                        if(value===3){
                            if(!this.freezeSelection){
                                const l = new LeaderLine(
                                    e.target,
                                    document.querySelector(`[data-value="${key}"]`),
                                    {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', endPlug: 'behind', endSocketGravity: 60, 
                                    path: 'fluid', gradient: {endColor: '#ff7f5090', startColor:'#ff7f5090'}, dash: {len: 6, gap: 3, animation: true},  size: 3}
                                );
                            }
                        }
                        //el.classList.add(value===2 && !el.classList.contains('on')?'on2':'on');
                    }
                }
            }
        },
		hoverHandler2(e){
            console.log('this.currHoverGroup', this.currHoverGroup);
            //if(this.currHoverGroup) return;	
            const group = e.target.dataset.group;
            let val = e.target.dataset.value;
			console.log('continuing', group, val);
            this.currHoverGroup = group;
            console.log('---this.currHoverGroup', this.currHoverGroup);
            if(group==='povs') {
				document.querySelector('.dccs').classList.add('active');
				document.querySelector('.line2note').classList.add('hidden');
				if(this.freezeSelection) document.querySelectorAll('.leader-line').forEach(item => item.remove());
				if(!e.target.classList.contains('selected')){
					document.querySelector('.map-pov-message').style.display = 'block';
				}
			}
			
            //highlight dccs
            for (const [key, value] of Object.entries(this.parsedData)) {
                const el = document.querySelector(`[data-value="${key}"]`);
                if(value[group][val]===1){
                    //el.classList.add('on');
                    if (group==='povs'){
						console.log(group, val, this.currPov)
                        //if(this.freezeSelection){
                            el.classList.add('onA');
                            const l = new LeaderLine(
                                document.querySelector(`[data-value="${key}"]`),
                                e.target,
                                {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', startPlugColor: '#34679a', endPlug: 'behind', endSocketGravity: 100, 
                                path: 'fluid', gradient: {startColor: '#ff7f5090', endColor:'#ff7f5090'}, dash: {len: 2, gap: 1, animation: true},  size: 1}
                            );
						//}
                    }else{
                        el.classList.add('on');
                    }
                    //el.classList.add('on');
                    //el.dispatchEvent(new Event('mouseover'));
                }
                if(value[group][val]===2){
                    //el.classList.add('on2');
                    if (group==='povs'){
                        //if(!this.freezeSelection){
                            el.classList.add('on2A');
                            const l = new LeaderLine(
                                document.querySelector(`[data-value="${key}"]`),
                                e.target,
                                {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', startPlugColor: '#34679a', endPlug: 'behind', endSocketGravity: 80, 
                                path: 'fluid', gradient: {startColor: '#ff7f5090', endColor:'#ff7f5090'}, dash: {len: 4, gap: 2, animation: true},  size: 2}
                            );
                        //}
                    }else{
                        el.classList.add('on2');
                    }
                }
                if(value[group][val]===3){
                    //el.classList.add('on3');
                    if (group==='povs'){
                        //if(!this.freezeSelection){
                            el.classList.add('on3A');
                            const l = new LeaderLine(
                                document.querySelector(`[data-value="${key}"]`),
                                e.target,
                                {startSocket: 'top', endSocket: 'bottom', startPlug: 'behind', startPlugColor: '#34679a', endPlug: 'behind', endSocketGravity: 60, 
                                path: 'fluid', gradient: {startColor: '#ff7f5090', endColor:'#ff7f5090'}, dash: {len: 6, gap: 3, animation: true},  size: 3}
                            );
                        //}
                    }else{
                        el.classList.add('on3');
                    }
                }
            }
        },
		povMoveHandler(e){
			const el = document.querySelector('.map-pov-message');
			el.style.top = (e.clientY-90)+'px';
			el.style.left = (e.clientX+10)+'px';
		},
		povHandler(e){
            const group = e.target.dataset.group;
            const val = e.target.dataset.value;
            if(!e.target.classList.contains('selected')){
				document.querySelectorAll('[data-group="povs"]').forEach(el => {el.classList.remove('selected')});
                e.target.classList.add('selected');
                document.querySelector('.line2').classList.add('open');
                document.querySelector('.dccs').classList.add('active');
				document.querySelectorAll('.search-context-label').forEach(el => el.innerHTML = val);
				console.log('CONTEXT', this.utilsBox.userUtils.getContext(), val);
				const userContext = this.utilsBox.userUtils.getContext() ? this.utilsBox.userUtils.getContext().replace('_', '-') : null;
				if(!userContext || (userContext !== val)){
					document.querySelector('.search-context.set').style.display = 'none';
					document.querySelector('.search-context.notset').style.display = 'block';
				}else{
					document.querySelector('.search-context.set').style.display = 'block';
					document.querySelector('.search-context.notset').style.display = 'none';
				}
				
				if(val==='computational-biology'){
					document.querySelector('.section-search-drc').style.display = 'flex';
					document.querySelector('.section-search-kc').style.display = 'none';
				}else{
					document.querySelector('.section-search-drc').style.display = 'none';
					document.querySelector('.section-search-kc').style.display = 'flex';
				}
                this.currPov = val;
                this.freezeSelection = true;
				
            }else{
				e.target.classList.remove('selected');
                document.querySelector('.line2').classList.remove('open');
                document.querySelector('.dccs').classList.remove('active');
				document.querySelectorAll('.search-context-label').forEach(el => el.innerHTML = 'none');
				if(val==='computational-biology'){
					document.querySelector('.section-search-drc').style.display = 'none';
					document.querySelector('.section-search-kc').style.display = 'flex';
				}
                this.currPov = null;
                this.freezeSelection = false;
				this.utilsBox.userUtils.clearContext();
				this.utilsBox.keyParams.set({ "context": '' });
            }
        },

		setContext(e){
			if(this.currPov && this.currPov!=='computational-biology'){
				const valUnderscored = this.currPov.toLowerCase().replace("-", "_")
				this.utilsBox.userUtils.saveContext(valUnderscored);
				this.utilsBox.keyParams.set({ "context": valUnderscored });
				document.querySelector('.search-context.set').style.display = 'block';
				document.querySelector('.search-context.notset').style.display = 'none';
			}
		},


		async loadCSV(url) {
			await fetch(url)
			.then(response => {
				if (!response.ok) {
					throw new Error('Network response was not ok');
				}
				console.log(response.text());
			})
			.catch(error => {
				console.error('Error loading CSV:', error);
			});
		},

		minVidEnd(e){
			e.target.dataset.loopCount++;
			if(e.target.dataset.loopCount < e.target.dataset.loopMax){
				e.target.play();
			}else{
				e.target.classList.add('paused');
			}
		},
		minVidHover(e){
			if(e.target.classList.contains('paused')){
				e.target.play();
			}
		},
		minVidHoverOut(e){
			if(e.target.classList.contains('paused')){
				e.target.pause();
			}
		},

		showInfoContent(e){
			const infoEl = document.querySelector(`.${e.target.dataset.infoEl}`);
			infoEl.style.top = (e.clientY-90)+'px';
			infoEl.style.left = (e.clientX+10)+'px';
			infoEl.style.display = 'block';
		},
		hideInfoContent(e){
			const infoEl = document.querySelector(`.${e.target.dataset.infoEl}`);
			infoEl.style.top = (e.clientY-90)+'px';
			infoEl.style.left = (e.clientX+10)+'px';
			infoEl.style.display = 'none';
		}
	}
});

$(function () {
});
</script>
<style>
.mdkp-body.flex-body.front-page {
    overflow-x: visible;
	flex: none;
}
.mdkp-body.flex-body:has(.kc-wrap){
	padding-top: 0;
}
.fp-search-section {
    margin: 50px 0 20px;
}
.multi-section.wrapper-section-0:has(.col-md-12.wrapper-section-0:empty){
	display: none;
}
#byor_single_search {
    border: 2px solid #ff6600;
    padding: 20px;
}
.col-md-12:has(.kc-wrap) {
    padding: 0;
}
.kc-hero {
    background: #f7f6f6;
}
.blurb {
    display: flex;
    align-items: center;
	justify-content: space-between;
	padding: 30px 0px 40px;
    gap: 20px;
}
.blurb div {
	font-size: 16px;
    color: #7c7c7c;
	font-weight: bold;
}
.blurb span {
	color: inherit;
	font-weight: normal;
}
.blurb span.highlight{
	color: #f26822;
	font-weight: bold;
}
.blurb .logo {
    width: 70px;
    flex: unset;
}
.blurb .logo img {
    width: -webkit-fill-available;
    object-fit: contain;
}
.map-bg{
	 /*background: #f7f6f6;*/
	 display: flex;
    flex-direction: column;
    align-items: center;
	/*box-shadow: inset 0px 10px 10px -10px #00000010, inset 0px -10px 10px -10px #00000010;*/
}
.map-title {
    margin: 20px 0 0 0;
    font-size: 12px;
	margin: 0 auto;
    position: absolute;
    left: 0;
    padding: 0 20px;
    width: 250px;
    margin-top: 83px;
    display: flex;
    flex-direction: column;
    
	color: #7c7c7c;
	z-index: 10;
}
.map-title.boxed{
	background: white;
    padding: 20px;
    border-radius: 0 10px 10px 0;
	margin-top: 0;
}
.map-title>span{
	color: #ff6600;
	text-transform: uppercase;
	font-weight: bold;
    letter-spacing: 1px;
	display: contents;
}
.map-title2 {
    color: #7c7c7c;
    width: 100%;
    margin: 0 0 10px 0;
	text-align: center;
}
.map-title2>span {
    text-transform: uppercase;
    font-size: 14px;
    font-weight: bold;
    letter-spacing: 1px;
    color: #ff6600;
	display: flex;
    align-items: center;
    justify-content: center;
    gap: 5px;
}
.map-bg .map-title2>span {
    font-size: 16px;
}
.how {
    font-size: 11px;
    text-transform: none;
    color: black;
    letter-spacing: normal;
    font-weight: normal;
    display: flex;
    gap: 5px;
    align-items: center;
    cursor: pointer;
	margin: 5px 0 0;
	width: fit-content;
}
.btn-icon {
    display: flex !important;
    border: 1px solid black !important;
    font-weight: 600;
    height: 12px;
    width: 12px;
    border-radius: 50%;
    line-height: 20px;
    align-items: center;
    justify-content: center;
    font-size: 9px;
	color: black !important;
	cursor: pointer;
}
.map-pov-message{
	font-size: 12px;
    background: #ff6600;
	color:white;
    padding: 3px 10px;
    border-radius: 5px;
    position: absolute;
	z-index: 10;
	box-shadow: 1px 1px 2px 0 #00000050;
	display: none;
}
.map {
	display: flex;
	flex-direction: column;
	gap: 0px;
	width: 830px;
	margin: 0 auto;
	padding: 0px 0 0px 0;
}
.povs,
.dccs,
.omics,
.entities{
	display: flex;
	justify-content: center;
	gap: 10px;
	position: relative;
}
.povs{
	gap: 30px;
	justify-content: space-between;
}
.pov {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: space-between;
	gap: 0px;

	/*width: 170px;
	width: 50px;
	aspect-ratio: 1;*/

	background: none;
	cursor: pointer;
	
	text-align: center;   
	filter: brightness(0);
}
.pov:hover {
	background: none !important;
}
.pov.selected {
	filter: none;
	/*border-bottom: solid 3px #ff6600;*/
}
.pov span {
	background: none;
	padding: 3px 0 1px 0;
	flex: 1 1 auto;
	color: black;
	display: flex;
	align-items: center;
	justify-content: center;
	pointer-events: none;
	text-transform: uppercase;
	font-size: 11px;
	font-weight: bold;
	letter-spacing: 1px;
}
.pov span{
	border-bottom: 1px solid transparent;
}
.pov:hover span,
.pov.selected span {
	background: none;
	color: #ff6600;
}
.pov img {
	width: -webkit-fill-available;
	height: auto;
	aspect-ratio: 1;
	object-fit: contain;
	pointer-events: none;
	padding: 5px;
}
.povs .img {
    width: 50px;
    height: 50px;
	pointer-events: none;
	border-radius: 5px;
}

.dccs{
	margin: 0 0 15px -25% !important;
    width: 150% !important;
	gap: 0;
    align-items: center;
	/*margin: 0 0 15px 0;
    width: 100%;*/
}
.dcc {
	display: flex;
	flex: 1 1 auto;
	align-items: center;
	justify-content: center; 

	width: 50px;
	aspect-ratio: 1;

	background: none;
	border-top: 3px solid transparent;
	cursor: default;
	   
	transition: .2s all ease-out;
}
.dcc:hover {
	background: none !important;
	border-top: solid 3px #ff6600;
}
.dcc img {
	width: -webkit-fill-available;
	height: auto;
	object-fit: contain;
	margin: 0 10px;
	pointer-events: none;
	mix-blend-mode: darken;
}
.dcc-separator {
    background: #ccc;
    width: 0.5px;
    height: 50px;
    margin: 0 5px;
}
.dcc-separator:last-child {
    display: none;
}
.dcc.onA, .dcc.on2A, .dcc.on3A{
	border-top: solid 1px transparent;
	padding-top: 2px;
}
.dcc.on{
	border-top:3px solid #ff6600 !important;
	/*background: #f0f0f0;
	outline: 5px solid white;
	outline-offset: -5px;*/
}
.dcc.on2{
	/*background: #f0f0f0;
	outline: 2.5px solid #e6e6e6;*/
}
.dcc.on3{
	/*background: #f0f0f0;
	outline: 10px solid #e6e6e6;*/
}
.dccs.active .dcc:hover{
	border-top:3px solid #ff6600;
}

.omics {
	display: flex;
	gap: 0;
	align-items: center;
	justify-content: center; 

	margin: 0 0 20px 0;

	background: none;
	cursor: default;

	gap: 5px;
}
.omic{
	display: flex;
	flex: 1 1 auto;
	align-items: center;
	justify-content: center;

	aspect-ratio: unset;
	height: 20px;
	
	text-transform: uppercase;
	font-size: 11px;
	padding: 0 5px;
	letter-spacing: 1px;
	font-weight: 600;

	background: #ddd;
	filter: grayscale(1);

	cursor: default;
	transition: .2s all linear;
}
.omic:hover{
	background: #ff802c !important;
	filter: none;
	color: white;
}
.omics.active .omic{
	min-width: 100px;
	/*flex: 0 0 auto;*/
	overflow: hidden;
}
.omic span,
.entity span{
	pointer-events: none;
}
.omics.active .omic.on{
	/*flex: 1 1 auto;*/
	background: #ff802c;
	filter: none;
	color: white;
}

.entities{
	gap: 0px;
}
.entity {
	display: flex;
	flex: 1 1 auto;
	align-items: center;
	justify-content: center; 
	
	width: auto;
	height: 20px;

	background: none;   
	/*border-bottom: 3px solid transparent;*/
	cursor: default;

	text-transform: uppercase;
	font-size: 11px;
	font-weight: bold;
	letter-spacing: .5px;
}
.entity:hover,
.entity.on{
	/*background:#ff6600;*/
	color:#ff6600;
	/*border-bottom: 3px solid #ff6600;*/
}

.line2 {
	font-size: 14px;
	height: 100px;
	display: flex;
	align-items: center;
	justify-content: center;
	width: 150%;
    padding: 0 300px;
    text-align: center;
    margin: 0 0 0 -25%;
	text-align: center;
	transition: .2s all ease-out;
	z-index: 2;
	position: relative;
	background:transparent;
}
.line2.open:has(.line2info:not(:empty)){
	background:#f7f6f695;
	backdrop-filter: blur(2px);
}
.hidden{
	display:none;
}

.map-label {
	position: absolute;
    right: 50%;
    transform: translateX(50%);
    line-height: 12px;
    width: 100vw;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    text-align: right;
    font-size: 11px;
    height: 100%;
    padding: 0 10px 0 0;
    border-right: 5px solid #dddddd;
    color: #8f8f8f;
	pointer-events: none;
}
.map-label>div {
    width: 70px;
}

.line2 .map-label{
	height: calc(100% - 20px);
	flex-direction: column;
    align-items: end;
    justify-content: center;
}
.relevance-legend {
    display: flex;
    flex-direction: column;
	gap: 0px;
	margin: 5px 0 0 0;
}
.relevance-legend>div {
    padding: 0 20px 0 0;
	position: relative;
}
.relevance-legend>div:after {
	position: absolute;
    content: '';
    width: 15px;
    height: 0;
    right: 0;
    top: 50%;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
    
}
.relevance-hi:after{
	border-top: 3px dashed #ff6600;
}
.relevance-md:after{
	border-top: 2px dashed #ff6600;
}
.relevance-lo:after{
	border-top: 1px dashed #ff6600;
}


.kc-wrap {
    width: 830px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap: 20px;
}
.kc-title {
    font-size: 22px;
    margin: 10px 0 20px;
    text-transform: uppercase;
}
.a {
    width: 100%;
    display: flex;
    gap: 20px;
    justify-content: space-between;
	/*background: linear-gradient(0deg, transparent, #f7f6f6);*/
}
.b {
    max-width: 50%;
    background: #f6f6f6;
    min-height: 500px;
    display: flex;
    align-items: flex-start;
    justify-content: flex-start;
    flex: 1 1 auto;
	flex-direction: column;
    padding: 40px 0 40px 40px;
}
.quick .b {
    min-height: 0;
	align-items:center;
    justify-content: flex-start;
	flex: 1 1 auto;
    width: 40%;
	background: #f7f6f6;
    border-radius: 20px 0 0 50px;
    border-radius: 20px;
	padding: 30px 0px 30px 30px;
}
.c-title {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 0 0 10px 0;
}
.b p {
    font-size: 22px;
	margin:0;
}
.b a {
    color: black !important;
	background: white;
    text-decoration: none;
    align-self: flex-end;
    border: 1px solid #ccc;
    padding: 3px 10px;
    border-radius: 5px;
	margin: 10px 0 0 0;
}
.b ul {
    padding: 0;
    list-style-type: none;
}
.b li {
    margin: 0 0 10px 0;
}
.b li p{
	font-size: 16px;
	margin: 0;
}

.blurbA {
    width: 100%;
    align-self: center;
    margin: 0;
}
.b:nth-child(1) {
    /*border-radius: 0 20px 50px 0;
	padding: 40px 40px 40px 0;*/
	padding: 30px 30px 30px 0;
}
.b:nth-child(1) li {
    text-align: right;
}

.c{
    display: flex;
    align-items: center;
    padding: 0 1px;
	background: white;
}
.c-body {
    margin: 0 0 10px 0;
}

.bold{
	font-weight: bold;
	color:#ff6600;
}

.section {
    min-height: 200px;
    width: 100%;
    margin: 0 auto;
	padding: 30px calc((100% - 830px) / 2);
	display: flex;
    flex-direction: column;
}
.section-title {
    font-size: 20px;
    letter-spacing: .2px;
    display: flex;
    align-items: center;
    flex-direction: row;
    gap: 10px;
}
.section-subtitle {
    text-transform: uppercase;
    font-size: 14px;
	margin: 5px 0 10px;
}
.section-wrap {
    display: flex;
    flex-direction: row;
}
.section-col {
    display: flex;
    flex-direction: column;
    flex: 1 1 auto;
    padding: 10px;
}
.section .placeholder {
    background: #f7f6f6;
    width: 365px;
    height: 215px;
	display: flex;
	align-items: center;
	justify-content: center;
	text-transform: uppercase;
    font-size: 14px;
	cursor: default;
	color: #ccc;
	border: solid 1px #ddd;
}
.partnerships{
	display:flex;
	flex-direction: row;
	gap: 20px;
}
.partner {
    height: 70px;
    padding: 5px;
    padding: 5px;
    display: flex;
    align-items: center;
}
.partner img {
    height: 100%;
    width: auto;
    object-fit: contain;
}

.section:has(.byor-single-search-wrapper) {
    min-height: auto;
	padding-bottom: 60px;
}
.byor-single-search-wrapper h3 {
    display: none;
}

.section.cdfe-centers {
    min-height: auto;
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    font-weight: bold;
	display:none;
}

.section-search-drc{
	display:none;
}

.search-try {
    font-size: 14px;
    display: flex;
    gap: 10px;
    color: #7c7c7c;
    padding: 3px 5px 0;
    justify-content: center;
}
.search-try span {
    cursor: pointer;
}
.search-try span:first-child {
	color: #7c7c7c;
    cursor: default;
}
.search-try a {
    color: #ff6600 !important;
}

.search-extras {
    display: flex;
    align-items: center;
    justify-content: center;
    color: #7c7c7c;
    padding: 10px 20px;
}
.search-context.notset{
	display:none;
}
.search-context-label{
	color:#ff6600;
}
.search-context button {
    border: 0.5px solid #ddd;
    background: #ff6600;
	color:white;
    border-radius: 5px;
    padding: 0px 5px;
    margin: 0 0 0 10px;
}

.search-extras {
    display: flex;
    align-items: center;
    justify-content: center;
    color: #7c7c7c;
    padding: 10px 20px;
}
.search-context-label{
	color:#ff6600;
}
.search-context button {
    border: 0.5px solid #ddd;
    background: #ff6600;
	color:white;
    border-radius: 5px;
    padding: 2px 10px;
    margin: 0 0 0 10px;
}

.hideable{
	opacity:0;
	transition: 0.2s all linear;
}
.map-bg:hover .hideable,
.section:hover .hideable{
	opacity: 1;
}

.mini-card-video {
    width: -webkit-fill-available;
    background: white;
}
.mini-card-video video {
    width: -webkit-fill-available;
    display: block;
}

.drc-logo {
    height: 50px;
    aspect-ratio: 1;
    padding: 5px;
    background: white;
    border-radius: 50%;
    box-shadow: 0px 1px 3px 1px rgba(15, 31, 46, 0.15);
	display: flex;
    align-items: center;
    justify-content: center;
}
.drc-logo img {
    width: 100%;
    height: 100%;
    object-fit: contain;
}

.section.section-search-drc {
    text-align: center;
}
.section-search-drc a,
#kc-section-c a {
    border: 0.5px solid #ddd;
    background: #ff6600;
    color: white;
    border-radius: 5px;
    padding: 3px 10px;
    margin: 0 0 0 10px;
    width: fit-content;
    align-self: center;
	color: white !important;
    text-transform: none;
}
.section-search-drc .section-title {
    justify-content: center;
	color: #336699;
    font-size: 30px;
}
.section-search-drc ul {
    list-style: none;
}

.overlay-window {
    position: absolute;
    background: white;
    padding: 20px;
    border-radius: 10px;
    z-index: 100;
    font-size: 12px;
	width:300px;
	box-shadow: 0 0 5px 0 #00000050;
}
.context-info{
	display:none;
}
.overlay-window-close {
    position: absolute;
    right: 10px;
    top: 12px;
    width: 10px;
    height: 10px;
    line-height: 10px;
    cursor: pointer;
}

#kc-section-d .logo {
    width: 100px;
}
#kc-section-d .logo img {
    width: 100%;
    height: 100%;
    object-fit: contain;
}
</style> 

