<template>
    <div class="kc-home flex-layout-styles">
        <div class="logo">
            <img src="https://hugeampkpncms.org/sites/default/files/users/user32/cfde_kc_logo_c.svg">
        </div>
        <div class="search-wrapper f-col align-h-center">
            <h1 class="kc">Explore Common Fund Knowledge</h1>
            <div class="f-col fill-width">
                <research-single-search-cfde :single-search-config="sectionConfigs['content']" :phenotypes="phenotypesInUse"
                    :utils="utilsBox"></research-single-search-cfde>
                <div class="search-extras f-row">
                    <div class="f-row" style="gap:5px">
                        Try <a href="/research.html?entity=gene&gene=BDH2&pageid=kc_entity&tissue=blood">BDH2</a>
                        <a
                            href="/research.html?disease=MONDO%3A0004985&entity=disease&pageid=kc_entity&tissue=blood">Bipolar
                            disorder</a>
                    </div>
                </div>
            </div>
            <div class="map-info">
                <div class="f-col">
                    <div class="map-info-title"></div>
                    <div class="map-info-subtitle"></div>
                </div>
            </div>
        </div>
        <div class="hero-wrapper f-col" v-if="this.parsedData">
            <div class="hero-q" style="right:40px" @click="this.toggleCFinfo">What is the Common Fund?</div>
            <div class="cf-intro f-col align-h-center">
                <h2 class="kc">{{ Object.keys(this.parsedData.map).length }} Common Fund Programs</h2>
                <div>Conducting ground-breaking research generating multi-omics data across diverse fields.</div>
            </div>
            <div class="cf-info" style="display:none">
                <h2 class="kc">The Common Fund</h2>
                <div><b>The Common Fund (CF)</b> is a program within the National Institutes of Health (NIH) designed to
                    support innovative, high-impact research that transcends the mission of any single NIH institute or
                    center.</div>
            </div>
            <div class="cfp-info f-col fill-width">
                <div class="dcc-info" style="display:none">
                    <h3 class="kc">Common Fund Programs and Data Coordinating Centers</h3>
                    <div><b>CF Programs</b> are large-scale, trans-NIH research initiatives designed to address
                        significant biomedical challenges that no single NIH institute or center can tackle alone.</div>
                    <div><b>Data Coordinating Centers (DCCs)</b> are focused on the management, integration, and
                        dissemination of data generated by CF Programs.</div>
                </div>
                <div class="dcc-icons-contain">
                    <div class="dcc-icons f-row">
                        <template v-for="(value, key, index) in this.parsedData.map">
                            <div class="dcc-icon" 
                                data-group="dccs" 
                                :data-value="key" 
                                @mouseover="hoverHandler($event)"
                                @mouseout="outHandler($event)">
                                <img :src="value['logo']">
                            </div>
                        </template>
                    </div>
                </div>
            </div>
            <!--<div class="paths"></div>-->
            <div class="cfde-info f-col fill-width align-h-center">
                <div class="arrw">➤</div>
                <div class="hero-q" @click="this.toggleCFDEinfo">What is the CDFE?</div>
                <div class="cfde-title f-col align-h-center">
                    <h2 class="kc">1 Data Ecosystem</h2>
                    <div>Allowing researchers to easily find, access, and integrate Common Fund datasets.</div>
                </div>
                <div class="what-cfde-info" style="display:none">
                    <h3 class="kc">Common Fund Data Ecosystem</h3>
                    <div><b>The Common Fund Data Ecosystem (CFDE)</b> is an initiative under the NIH Common Fund that
                        aims to
                        enhance the accessibility, interoperability, and usability of data generated by Common Fund
                        programs.</div>
                </div>
                <!--
                <div class="cfde-stats f-row fill-width spread-out">
                    <div class="f-col align-h-center">
                        <div>50k+</div>
                        <div>subjects</div>
                    </div>
                    <div class="f-col align-h-center">
                        <div>350+</div>
                        <div>tissues</div>
                    </div>
                    <div class="f-col align-h-center">
                        <div>1.5m+</div>
                        <div>biosamples</div>
                    </div>
                    <div class="f-col align-h-center">
                        <div>100+</div>
                        <div>assays</div>
                    </div>
                    <div class="f-col align-h-center">
                        <div>2k+</div>
                        <div>diseases</div>
                    </div>
                </div>
                -->
                <div class="f-col" style="gap:10px;width: 100%;">
                    <div class="eco-row f-col">
                        <div class="eco-title">Resources</div>
                        <div class="resources f-row fill-width spread-out" style="gap:5px">
                            <div v-for="(value, key) in this.parsedData.sets['resources']"
                                class="resource" 
                                data-group="resources" 
                                :data-value="value"
                                @mouseover="hoverHandler2($event)" 
                                @mouseout="outHandler($event)">
                                <!--<span>{{ key.replace('-', ' ') }}</span>-->
                                <span>{{ value }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="eco-row f-col">
                        <div class="eco-title">Omics</div>
                        <div class="omics f-row fill-width spread-out" style="gap:5px">
                            <div v-for="(value, key) in this.parsedData.sets['omics']"
                                class="omic" 
                                data-group="omics" 
                                :data-value="value" 
                                @mouseover="hoverHandler2($event)"
                                @mouseout="outHandler($event)">
                                <span>{{ value }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="eco-row f-col">
                        <div class="eco-title">Entities</div>
                        <div class="entities f-row fill-width spread-out" style="gap:5px">
                            <div v-for="(value, key) in this.parsedData.sets['entities']"
                                class="entity" 
                                data-group="entities" 
                                :data-value="value"
                                @mouseover="hoverHandler2($event)" 
                                @mouseout="outHandler($event)">
                                <span>{{ value }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="fold f-col align-h-center">
            <h1>What you can do with the CFDE</h1>
            <div class="fold-arrow">
                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#7c7c7c"
                    stroke-width="1.2">
                    <path
                        d="M5.707 9.71a1 1 0 0 0 0 1.415l4.892 4.887a2 2 0 0 0 2.828 0l4.89-4.89a1 1 0 1 0-1.414-1.415l-4.185 4.186a1 1 0 0 1-1.415 0L7.121 9.71a1 1 0 0 0-1.414 0Z"
                        fill="#7c7c7c" />
                </svg>
            </div>
        </div>



        <div class="home-section-wrap" style="display:none">
            <h3 class="kc">Access Canonical Data Resources</h3>
            <div class="home-section f-col">
                <div>
                    <div>
                        <h2>Molecular Signatures</h2>
                        <div>Explore comprehensive gene expression signatures, protein markers, and methylation
                            profiles—essential tools for biomarker discovery and pathway analysis.</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
                <div>
                    <div>
                        <h2>Biomedical Aggregators</h2>
                        <div>Lorem Ipsum - need copy here to explain biomedical aggregators</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
                <div>
                    <div>
                        <h2>Reference Maps</h2>
                        <div>Dive into single-cell reference maps, offering fine-resolution insights into cellular
                            diversity and
                            tissue-specific functions.</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="home-section-wrap">
            <h3 class="kc">Data Integration for Advanced Discovery</h3>
            <div class="home-section f-row">
                <div>
                    <div>
                        <h2>Gene Set Analysis</h2>
                        <div>Uncover gene set patterns across integrated Common Fund programs—designed for advanced
                            cross-dataset exploration.</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
                <div>
                    <div>
                        <h2>Differential Expression Analysis</h2>
                        <div>Compare differentially expressed genes across tissues and diseases, driving insights into
                            gene
                            regulation and disease mechanisms.</div>
                    </div>
                    <div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="home-section-wrap">
            <h3 class="kc">KC Examples of CFDE Knowledge</h3>
            <div class="home-section">
                <div class="examples-tabs f-row">
                    <div class="examples-tab active" data-tab="gene" @click="this.handleExampleTab"><h3>Gene</h3></div>
                    <div class="examples-tab" data-tab="disease" @click="this.handleExampleTab"><h3>Disease</h3></div>
                    <div class="examples-tab" data-tab="protein" @click="this.handleExampleTab"><h3>Protein</h3></div>
                </div>
                
                <div class="examples-list active f-col" data-tabgroup="gene">
                    <div class="example-item f-row">
                        <div class="example-dcc">GTEx</div>
                        <div class="example-info">Specific expression of gene by tissue</div>
                    </div>
                    <div class="example-item f-row">
                        <div class="example-dcc">4DN</div>
                        <div class="example-info">Common disease association signals nearby the promoter of a gene</div>
                    </div>
                    <div class="example-item f-row">
                        <div class="example-dcc">LINCS</div>
                        <div class="example-info">Transcriptional signatures, resulting from either CRISPR gene knockdown or chemical perturbation, that are correlated with the transcriptional signature of a gene derived from coexpression correlation.</div>
                    </div>
                    <div class="example-item f-row">
                        <div class="example-dcc">IDG</div>
                        <div class="example-info">Summarizes the amount of evidence supporting a gene as a potential drug target.</div>
                    </div>
                    <div class="example-item f-row">
                        <div class="example-dcc">exRNA</div>
                        <div class="example-info">RNA binding proteins predicted to interact with extracellular RNAs originating from a gene.</div>
                    </div>
                </div>
                <div class="examples-list f-col" data-tabgroup="disease">
                    <div class="example-item f-row">
                        <div class="example-dcc">GTEx</div>
                        <div class="example-info">Tissues most-relevant to a disease based on enrichment of genetic associations near genes specific to the tissue</div>
                    </div>
                    <div class="example-item f-row">
                        <div class="example-dcc">4DN</div>
                        <div class="example-info">Common disease association signals nearby the promoter of a disease.</div>
                    </div>
                    <div class="example-item f-row">
                        <div class="example-dcc">IDG</div>
                        <div class="example-info">Potential drug targets for a disease.</div>
                    </div>
                    <div class="example-item f-row">
                        <div class="example-dcc">Metabolomics Workbench</div>
                        <div class="example-info">Metabolites associated with a disease.</div>
                    </div>
                </div>
                <div class="examples-list f-col" data-tabgroup="protein">
                    <div class="example-item f-row">
                        <div class="example-dcc">IDG</div>
                        <div class="example-info">Drug target level classifications.</div>
                    </div>
                    <div class="example-item f-row">
                        <div class="example-dcc">exRNA</div>
                        <div class="example-info">Genes that produce extracellular RNAs and whose intracellular RNAs are detected bound to a protein</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="home-section-wrap" v-if="this.parsedData">
            <h3 class="kc">Common Fund Program Spotlight</h3>
            <div class="home-section">
                <template v-for="(value, key) in this.parsedData.map">
                    <div class="spotlight-item">
                        <div class="spotlight-logo f-row align-v-center">
                            <img :src="value.logo">
                        </div>
                        <div class="f-col fill-width">
                            <div class="f-col fill-height">
                                <h3>{{ value.name }}</h3>
                                <div v-html="value.description"></div>
                            </div>
                            <a style="align-self: flex-end;" :href="`/research.html?DCC=${key}&pageid=kc_dccs`">Learn More</a>
                        </div>
                    </div>
                </template>
                <div class="spotlight-prev" data-dir="prev" @click="this.changeSpotlight">
                    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#7c7c7c"
                    stroke-width="1.2">
                    <path
                        d="M5.707 9.71a1 1 0 0 0 0 1.415l4.892 4.887a2 2 0 0 0 2.828 0l4.89-4.89a1 1 0 1 0-1.414-1.415l-4.185 4.186a1 1 0 0 1-1.415 0L7.121 9.71a1 1 0 0 0-1.414 0Z"
                        fill="#7c7c7c" />
                </svg>
                </div>
                <div class="spotlight-next" data-dir="next" @click="this.changeSpotlight">
                    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#7c7c7c"
                    stroke-width="1.2">
                    <path
                        d="M5.707 9.71a1 1 0 0 0 0 1.415l4.892 4.887a2 2 0 0 0 2.828 0l4.89-4.89a1 1 0 1 0-1.414-1.415l-4.185 4.186a1 1 0 0 1-1.415 0L7.121 9.71a1 1 0 0 0-1.414 0Z"
                        fill="#7c7c7c" />
                </svg>
                </div>
            </div>
        </div>
        <div class="f-tooltip top" style="top: 0; left: 50px; width: 200px; height:100px;"></div>
        <div class="f-tooltip right" style="top: 0; left: 300px; width: 200px; height:100px;"></div>
        <div class="f-tooltip bottom" style="top: 0; left: 550px; width: 200px; height:100px;"></div>
        <div class="f-tooltip left" style="top: 0; left: 800px; width: 200px; height:100px;"></div>
    </div>
    
</template>

<script>
import Vue from "vue";
import { BootstrapVueIcons } from "bootstrap-vue";

Vue.use(BootstrapVueIcons);

export default Vue.component("cfde-landing", {
    props: ["sectionConfigs", "phenotypesInUse", "utilsBox", "keyParams"],
    data() {
        return {
            parsedData: null,
            currPov: null,
            currHoverGroup: null,
            freezeSelection: false,
            cfInfoToggle: false,
            cfdeInfoToggle: false,
            lines: [],
            spotlightInterval: null,
            currSpotlight: -1,
        };
    },
    mounted() {
        window.addEventListener('resize', this.handleResize);
        this.init();
    },
    beforeDestroy() {
        window.removeEventListener('resize', this.handleResize);
    },
    computed: {},
    watch: {
    },
    updated() {
    },
    methods: {
        async init() {
            const data = await this.loadFile(this.sectionConfigs["content"]["custom"]["viz data"])
            //this.parsedData = await this.parseEntities(data);
            //console.log('parsedData', this.parsedData);
            this.parsedData = this.parseData(JSON.parse(data));
            
            setTimeout(() => {
                const edges = this.getNodePoints();
                this.renderEdges(edges);
                this.changeSpotlight(null);
                this.spotlightInterval = setInterval(() => {
                    this.changeSpotlight(null)
                }, 10000);
                setTimeout(() => {
                    this.simulateMouseOverSequence();
                }, 400);
            }, 100);
            
        },
        async loadFile(src) {
            //must use dataset endpoint to load csv file from hugeampkpncms (otherwise CORS error)
            const fetchUrl = "https://hugeampkpncms.org/servedata/dataset?dataset=" + src;
            //however, dataset enpoint parses the original csv and escapes special characters
            let data = await fetch(fetchUrl).then(resp => {
                return resp.json();
                //return resp.text(fetchUrl)
            });

            return data;

            //we must undo all of that to get the original data
            data = data.replace(/\\u0022/g, '"'); 		//quotes
            data = data.replace(/\\\//g, '/');			//slashes
            data = data.replace(/\\n/g, '\n');			//line breaks
            data = data.replace(/\\r/g, '\r');			//carriage returns
            data = data.substring(1, data.length - 1);	//remove surrounding quotes
            return data;
        },
        parseData(data){
            const map = {};
            const sets = {
                programs: new Set(),
                resources: new Set(),
                omics: new Set(),
                entities: new Set()
            };

            data.forEach(dccItem => {
                const dcc = dccItem.DCC;

                // Add to Map object
                map[dcc] = {
                    logo: dccItem["Logo"] || "",
                    name: dccItem["Name"] || "",
                    description: dccItem["Foundational Knowledge"] || "",
                    resources: dccItem["Resources"] || [],
                    omics: dccItem["Omics"] || [],
                    entities: dccItem["Data Entities"] || []
                };

                // Add to Sets object (using Set to ensure uniqueness)
                sets.programs.add(dcc);
                (dccItem["Resources"] || []).forEach(resource => sets.resources.add(resource));
                (dccItem["Omics"] || []).forEach(omic => sets.omics.add(omic));
                (dccItem["Data Entities"] || []).forEach(entity => sets.entities.add(entity));
            });

            // Convert Sets to arrays for the final result
            const setsAsArrays = {
                programs: Array.from(sets.programs),
                resources: Array.from(sets.resources),
                omics: Array.from(sets.omics),
                entities: Array.from(sets.entities)
            };

            console.log({ map, sets: setsAsArrays });

            return { map, sets: setsAsArrays };

            //return { map, sets: setsAsArrays };
        },
        async parseEntities(data) {
            const lines = data.split('\n');
            const headers = lines[0].split(',');
            const result = {};

            for (let i = 1; i < lines.length; i++) {
                const values = lines[i].match(/(".*?"|[^",\r\n]+|(?<=,)(?=,))/g);//.split(',');
                const dcc = values[0];
                result[dcc] = { entities: {}, omics: {}, resources: {}, povs: {}, logo: '', info: {} };

                for (let j = 1; j < headers.length; j++) {
                    const [prefix, key] = headers[j].split('_');
                    if (prefix && key) {
                        let group;
                        if (prefix === 'a') {
                            group = 'entities';
                        } else if (prefix === 'b') {
                            group = 'omics';
                        } else if (prefix === 'c') {
                            group = 'povs';
                        } else if (prefix === 'd') {
                            group = 'logo';
                            result[dcc][group] = values[j];
                            continue;
                        } else if (prefix === 'e') {
                            group = 'resources';
                        } else if (prefix === 'r') {
                            group = 'info';
                            result[dcc][group][key.trim()] = values[j];
                            continue;
                        }
                        result[dcc][group][key.trim()] = values[j] ? parseInt(values[j]) : null;
                    }
                }
            }

            return result;
            //this.parsedData = result;
            //console.log(this.parsedData);
        },
        drawEdge(from, to, thickness, value) {
            let nodeConnectOffset = 20;

            //start and end point offsets
            let startX = from.x;
            let endX = to.x;
            let startY = from.y;
            let endY = to.y;

            let curveDirX = startX < endX ? -1 : 1;
            let curveDirY = startY < endY ? -1 : 1;
            const curveSize = startX === endX ? 0 : nodeConnectOffset;

            //if the endX point is more left than startX point
            //swap them
            if (to.x < from.x) {
                startX = to.x;
                endX = from.x;
                curveDirX = endX < startX ? -1 : 1;
            }

            startX -= thickness;
            endX += thickness;

            // Create an SVG element
            const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
            const svgWidth = Math.abs(startX - endX);
            const svgHeight = Math.abs(startY - endY);
            svg.style.position = 'absolute';
            svg.style.left = startX + 'px';
            svg.style.top = startY + 'px';
            svg.style.width = svgWidth + 'px';
            svg.style.height = svgHeight + 'px';
            svg.setAttribute('viewBox', `0 0 ${svgWidth} ${svgHeight}`);
            svg.classList.add('line-svg');
            document.body.append(svg);

            //create the path element
            const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
            let sX = thickness;
            let eX = endX - startX - thickness;
            let sY = 0;
            let eY = endY - startY;
            let midY = ((eY - sY) / 2);

            if (to.x < from.x) {
                sX = endX - startX - thickness;
                eX = thickness;
            }

            // Draw path
            let d = `M ${sX} ${sY}`;
            d += ` V ${midY - curveSize}`;
            d += ` Q ${sX} ${midY}, ${sX - curveSize * curveDirX} ${midY}`;
            d += ` H ${eX + curveSize * curveDirX}`;
            d += ` Q ${eX} ${midY}, ${eX} ${midY - curveSize * curveDirY}`;
            d += ` V ${eY}`;

            // Set path attributes
            path.setAttribute("data-value", value);
            path.setAttribute("d", d);
            path.setAttribute("stroke", "#f26822");
            path.setAttribute("fill", "transparent");
            path.setAttribute("stroke-width", thickness);

            svg.appendChild(path);

            this.lines.push(path);
        },
        renderEdges(edges) {
            document.querySelectorAll('.line-svg').forEach(el => {
                el.remove();
            })
            edges.forEach(edge => {
                this.drawEdge(edge.from_point, edge.to_point, 1, edge.value);
            });
            document.querySelector('.arrw').style.display = 'block';
        },
        getNodePoints() {
            const from_nodes = document.querySelectorAll('.dcc-icon');
            const to_node = document.querySelector('.cfde-info');

            function getBottomCenter(element) {
                const rect = element.getBoundingClientRect();
                return {
                    x: rect.left + (rect.width / 2),
                    y: rect.bottom + window.scrollY
                };
            };

            function getTopCenter(element) {
                const rect = element.getBoundingClientRect();
                return {
                    x: rect.left + (rect.width / 2),
                    y: rect.top + window.scrollY
                };
            };

            const to_point = getTopCenter(to_node);

            const edges = Array.from(from_nodes).map(from_node => ({
                value: from_node.dataset.value,
                from_point: getBottomCenter(from_node),
                to_point: to_point
            }));

            return edges;
        },
        handleResize() {
            const edges = this.getNodePoints();
            this.renderEdges(edges);
        },
        toggleCFinfo(e) {
            if (!this.cfInfoToggle) {
                e.target.innerHTML = 'close ✖';
                document.querySelector('.cf-intro').style.display = 'none';
                //document.querySelector('.cfp-info').classList.add('active');
                document.querySelector('.cf-info').style.display = 'block';
                document.querySelector('.dcc-info').style.display = 'block';
                this.cfInfoToggle = true;
            } else {
                e.target.innerHTML = 'What is the Common Fund?';
                document.querySelector('.cf-intro').style.display = 'flex';
                //document.querySelector('.cfp-info').classList.remove('active');
                document.querySelector('.cf-info').style.display = 'none';
                document.querySelector('.dcc-info').style.display = 'none';
                this.cfInfoToggle = false;
            }
            this.handleResize();
        },
        toggleCFDEinfo(e) {
            if (!this.cfdeInfoToggle) {
                e.target.innerHTML = 'close ✖';
                document.querySelector('.cfde-title').style.display = 'none';
                document.querySelector('.what-cfde-info').style.display = 'block';
                this.cfdeInfoToggle = true;
            } else {
                e.target.innerHTML = 'What is the CFDE?';
                document.querySelector('.cfde-title').style.display = 'flex';
                document.querySelector('.what-cfde-info').style.display = 'none';
                this.cfdeInfoToggle = false;
            }
            this.handleResize();
        },
        outHandler(e) {
            if (this.freezeSelection) {
                document.querySelectorAll(`[data-group]`).forEach(item => item.classList.remove('on', 'on2', 'on3'));
                const targetElement = document.querySelector(`[data-value="${this.currPov}"]`);
                if (targetElement) targetElement.dispatchEvent(new Event('mouseover'));
            } else {
                document.querySelectorAll(`[data-group]`).forEach(item => item.classList.remove('on', 'on2', 'on3', 'onA', 'on2A', 'on3A'));
                this.lines.forEach(line => {
                    line.setAttribute("stroke", "#f26822");
                    line.parentNode.style.zIndex = 0;
                })
                document.querySelector('.map-info').style.opacity = 0;
            }
            this.currHoverGroup = null;
            
        },
        hoverHandler(e) {

            const val = e.target.dataset.value;

            this.lines.forEach(line => {
                if (line.dataset.value !== val) {
                    line.setAttribute("stroke", "#ddd");
                } else {
                    line.parentNode.style.zIndex = 1;
                }
            })

            /*
            //highlight resources
            if (this.currHoverGroup !== 'resources') {
                for (const [key, value] of Object.entries(this.parsedData[val]['resources'])) {
                    if (value) {
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }

            //highlight entities
            if (this.currHoverGroup !== 'entities') {
                for (const [key, value] of Object.entries(this.parsedData[val]['entities'])) {
                    if (value) {
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }

            //highlight omics
            if (this.currHoverGroup !== 'omics') {
                for (const [key, value] of Object.entries(this.parsedData[val]['omics'])) {
                    if (value) {
                        document.querySelector(`[data-value="${key}"]`).classList.add('on');
                    }
                }
            }*/
            //highlight resources
            if (this.currHoverGroup !== 'resources') {
                this.parsedData.map[val]['resources'].forEach(value => {
                    if (value) { document.querySelector(`[data-value="${value}"]`).classList.add('on');}
                });
            }
            if (this.currHoverGroup !== 'omics') {
                this.parsedData.map[val]['omics'].forEach(value => {
                    if (value) { document.querySelector(`[data-value="${value}"]`).classList.add('on');}
                });
            }
            if (this.currHoverGroup !== 'entities') {
                this.parsedData.map[val]['entities'].forEach(value => {
                    if (value) { document.querySelector(`[data-value="${value}"]`).classList.add('on');}
                });
            }
            
            if(e.isTrusted){
                document.querySelector('.map-info').style.opacity = 1;
                this.mapTooltip('Program', val);
            }
        },
        hoverHandler2(e) {
            clearTimeout(this.mapInfoTimeout);

            const group = e.target.dataset.group;
            let val = e.target.dataset.value;
            this.currHoverGroup = group;

            //un-hilight lines from DCCs
            this.lines.forEach(line => {
                line.setAttribute("stroke", "#ddd");
            })

            //highlight dccs
            /*for (const [key, value] of Object.entries(this.parsedData)) {
                const el = document.querySelector(`[data-value="${key}"]`);
                if (value[group][val] === 1) {
                    //highlight DCC
                    el.classList.add('on');
                    //hilighlight lines from DCC
                    const line = this.lines.find(element => element.dataset.value === key);
                    line.setAttribute("stroke", "#f26822");
                    line.parentNode.style.zIndex = 1;
                }
                //ununsed
                if (value[group][val] === 2) {
                    el.classList.add('on2');
                }
                if (value[group][val] === 3) {
                    el.classList.add('on3');
                }
            }*/


            for (const [key, value] of Object.entries(this.parsedData.map)) {
                const el = document.querySelector(`[data-value="${key}"]`);
                if (value[group].includes(val)) {
                    //highlight DCC icon
                    el.classList.add('on');
                    //hilighlight lines from DCC
                    const line = this.lines.find(element => element.dataset.value === key);
                    line.setAttribute("stroke", "#f26822");
                    line.parentNode.style.zIndex = 1;
                }
                //ununsed
                if (value[group][val] === 2) {
                    el.classList.add('on2');
                }
                if (value[group][val] === 3) {
                    el.classList.add('on3');
                }
            }

            if(e.isTrusted){
                document.querySelector('.map-info').style.opacity = 1;
                this.mapTooltip(group, val);
            }
        },
        mapTooltip(group, value){
            document.querySelector('.map-info-title').innerHTML = group;
            document.querySelector('.map-info-subtitle').innerHTML = value;
        },
        triggerMouseEvent(element, eventType) {
            const event = new MouseEvent(eventType, {
                bubbles: true,
                cancelable: true,
                view: window
            });
            element.dispatchEvent(event);
            //eventType === 'mouseover' ? element.classList.add('on') : element.classList.remove('on');
        },
        simulateMouseOverSequence() {
            const delay = 150;
            const elements = document.querySelectorAll('.dcc-icon');

            let lastEl = null;

            elements.forEach((element, index) => {
                setTimeout(() => {
                    if (lastEl) {
                        this.triggerMouseEvent(element, 'mouseout');
                        element.classList.remove('on')
                    }
                    this.triggerMouseEvent(element, 'mouseover');
                    element.classList.add('on')
                    lastEl = element;
                    if (index === elements.length - 1) {
                        setTimeout(() => {
                            this.triggerMouseEvent(element, 'mouseout');
                            element.classList.remove('on')
                        }, delay);
                    }

                }, index * delay);
            });
        },
        changeSpotlight(e){
            const randInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
            let currSpotlight = this.currSpotlight;
            const max = Object.keys(this.parsedData.map).length;
            let dir = 'next';
            if(e?.target){
                clearInterval(this.spotlightInterval);
                dir = e.target.dataset.dir
            }
            if(currSpotlight>0){
                document.querySelector(`.spotlight-item:nth-of-type(${this.currSpotlight})`).classList.remove('active')
            }else{
                currSpotlight = randInt(1, max);
            }
            if(dir==='next'){
                currSpotlight = currSpotlight>=max ? 1 : currSpotlight+1;
            }else{
                currSpotlight = currSpotlight<=1 ? max : currSpotlight-1;
            }
            this.currSpotlight = currSpotlight;
            document.querySelector(`.spotlight-item:nth-child(${this.currSpotlight})`).classList.add('active');
        },
        handleExampleTab(e){
            const group = e.target.dataset.tab;
            document.querySelectorAll('.examples-tab').forEach(el=>{
                el.classList.remove('active')
            })
            e.target.classList.add('active');
            document.querySelectorAll('.examples-list').forEach(el=>{
                el.classList.remove('active')
            })
            console.log('tab', group, document.querySelector(`.examples-list[data-tabgroup="${group}"]`));
            document.querySelector(`.examples-list[data-tabgroup="${group}"]`).classList.add('active');
        }
    }
});
</script>
<style scoped>
.line-svg {
    pointer-events: none;
}
.f-tooltip{
    position: absolute;
    background: white;
    border-radius: 10px;
    padding:10px;
    z-index:100;
    box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;
    display:none;
}
.f-tooltip.top::after {
    content: '';
    width: 0;
    height: 0;
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-bottom: 10px solid white;
    position: absolute;
    left: 50%;
    top: -10px;
    transform: translateX(-50%);
}
.f-tooltip.right::after {
    content: '';
    width: 0;
    height: 0;
    border-top: 5px solid transparent;
    border-bottom: 5px solid transparent;
    border-left: 10px solid white;
    position: absolute;
    right: -10px;
    top: 50%;
    transform: translateY(-50%);
}
.f-tooltip.bottom::after {
    content: '';
    width: 0;
    height: 0;
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-top: 10px solid white;
    position: absolute;
    left: 50%;
    bottom: -10px;
    transform: translateX(-50%);
}
.f-tooltip.left::after {
    content: '';
    width: 0;
    height: 0;
    border-top: 5px solid transparent;
    border-bottom: 5px solid transparent;
    border-right: 10px solid white;
    position: absolute;
    left: -10px;
    top: 50%;
    transform: translateY(-50%);
}

.flex-layout-styles {

    /* LAYOUT STYLES */
    .no-events {
        pointer-events: none;
    }

    .f-col {
        display: flex;
        flex-direction: column;
    }

    .f-row {
        display: flex;
        flex-direction: row;
    }

    .f-col.align-v-center {
        justify-content: center;
    }

    .f-row.align-v-center {
        align-items: center;
    }

    .f-col.align-h-center {
        align-items: center;
    }

    .f-row.align-h-center {
        justify-content: center;
    }

    .f-col.align-v-bottom {
        justify-content: flex-end;
    }

    .f-row.align-v-bottom {
        align-items: flex-end;
    }

    .f-col.align-h-bottom {
        align-items: flex-end;
    }

    .f-row.align-h-bottom {
        justify-content: flex-end;
    }

    .f-col.spread-out,
    .f-row.spread-out {
        justify-content: space-between;
    }

    .fill-height {
        /*height: -moz-available;
        height: -webkit-fill-avaiilable;*/
        height: stretch;
        height: 100%;
    }

    .fill-width {
        /*width: -moz-available;
        width: -webkit-fill-avaiilable;*/
        width: stretch;
        width: 100%;
    }

    .hug-height {
        height: fit-content;
    }

    .hug-width {
        width: fit-content
    }

    .grow-children>* {
        flex-grow: 1;
    }
}

.kc-home {
    display: flex;
    flex-direction: column;
    align-items: center;
    background: #f7f6f6;
    margin: -30px;
    padding: 15px;
    color: #7c7c7c;

    .map-info {
        opacity:0;
        position: absolute;
        bottom: 0;
        background: white;
        width: 100%;
        height: 100%;
        border-radius: 10px;
        box-shadow: rgba(0, 0, 0, 0.1) 0px 10px 15px -3px, rgba(0, 0, 0, 0.05) 0px 4px 6px -2px;
        transition: 0.2s all;
        pointer-events: none;
        padding:20px;
    }
    .map-info-title {
        font-size: 12px;
        text-transform: capitalize;
        line-height: 10px;
    }
    .map-info-subtitle {
        font-size: 16px;
        text-transform: uppercase;
        font-weight: bold;
        color:#f26822;
    }

    h1 {
        font-size: 22px;
        font-weight: bold;
        line-height: 22px;
    }

    h2 {
        font-size: 18px;
        font-weight: bold;
        line-height: 18px;
    }

    h3 {
        font-size: 16px;
        font-weight: bold;
        line-height: 16px;
    }

    h1.kc,
    h2.kc,
    h3.kc {
        text-transform: uppercase;
        color: #f26822;
    }

    h1.kc {
        font-size: 20px;
    }

    h2.kc {
        font-size: 18px;
    }

    h3.kc {
        font-size: 16px;
    }

    .logo img {
        width: 70px;
    }

    .search-wrapper {
        width: 800px;
        margin: 10px 0 30px 0;
        gap: 10px;
        position: relative;
    }

    #byor_single_search {
        border-radius: 10px;
        padding: 25px;
        font-size: 16px;
    }

    .search-extras {
        gap: 5px;
        background: #e6e6e6;
        padding: 5px 25px;
        margin: 0 25px;
        border-radius: 0 0 10px 10px;
    }

    .search-extras a,
    .search-extras a:visited {
        color: #f26822 !important;
    }

    .hero-wrapper {
        width: 1200px;
        background: #f8f6f6;
        padding: 20px;
        gap: 20px;
        position: relative;
        border-radius: 10px;
        align-items: center;
    }

    .cf-info {
        padding: 0px 0px 0px 0px;
    }

    .cfp-info {
        width: fit-content;
        padding: 0px 20px 20px 20px;
        gap: 30px;
    }

    .cfp-info.active {
        padding-top: 20px;
        background: #ebebeb;
    }

    .cfde-info {
        margin-top: 30px;
        padding: 20px 20px 20px 20px;
        gap: 20px;
        /*background: #ebebeb;*/
        position: relative;
        border-radius: 10px;
    }

    .dcc-icons-contain {
        position: relative;
        height: 70px;
    }

    .dcc-icons {
        gap: 10px;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .dcc-icon {
        width: 75px;
        aspect-ratio: 1;
        background: #ebebeb;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 10px;
        transition: .15s all linear;
    }

    .dcc-icon img {
        width: 75%;
        pointer-events: none;
        mix-blend-mode: darken;
    }

    .dcc-icon.on,
    .dcc-icon:hover {
        /*outline: 2px solid #ff6600;*/
        background: #ff660050;
        transform: scale(1.1);
        /*border-bottom:3px solid #ff6600;*/
    }

    .eco-row {
        position: relative;
    }

    .eco-title {
        font-size: 12px;
        font-weight: bold;
        position: absolute;
        left: calc(100% + 50px);
        top: 50%;
        transform: translateY(-50%);
    }

    .resources,
    .omics,
    .entities {
        flex-wrap:wrap;
    }

    .resource,
    .omic,
    .entity {
        display: flex;
        flex: 1 1 auto;
        align-items: center;
        justify-content: center;
        aspect-ratio: unset;
        height: 20px;
        text-transform: uppercase;
        font-size: 11px;
        padding: 0 5px;
        letter-spacing: 1px;
        font-weight: 600;
        background: #ddd;
        filter: grayscale(1);
        cursor: default;
        transition: .15s all linear;
        white-space: nowrap;
    }

    .resource.on,
    .resource:hover,
    .omic.on,
    .omic:hover,
    .entity.on,
    .entity:hover {
        background: #ff802c;
        filter: none;
        color: white;
    }

    .resource span,
    .omic span,
    .entity span {
        pointer-events: none;
    }

    .paths {
        height: 50px;
    }

    .cfde-stats {
        gap: 5px;
    }

    .hero-q {
        align-self: flex-end;
        font-size: 12px;
        /*color: #f26822;*/
        font-weight: bold;
        position: absolute;
        top: 20px;
        right: 20px;
        cursor: pointer;
        user-select: none;
        background: white;
        padding: 0 10px;
        border-radius: 10px;
    }

    .fold {
        margin: 30px 0;
    }

    .fold-arrow {
        line-height: 0;
        margin: -10px 0 0;
    }

    .fold-arrow svg {
        height: 30px;
    }

    .home-section-wrap {
        width: 800px;
        margin: 0 0 40px;
    }

    .home-section {
        background: #eee;
        padding: 20px;
        gap: 10px;
        position:relative;
    }

    .arrw {
        position: absolute;
        top: -10px;
        transform: rotate(90deg);
        display: none;
        font-size: 12px;
        align-self: center;
        color: #f26822;
    }

    .examples-tabs{
        gap:10px;
        padding:0 0 10px 0;
    }
    .examples-tab {
        cursor: pointer;
    }
    .examples-tab.active {
        border-bottom: 3px solid #f26822;
    }
    .examples-tab h3 {
        margin: 0 0 2px 0;
        pointer-events: none;
    }
    .examples-list{
        gap:10px;
        display:none;
    }
    .examples-list.active{
        display:flex;
    }
    .example-item{
        gap:10px;
    }
    .example-dcc{
        min-width: 100px;
        width: 100px;
    }
    .example-info{

    }

    .spotlight-item {
        display: none;
        gap:20px;
    }
    .spotlight-item.active{
        display:flex;
    }
    .spotlight-item a,
    .spotlight-item a:visited{
        color:#f26822 !important;
    }
    .spotlight-logo {
        aspect-ratio: 1;
    }
    .spotlight-logo img {
        width: 150px;
        mix-blend-mode: darken;
    }

    .spotlight-prev,
    .spotlight-next {
        position: absolute;
        top: 100px;
        width: 30px;
        height: 30px;
        cursor:pointer;
    }
    .spotlight-prev svg,
    .spotlight-next svg{
        pointer-events: none;
    }
    .spotlight-prev {
        left: -30px;
        transform: translateY(-50%) rotate(90deg);
    }
    .spotlight-next {
        right: -30px;
        transform: translateY(-50%) rotate(-90deg);
    }
}
</style>
