<template>
	<div class="genes-validator">
		<!-- Header -->
		<div class="validator-header">
			<h3>Gene Validator</h3>
			<p class="validator-description">Validate genes against your hypothesis by getting their relevance and novelty contexts.</p>
		</div>

		<!-- Hypothesis Section -->
		<div class="hypothesis-section">
			<label for="hypothesis">Your Hypothesis</label>
			<textarea 
				id="hypothesis"
				v-model="hypothesis" 
				placeholder="Enter your hypothesis to validate genes against..."
				class="hypothesis-textarea"
				rows="3"
			></textarea>
		</div>

		<!-- Manual Gene Input Section -->
		<div class="manual-gene-section">
			<label for="manual-genes">Add Genes to Validate</label>
			<small class="format-suggestion">Enter gene symbols separated by commas (e.g., GENE1, GENE2, GENE3)</small>
			<textarea 
				id="manual-genes"
				v-model="manualGenes" 
				placeholder="e.g., TP53, BRCA1, MYC, EGFR"
				class="manual-genes-field"
				rows="2"
			></textarea>
			<div class="manual-gene-actions">
				<button 
					@click="addManualGenes" 
					class="btn btn-primary add-genes-btn"
					:disabled="!manualGenes.trim() || !hypothesis.trim()"
				>
					Add Genes
				</button>
				<button 
					@click="clearAllGenes" 
					class="btn btn-outline-secondary clear-btn"
					:disabled="geneData.length === 0"
				>
					Clear All
				</button>
			</div>
		</div>

		<!-- Gene Data Table -->
		<div v-if="geneData.length > 0" class="gene-data-table-section">
			<div class="gene-data-header">
				<label class="gene-data-label">Gene Validation Results</label>
				<small class="gene-data-description">
					Review the novelty and relevance scores for each gene. These scores are generated by AI and represent how novel/relevant each gene is to your specific hypothesis.
				</small>
			</div>
			
			<div class="table-container">
				<div v-if="isGettingGeneNovelty" class="summary-loading-indicator">
					<span class="loading-spinner-small"></span>
					<span class="loading-text">Generating gene novelty and relevance scores... ({{ geneNoveltyElapsedTime }})</span>
				</div>
				
				<table class="gene-data-table">
					<thead>
						<tr>
							<th>Gene</th>
							<th>Relevance</th>
							<th>Novelty</th>
							<th style="width: 70%;">Reason</th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="item in paginatedGenes" :key="item.gene">
							<td>{{ item.gene }}</td>
							<td>
								<div class="relevance-cell">
									<span v-if="isGettingGeneNovelty && !getRelevance(item.gene)" class="loading-text">Loading...</span>
									<div v-else-if="getRelevance(item.gene)" class="score-content" :class="{ 'high-score': getRelevance(item.gene).score >= 7 }">
										<div class="score-value">{{ getRelevanceScore(item.gene) }}</div>
									</div>
									<span v-else>TBD</span>
								</div>
							</td>
							<td>
								<div class="novelty-cell">
									<span v-if="isGettingGeneNovelty && !getNovelty(item.gene)" class="loading-text">Loading...</span>
									<div v-else-if="getNovelty(item.gene)" class="score-content" :class="{ 'high-score': getNovelty(item.gene).score >= 7 }">
										<div class="score-value">{{ getNoveltyScore(item.gene) }}</div>
									</div>
									<span v-else>TBD</span>
								</div>
							</td>
							<td>
								<div class="reason-cell">
									<span v-if="isGettingGeneNovelty && !getNovelty(item.gene)" class="loading-text">Loading...</span>
									<div v-else-if="getNovelty(item.gene)" class="reason-content">
										{{ getNovelty(item.gene).context }}
									</div>
									<span v-else>TBD</span>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
				
				<!-- Pagination -->
				<div v-if="totalPages > 1" class="pagination-container">
					<div class="pagination-info">
						Showing {{ (currentPage - 1) * itemsPerPage + 1 }} to {{ Math.min(currentPage * itemsPerPage, geneData.length) }} of {{ geneData.length }} entries
					</div>
					<div class="pagination-controls">
						<button 
							@click="goToFirstPage" 
							:disabled="currentPage === 1"
							class="pagination-btn first-last-btn"
							title="First page"
						>
							««
						</button>
						<button 
							@click="previousPage" 
							:disabled="currentPage === 1"
							class="pagination-btn"
						>
							Previous
						</button>
						<span class="page-numbers">
							<button 
								v-for="page in visiblePages" 
								:key="page"
								@click="goToPage(page)"
								:class="['page-btn', { 'active': page === currentPage }]"
							>
								{{ page }}
							</button>
						</span>
						<button 
							@click="nextPage" 
							:disabled="currentPage === totalPages"
							class="pagination-btn"
						>
							Next
						</button>
						<button 
							@click="goToLastPage" 
							:disabled="currentPage === totalPages"
							class="pagination-btn first-last-btn"
							title="Last page"
						>
							»»
						</button>
					</div>
				</div>
			</div>
			
			<!-- What's Next Information Box -->
			<div v-if="geneData.length > 0" class="whats-next-box">
				<div class="whats-next-content">
					<span class="whats-next-text">Explore gene expression patterns across human tissues using GTEx data (max 50 genes)</span>
					<a :href="gtexUrl" target="_blank" class="whats-next-link">
						Open
					</a>
				</div>
			</div>
		</div>

		<!-- Empty State -->
		<div v-else class="empty-state">
			<p>No genes added yet. Enter your hypothesis and add genes to get started.</p>
		</div>
	</div>
</template>

<script>
import { createLLMClient } from '@/utils/llmClient';

export default {
	name: 'CFDEGenesValidator',
	data() {
		return {
			// Hypothesis
			hypothesis: '',
			
			// Manual gene input
			manualGenes: '',
			
			// Gene data
			geneData: [],
			
			// Pagination properties
			currentPage: 1,
			itemsPerPage: 10,
			
			// Gene novelty and relevance cache
			geneNovelty: {},
			geneRelevance: {},
			
			// Gene novelty request state
			isGettingGeneNovelty: false,
			geneNoveltyTimeout: null,
			geneNoveltyStartTime: null,
			geneNoveltyTimer: null,
			geneNoveltyElapsedTime: '0:00',
			
			// LLM client
			getGeneNovelty: null,
			
			// Gene novelty prompt
			gene_novelty_prompt: `Generate a JSON array for up to 10 genes based on the hypothesis below.

**Hypothesis:** [INSERT YOUR HYPOTHESIS HERE]
**Genes:** [INSERT YOUR COMMA-SEPARATED GENE LIST HERE (MAX 10)]

**Task & JSON Model:** Respond **ONLY** with a valid JSON array. For each gene, provide numeric scores for novelty and relevance, and a single 'reason' field (max 25 words) that justifies both scores.

**Workflow:** Prioritize speed. Determine all scores/reasoning concurrently across the gene list.
***Reasoning Requirement: The 'reason' field must clearly link the gene's function to the hypothesis (relevance) AND contextualize the novelty score by classifying the gene's role (e.g., Core Functional Enzyme vs. Upstream Regulator vs. Accessory Factor), justifying its research standing.***
***If information is unavailable for a gene, set both scores to "N/A" and explain why in 'reason' (≤25 words).***

Novelty Score (1=Highly Studied, 10=Poorly Studied).
Relevance Score (1=Low Relevance to Hypothesis, 10=Highly Relevant).

[
  {
    "gene": "<symbol>",
    "relevance_score": "<1-10 or N/A>",
    "novelty_score": "<1-10 or N/A>",
    "reason": "<max 25 words: justification for both scores>"
  },
  ...
]`
		};
	},
	created() {
		this.getGeneNovelty = createLLMClient({
			llm: "openai",
			model: "gpt-5-mini",
			system_prompt: this.gene_novelty_prompt
		});
	},
	mounted() {
		this.initializeFromUrlParams();
		// Check if there are genes that need scores after initialization
		this.$nextTick(() => {
			this.checkAndFetchScoresForCurrentPage();
		});
	},
	beforeDestroy() {
		// Clean up timer when component is destroyed
		this.clearGeneNoveltyTimer();
		// Clean up gene novelty timeout
		if (this.geneNoveltyTimeout) {
			clearTimeout(this.geneNoveltyTimeout);
		}
	},
	computed: {
		gtexUrl() {
			if (this.geneData.length === 0) return '';
			
			// Extract gene symbols from the gene data (limit to first 50 genes)
			const geneSymbols = this.geneData.slice(0, 50).map(gene => gene.gene).join(',');
			
			// Create GTEx multi-gene query URL
			return `https://www.gtexportal.org/home/multiGeneQueryPage/${geneSymbols}`;
		},
		totalPages() {
			return Math.ceil(this.geneData.length / this.itemsPerPage);
		},
		paginatedGenes() {
			const start = (this.currentPage - 1) * this.itemsPerPage;
			const end = start + this.itemsPerPage;
			return this.geneData.slice(start, end);
		},
		visiblePages() {
			const pages = [];
			const total = this.totalPages;
			const current = this.currentPage;
			
			// Show up to 5 page numbers
			let start = Math.max(1, current - 2);
			let end = Math.min(total, start + 4);
			
			// Adjust start if we're near the end
			if (end - start < 4) {
				start = Math.max(1, end - 4);
			}
			
			for (let i = start; i <= end; i++) {
				pages.push(i);
			}
			
			return pages;
		}
	},
	methods: {
		async addManualGenes() {
			// Check if there are genes in the manual-genes field
			if (!this.manualGenes.trim()) {
				alert('Please enter gene symbols in the manual genes field.');
				return;
			}
			
			// Check if hypothesis is provided
			if (!this.hypothesis.trim()) {
				alert('Please enter a hypothesis to validate genes against.');
				return;
			}
			
			// Parse the manual genes input
			const geneList = this.manualGenes.split(',').map(gene => gene.trim()).filter(gene => gene);
			
			if (geneList.length === 0) {
				alert('Please enter valid gene symbols separated by commas.');
				return;
			}
			
			// Check for duplicate genes
			const existingGenes = this.geneData.map(g => g.gene);
			const duplicateGenes = geneList.filter(gene => existingGenes.includes(gene));
			if (duplicateGenes.length > 0) {
				alert(`The following genes are already in the table: ${duplicateGenes.join(', ')}. Please remove duplicates and try again.`);
				return;
			}
			
			// Create gene data entries for manual genes
			const manualGeneData = geneList.map(gene => ({
				gene: gene,
				source: 'Manual Input',
				isManual: true // Flag to identify manual genes
			}));
			
			// Add to existing gene data
			this.geneData = [...this.geneData, ...manualGeneData];
			
			// Reset pagination to first page
			this.currentPage = 1;
			
			// Get novelty scores for manually added genes
			await this.getNoveltyForManualGenes(geneList);
			
			// Clear manual input
			this.manualGenes = '';
			
			console.log(`Added ${geneList.length} manual genes: ${geneList.join(', ')}`);
			
			// Check if current page has genes that need scores
			this.$nextTick(() => {
				this.checkAndFetchScoresForCurrentPage();
			});
		},
		
		async getNoveltyForManualGenes(geneList) {
			try {
				// Limit to 10 genes as per prompt constraints
				const genesToProcess = geneList.slice(0, 10);
				
				if (genesToProcess.length === 0) {
					return;
				}
				
				// Prepare the prompt
				const prompt = this.gene_novelty_prompt
					.replace('[INSERT YOUR HYPOTHESIS HERE]', this.hypothesis.trim())
					.replace('[INSERT YOUR COMMA-SEPARATED GENE LIST HERE (MAX 10)]', genesToProcess.join(', '));
				
				// Set loading state
				this.isGettingGeneNovelty = true;
				this.geneNoveltyStartTime = Date.now();
				this.geneNoveltyElapsedTime = '0:00';
				
				// Start timer to update elapsed time every second
				this.geneNoveltyTimer = setInterval(() => {
					if (this.isGettingGeneNovelty && this.geneNoveltyStartTime) {
						const elapsed = Math.floor((Date.now() - this.geneNoveltyStartTime) / 1000);
						const minutes = Math.floor(elapsed / 60);
						const seconds = elapsed % 60;
						this.geneNoveltyElapsedTime = `${minutes}:${seconds.toString().padStart(2, '0')}`;
					}
				}, 1000);
				
				// Call the LLM
				this.getGeneNovelty.sendPrompt({
					userPrompt: prompt,
					onResponse: (response) => {
						try {
							// Parse the JSON response
							const noveltyData = JSON.parse(response);
							
							// Update the geneNovelty and geneRelevance cache
							noveltyData.forEach(item => {
								if (item.gene) {
									// Handle novelty score
									if (item.novelty_score !== undefined) {
										this.$set(this.geneNovelty, item.gene, {
											score: item.novelty_score,
											context: item.reason || 'No context provided'
										});
									}
									
									// Handle relevance score
									if (item.relevance_score !== undefined) {
										this.$set(this.geneRelevance, item.gene, {
											score: item.relevance_score,
											context: item.reason || 'No context provided'
										});
									}
								}
							});
							
							console.log(`Novelty scores updated for ${noveltyData.length} manual genes`);
							
						} catch (error) {
							console.error('Error parsing manual gene novelty response:', error);
						} finally {
							this.isGettingGeneNovelty = false;
							this.clearGeneNoveltyTimer();
						}
					},
					onError: (error) => {
						console.error('Error getting novelty for manual genes:', error);
						this.isGettingGeneNovelty = false;
						this.clearGeneNoveltyTimer();
					},
					onEnd: () => {
						this.isGettingGeneNovelty = false;
						this.clearGeneNoveltyTimer();
					}
				});
			} catch (error) {
				console.error('Error preparing manual gene novelty request:', error);
				this.isGettingGeneNovelty = false;
				this.clearGeneNoveltyTimer();
			}
		},
		
		clearAllGenes() {
			this.geneData = [];
			this.geneNovelty = {};
			this.geneRelevance = {};
			this.manualGenes = '';
			this.currentPage = 1;
		},
		
		getNovelty(geneSymbol) {
			if (!geneSymbol) return null;
			return this.geneNovelty[geneSymbol] || null;
		},
		
		getRelevance(geneSymbol) {
			if (!geneSymbol) return null;
			return this.geneRelevance[geneSymbol] || null;
		},
		
		getNoveltyScore(geneSymbol) {
			const novelty = this.getNovelty(geneSymbol);
			return novelty ? `${novelty.score}/10` : 'N/A';
		},
		
		getRelevanceScore(geneSymbol) {
			const relevance = this.getRelevance(geneSymbol);
			return relevance ? `${relevance.score}/10` : 'N/A';
		},
		
		clearGeneNoveltyTimer() {
			if (this.geneNoveltyTimer) {
				clearInterval(this.geneNoveltyTimer);
				this.geneNoveltyTimer = null;
			}
		},
		
		// Pagination methods
		previousPage() {
			if (this.currentPage > 1) {
				this.currentPage--;
				this.checkAndFetchScoresForCurrentPage();
			}
		},
		nextPage() {
			if (this.currentPage < this.totalPages) {
				this.currentPage++;
				this.checkAndFetchScoresForCurrentPage();
			}
		},
		goToPage(page) {
			if (page >= 1 && page <= this.totalPages) {
				this.currentPage = page;
				this.checkAndFetchScoresForCurrentPage();
			}
		},
		goToFirstPage() {
			this.currentPage = 1;
			this.checkAndFetchScoresForCurrentPage();
		},
		goToLastPage() {
			this.currentPage = this.totalPages;
			this.checkAndFetchScoresForCurrentPage();
		},
		
		checkAndFetchScoresForCurrentPage() {
			// Get genes on current page that don't have novelty scores yet
			const genesWithoutScores = this.paginatedGenes.filter(gene => 
				!this.getNovelty(gene.gene) && !this.getRelevance(gene.gene)
			);
			
			if (genesWithoutScores.length > 0) {
				const geneList = genesWithoutScores.map(gene => gene.gene);
				console.log(`Fetching scores for ${geneList.length} genes on page ${this.currentPage}: ${geneList.join(', ')}`);
				this.getNoveltyForManualGenes(geneList);
			}
		},
		
		initializeFromUrlParams() {
			try {
				const urlParams = new URLSearchParams(window.location.search);
				
				// Get hypothesis from URL parameters
				const hypothesisParam = urlParams.get('hypothesis');
				if (hypothesisParam) {
					this.hypothesis = decodeURIComponent(hypothesisParam);
				}
				
				// Get genes from URL parameters
				const genesParam = urlParams.get('genes');
				if (genesParam) {
					const geneList = decodeURIComponent(genesParam).split(',').map(gene => gene.trim()).filter(gene => gene);
					
					if (geneList.length > 0) {
						// Add genes to the table
						const manualGeneData = geneList.map(gene => ({
							gene: gene,
							source: 'URL Parameters',
							isManual: true
						}));
						
						this.geneData = [...this.geneData, ...manualGeneData];
						
						// Get novelty scores for the genes
						this.getNoveltyForManualGenes(geneList);
						
						console.log(`Initialized with ${geneList.length} genes from URL parameters: ${geneList.join(', ')}`);
						
						// Check if current page has genes that need scores
						this.$nextTick(() => {
							this.checkAndFetchScoresForCurrentPage();
						});
					}
				}
			} catch (error) {
				console.error('Error initializing from URL parameters:', error);
			}
		}
	}
};
</script>

<style scoped>
/* Main Background - CFDE Knowledge Center Style */
body {
    background-color: #F8F8F8;
}

a {
    color: #FF6600 !important;
}

.genes-validator {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Section Wrappers - CFDE Card Style */
.validator-header, .hypothesis-section, .manual-gene-section, .gene-data-table-section {
    background: #ffffff;
    padding: 20px;
}

.validator-header h3 {
    color: #FF6600;
    font-size: 24px;
    font-weight: 700;
    margin: 0 0 10px 0;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}

.validator-description {
    color: #666;
    font-size: 16px;
    margin: 0;
}

.hypothesis-section label {
    display: block;
    margin-top: 0 !important;
    margin-bottom: 15px !important;
    color: #333333;
    font-size: 14px;
    font-weight: 600;
}

.hypothesis-textarea {
    width: 100%;
    padding: 8px 12px;
    border: 1px solid #d1d5db;
    border-radius: 6px;
    font-size: 14px;
    font-family: inherit;
    resize: vertical;
    min-height: 60px;
    background-color: white;
}

.hypothesis-textarea:focus {
    outline: none;
    border-color: #86b7fe;
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
}

.manual-gene-section {
    margin-bottom: 30px;
    padding: 20px;
}

.manual-gene-section label {
    display: block;
    margin-top: 0 !important;
    margin-bottom: 15px !important;
    color: #333333;
    font-size: 14px;
    font-weight: 600;
}

.format-suggestion {
    display: block;
    color: #777777;
    font-size: 12px;
    font-style: italic;
    margin: 4px 0 8px 0;
    padding: 4px 8px;
    background-color: #F8F8F8;
    border-left: 3px solid #7c757d;
}

.manual-genes-field {
    width: 100%;
    padding: 8px 12px;
    border: 1px solid #ced4da;
    border-radius: 4px;
    font-size: 14px;
    margin-bottom: 15px;
    resize: vertical;
    min-height: 60px;
}

.manual-genes-field:focus {
    outline: none;
    border-color: #007bff;
    box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
}

.manual-gene-actions {
    display: flex;
    gap: 10px;
    justify-content: flex-start;
}

/* Button Styles - CFDE Style */
.btn {
    padding: 8px 16px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 14px;
    margin-top: 10px;
}

.btn-primary {
    background-color: #007bff;
    color: white;
}

.btn-primary:disabled {
    background-color: #6c757d;
    cursor: not-allowed;
}

.btn-primary:hover:not(:disabled) {
    background-color: #0056b3;
}

.btn-outline-secondary {
    background-color: transparent;
    color: #6c757d;
    border: 1px solid #6c757d;
}

.btn-outline-secondary:hover:not(:disabled) {
    background-color: #6c757d;
    color: white;
}

.btn-outline-secondary:disabled {
    background-color: #f9fafb;
    color: #d1d5db;
    cursor: not-allowed;
}

.add-genes-btn {
    min-width: 100px;
}

.clear-btn {
    min-width: 100px;
}

.gene-data-table-section {
    margin-top: 30px;
}

.gene-data-header {
    margin-bottom: 20px;
}

.gene-data-label {
    display: block;
    margin-top: 0 !important;
    margin-bottom: 15px !important;
    color: #333333;
    font-size: 14px;
    font-weight: 600;
}

.gene-data-description {
    display: block;
    color: #777777;
    font-size: 12px;
    font-style: italic;
    margin: 4px 0 8px 0;
    padding: 4px 8px;
    background-color: #F8F8F8;
    border-left: 3px solid #7c757d;
}

.table-container {
    overflow-x: auto;
    border-radius: 6px;
    background: white;
}

.gene-data-table {
    width: 100%;
    border-collapse: collapse;
    background: white;
    border: 1px solid #CCCCCC;
    border-radius: 6px;
    overflow: hidden;
}

.gene-data-table th {
    padding: 12px 8px;
    text-align: left;
    font-weight: 600;
    font-size: 13px;
    color: #333333;
    border-bottom: 1px solid #CCCCCC;
    white-space: nowrap;
}

.gene-data-table td {
    padding: 10px 8px;
    border-bottom: 1px solid #EEEEEE;
    font-size: 13px;
    color: #333333;
    vertical-align: top;
}

.gene-data-table tr:hover {
    background-color: #EFEFEF;
}

.gene-data-table tr:last-child td {
    border-bottom: none;
}

.summary-loading-indicator {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 4px 8px;
    background: #e3f2fd;
    border: 1px solid #bbdefb;
    border-radius: 4px;
    font-size: 12px;
    color: #1976d2;
}

.loading-spinner-small {
    display: inline-block;
    width: 12px;
    height: 12px;
    border: 2px solid #f3f3f3;
    border-top: 2px solid #1976d2;
    border-radius: 50%;
    animation: spin 1s linear infinite;
    margin-right: 8px;
}

@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}

.loading-text {
    font-weight: 500;
    white-space: nowrap;
    color: #6c757d;
    font-size: 14px;
}

/* Novelty & Relevance Column Styles */
.novelty-cell,
.relevance-cell,
.reason-cell {
    display: flex;
    align-items: center;
    min-height: 20px;
}

.score-content {
    display: flex;
    flex-direction: column;
    gap: 2px;
    font-size: 11px;
    line-height: 1.2;
    width: 100%;
}

.score-value {
    font-weight: 700;
    font-size: 13px;
}

/* High Score Text Color */
.novelty-cell .score-content .score-value,
.relevance-cell .score-content .score-value {
    color: #777777;
}

.novelty-cell .score-content.high-score .score-value,
.relevance-cell .score-content.high-score .score-value {
    color: #007BFF;
    font-weight: 700;
}

.reason-content {
    color: #495057;
    font-size: 14px;
    line-height: 1.3;
    word-wrap: break-word;
}

.empty-state {
    text-align: center;
    padding: 40px 20px;
    color: #6b7280;
    font-size: 16px;
    background: #f9fafb;
    border: 1px solid #e5e7eb;
    border-radius: 8px;
}

.empty-state p {
    margin: 0;
}

/* What's Next Information Box */
.whats-next-box {
    margin-top: 20px;
    padding: 15px 20px;
    background: #f8f9fa;
    border: 1px solid #e9ecef;
    border-left: 3px solid #FF6600;
}

.whats-next-content {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 15px;
}

.whats-next-text {
    color: #495057;
    font-size: 14px;
    font-weight: 500;
    flex: 1;
}

.whats-next-link {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 52px;
    height: 32px;
    background: #FF6600;
    color: white !important;
    text-decoration: none;
    border-radius: 4px;
    font-size: 12px;
    font-weight: 600;
    transition: all 0.2s ease;
    flex-shrink: 0;
    padding: 0 10px;
}

.whats-next-link:hover {
    background: #954835;
    transform: translateY(-1px);
    box-shadow: 0 2px 4px rgba(0, 123, 255, 0.3);
}

/* Pagination Styles */
.pagination-container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: 20px;
    padding: 15px 0;
    border-top: 1px solid #e9ecef;
}

.pagination-info {
    font-size: 14px;
    color: #6c757d;
}

.pagination-controls {
    display: flex;
    align-items: center;
    gap: 5px;
}

.pagination-btn {
    padding: 6px 12px;
    min-width: 32px;
    text-align: center;
    border: 1px solid #dee2e6;
    background: white;
    color: #495057;
    border-radius: 16px;
    cursor: pointer;
    font-size: 13px;
    transition: all 0.2s ease;
}

.pagination-btn:hover:not(:disabled) {
    background: #f8f9fa;
    border-color: #adb5bd;
}

.pagination-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
}

.first-last-btn {
    padding: 6px 8px;
    font-weight: bold;
    font-size: 12px;
}

.page-numbers {
    display: flex;
    gap: 2px;
}

.page-btn {
    padding: 6px 10px;
    border: 1px solid #dee2e6;
    background: white;
    color: #495057;
    border-radius: 17px;
    cursor: pointer;
    font-size: 13px;
    min-width: 33.5px;
    text-align: center;
    transition: all 0.2s ease;
}

.page-btn:hover {
    background: #f8f9fa;
    border-color: #adb5bd;
}

.page-btn.active {
    background: #55AAEE;
    color: white;
    border-color: #55AAEE;
}

.page-btn.active:hover {
    background: #55AAEE;
    border-color: #55AAEE;
}
</style>
