import { applyKrVariantFixturePipeline } from "./fixturePipeline";

export function createKrVariantState() {
    const state = {
            largeText: false,
            activeDensity: "all",
            activeInvestigator: "all-investigators",
            activeCarrierAge: "all-ages",
            activePhenotypeInvestigator: "all-investigators",
            activeSummaryLevel: "variant",
            activeDemographicLevel: "variant",
            activeDemographicAgeRange: "0-17-plus",
            activePhenotypeCategory: "",
            activeDemographic: "all",
            activeCarrierProfileTab: "phenotype",
            activeCarrierDetail: "phenotypes",
            activeResidualGroupName: "All CRDC",
            carrierSampleSort: { key: "id", direction: "asc" },
            carrierHpoSort: { key: "count", direction: "desc" },
            showDiseaseRegions: false,
            showDiseaseTrack: true,
            showGeneTrack: true,
            variant: {
                query: {
                    label: "chr15:22,000,220 G>C",
                    pathogenicity: "Pathogenic",
                    focusLeft: "50%",
                    focusBandWidth: "0.35rem",
                    window: "UBE3A Variant",
                    build: "GRCh38",
                },
                axisTicks: ["22,000,195", "22,000,207", "22,000,220", "22,000,232", "22,000,245"],
                minorTicks: [
                    { left: "10%", label: "200" },
                    { left: "20%", label: "205" },
                    { left: "30%", label: "210" },
                    { left: "40%", label: "215" },
                    { left: "50%", label: "220" },
                    { left: "60%", label: "225" },
                    { left: "70%", label: "230" },
                    { left: "80%", label: "235" },
                    { left: "90%", label: "240" },
                ],
                diseaseSignals: [
                    { label: "Angelman syndrome", scope: "UBE3A coding exon overlaps the queried base window" },
                    { label: "UBE3A-related neurodevelopmental disorder", scope: "gene-level disease annotation remains relevant in this 51 bp view" },
                ],
                genes: [
                    {
                        label: "UBE3A",
                        style: "left:10%; width:80%;",
                        focal: true,
                        exons: [
                            { left: "5%", width: "7%" },
                            { left: "18%", width: "5%" },
                            { left: "30%", width: "8%" },
                            { left: "47%", width: "6%" },
                            { left: "62%", width: "9%" },
                            { left: "82%", width: "10%" },
                        ],
                    },
                ],
                exonBases: [
                    { position: "213", base: "A" },
                    { position: "214", base: "T" },
                    { position: "215", base: "C" },
                    { position: "216", base: "A" },
                    { position: "217", base: "T" },
                    { position: "218", base: "C" },
                    { position: "219", base: "A" },
                    { position: "220", base: "G", variant: true },
                    { position: "221", base: "G" },
                    { position: "222", base: "A" },
                    { position: "223", base: "G" },
                    { position: "224", base: "C" },
                    { position: "225", base: "T" },
                    { position: "226", base: "T" },
                    { position: "227", base: "A" },
                ],
                codons: [
                    { label: "codon -2", ref: "ATC", aa: "Ile" },
                    { label: "codon -1", ref: "TCA", aa: "Ser" },
                    { label: "queried codon", ref: "CAG", aa: "Gln", alt: "G>C → CAC", altAa: "His", variant: true },
                    { label: "codon +1", ref: "GAG", aa: "Glu" },
                    { label: "codon +2", ref: "CTT", aa: "Leu" },
                ],
                markers: [
                    {
                        label: "●",
                        left: "50%",
                        badge: "G>C",
                        coordinate: "chr15:22,000,220 G>C",
                        pathogenicity: "Pathogenic",
                        classification: "P",
                        focal: true,
                        visibleInWindow: true,
                    },
                    {
                        label: "◆",
                        left: "70.7%",
                        badge: "A>T",
                        coordinate: "chr15:22,001,120 A>T",
                        pathogenicity: "Likely pathogenic",
                        classification: "LP",
                        visibleInWindow: false,
                    },
                ],
                densitySeries: {
                    "all-investigators": {
                        all: [0, 1, 1, 2, 2, 3, 4, 5, 4, 3, 5, 6, 7, 8, 9, 10, 12, 11, 10, 9, 11, 13, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 7, 8, 9, 10, 11, 12, 10, 9, 8, 7, 6, 5, 4, 3, 3, 2, 2, 1],
                        affected: [0, 0, 0, 1, 1, 1, 2, 2, 2, 1, 2, 3, 4, 5, 6, 7, 8, 7, 7, 6, 7, 8, 9, 10, 9, 8, 8, 7, 7, 6, 5, 4, 5, 5, 6, 7, 7, 8, 7, 6, 5, 4, 4, 3, 2, 2, 1, 1, 1, 0],
                        proband: [0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 2, 2, 3, 4, 4, 5, 6, 6, 5, 5, 6, 7, 8, 8, 7, 7, 6, 6, 5, 5, 4, 3, 4, 4, 5, 5, 6, 6, 5, 5, 4, 3, 3, 2, 2, 1, 1, 1, 0, 0],
                    },
                    "investigator-1": {
                        all: [0, 0, 1, 1, 1, 2, 2, 3, 2, 2, 3, 4, 4, 5, 6, 7, 8, 8, 7, 6, 7, 8, 9, 10, 9, 8, 7, 7, 6, 5, 5, 4, 4, 5, 5, 6, 6, 7, 6, 5, 5, 4, 3, 3, 2, 2, 1, 1, 0, 0],
                        affected: [0, 0, 0, 1, 1, 1, 1, 2, 2, 1, 2, 2, 3, 4, 4, 5, 6, 5, 5, 4, 5, 6, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 3, 4, 4, 5, 5, 5, 4, 4, 3, 3, 2, 2, 1, 1, 0, 0, 0, 0],
                        proband: [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 4, 4, 5, 5, 6, 6, 5, 5, 4, 4, 4, 3, 3, 2, 3, 3, 4, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0],
                    },
                    "investigator-2": {
                        all: [0, 1, 1, 1, 2, 2, 3, 3, 2, 2, 3, 3, 4, 5, 5, 6, 7, 6, 6, 5, 6, 7, 8, 8, 7, 7, 7, 6, 6, 5, 4, 4, 5, 5, 6, 6, 7, 8, 7, 6, 5, 5, 4, 3, 3, 2, 2, 1, 1, 0],
                        affected: [0, 0, 0, 0, 1, 1, 2, 2, 1, 1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 4, 5, 5, 6, 6, 6, 5, 5, 5, 4, 4, 3, 3, 4, 4, 5, 5, 5, 6, 5, 5, 4, 3, 3, 2, 2, 1, 1, 0, 0, 0],
                        proband: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 3, 4, 4, 5, 5, 5, 4, 4, 4, 4, 3, 3, 2, 3, 3, 4, 4, 4, 5, 4, 4, 3, 3, 2, 2, 1, 1, 0, 0, 0, 0],
                    },
                    "investigator-3": {
                        all: [0, 0, 0, 1, 1, 1, 2, 2, 3, 2, 2, 3, 3, 4, 5, 5, 6, 5, 5, 4, 5, 6, 7, 7, 6, 6, 5, 5, 5, 4, 4, 3, 4, 4, 5, 5, 6, 6, 5, 5, 4, 4, 3, 2, 2, 1, 1, 0, 0, 0],
                        affected: [0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1, 2, 2, 3, 3, 4, 5, 4, 4, 3, 4, 5, 5, 6, 5, 5, 4, 4, 4, 3, 3, 2, 3, 3, 4, 4, 4, 5, 4, 4, 3, 3, 2, 1, 1, 0, 0, 0, 0, 0],
                        proband: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 4, 4, 3, 3, 4, 4, 5, 5, 4, 4, 4, 3, 3, 3, 2, 2, 2, 3, 3, 3, 4, 4, 3, 3, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0],
                    },
                },
                geneContext: [
                    { label: "Nearest gene", value: "UBE3A" },
                    { label: "UBE3A variant carriers", value: "132 samples" },
                    { label: "P/LP variants in UBE3A", value: "9 variants" },
                ],
                relatedDiseases: [
                    { name: "Angelman syndrome", domain: "neural", signal: "UBE3A-linked" },
                    { name: "UBE3A-related neurodevelopmental disorder", domain: "neurodevelopmental", signal: "gene-level overlap" },
                ],
                variantEvidence: [
                    { label: "Search Variant", value: "chr15:22000220:G:C" },
                    { label: "Queried variant carriers", value: "18 samples" },
                    { label: "ClinVar", value: "Pathogenic" },
                    { label: "gnomAD AF", value: "0.00003" },
                    { label: "REVEL", value: "0.81" },
                    { label: "AlphaMissense", value: "0.94" },
                    { label: "LoFTEE", value: "HC" },
                ],
                phenotypes: {
                    "all-investigators": [
                        { label: "Abnormality of the nervous system [HP:0000707]", all: 72, proband: 41 },
                        { label: "Abnormality of head or neck [HP:0000152]", all: 58, proband: 36 },
                        { label: "Growth abnormality [HP:0001507]", all: 39, proband: 14 },
                        { label: "Abnormality of the digestive system [HP:0025031]", all: 34, proband: 20 },
                        { label: "Abnormality of the ear [HP:0000598]", all: 28, proband: 14 },
                    ],
                    "investigator-1": [
                        { label: "Abnormality of the nervous system [HP:0000707]", all: 68, proband: 39 },
                        { label: "Abnormality of head or neck [HP:0000152]", all: 54, proband: 32 },
                        { label: "Growth abnormality [HP:0001507]", all: 35, proband: 12 },
                        { label: "Abnormality of the digestive system [HP:0025031]", all: 30, proband: 18 },
                        { label: "Abnormality of the ear [HP:0000598]", all: 24, proband: 10 },
                    ],
                    "investigator-2": [
                        { label: "Abnormality of the nervous system [HP:0000707]", all: 75, proband: 46 },
                        { label: "Abnormality of head or neck [HP:0000152]", all: 62, proband: 40 },
                        { label: "Growth abnormality [HP:0001507]", all: 41, proband: 16 },
                        { label: "Abnormality of the digestive system [HP:0025031]", all: 36, proband: 22 },
                        { label: "Abnormality of the ear [HP:0000598]", all: 30, proband: 15 },
                    ],
                    "investigator-3": [
                        { label: "Abnormality of the nervous system [HP:0000707]", all: 70, proband: 38 },
                        { label: "Abnormality of head or neck [HP:0000152]", all: 56, proband: 34 },
                        { label: "Growth abnormality [HP:0001507]", all: 36, proband: 13 },
                        { label: "Abnormality of the digestive system [HP:0025031]", all: 32, proband: 18 },
                        { label: "Abnormality of the ear [HP:0000598]", all: 27, proband: 13 },
                    ],
                },
                variantPhenotypes: {
                    "all-investigators": [
                        { label: "Abnormality of the nervous system [HP:0000707]", all: 67, proband: 58 },
                        { label: "Abnormality of head or neck [HP:0000152]", all: 56, proband: 50 },
                        { label: "Growth abnormality [HP:0001507]", all: 33, proband: 25 },
                        { label: "Abnormality of the digestive system [HP:0025031]", all: 28, proband: 17 },
                        { label: "Abnormality of the ear [HP:0000598]", all: 22, proband: 17 },
                    ],
                    "investigator-1": [
                        { label: "Abnormality of the nervous system [HP:0000707]", all: 60, proband: 50 },
                        { label: "Abnormality of head or neck [HP:0000152]", all: 50, proband: 42 },
                        { label: "Growth abnormality [HP:0001507]", all: 30, proband: 17 },
                        { label: "Abnormality of the digestive system [HP:0025031]", all: 20, proband: 8 },
                        { label: "Abnormality of the ear [HP:0000598]", all: 20, proband: 8 },
                    ],
                    "investigator-2": [
                        { label: "Abnormality of the nervous system [HP:0000707]", all: 71, proband: 63 },
                        { label: "Abnormality of head or neck [HP:0000152]", all: 57, proband: 50 },
                        { label: "Growth abnormality [HP:0001507]", all: 43, proband: 25 },
                        { label: "Abnormality of the digestive system [HP:0025031]", all: 29, proband: 13 },
                        { label: "Abnormality of the ear [HP:0000598]", all: 29, proband: 13 },
                    ],
                    "investigator-3": [
                        { label: "Abnormality of the nervous system [HP:0000707]", all: 63, proband: 55 },
                        { label: "Abnormality of head or neck [HP:0000152]", all: 63, proband: 45 },
                        { label: "Growth abnormality [HP:0001507]", all: 25, proband: 18 },
                        { label: "Abnormality of the digestive system [HP:0025031]", all: 25, proband: 18 },
                        { label: "Abnormality of the ear [HP:0000598]", all: 13, proband: 9 },
                    ],
                },
                phenotypeDetails: {
                    "Abnormality of the nervous system [HP:0000707]": [
                        { label: "Developmental delay [HP:0001263]", value: 58 },
                        { label: "Speech delay [HP:0000750]", value: 46 },
                        { label: "Hypotonia [HP:0001252]", value: 42 },
                        { label: "Intellectual disability [HP:0001249]", value: 39 },
                        { label: "Seizure [HP:0001250]", value: 33 },
                        { label: "EEG abnormality [HP:0002353]", value: 31 },
                        { label: "Autism [HP:0000717]", value: 28 },
                        { label: "Motor delay [HP:0001270]", value: 25 },
                        { label: "Global developmental delay [HP:0001263]", value: 22 },
                    ],
                    "Abnormality of head or neck [HP:0000152]": [
                        { label: "Cleft palate [HP:0000175]", value: 44 },
                        { label: "Micrognathia [HP:0000347]", value: 39 },
                        { label: "High palate [HP:0000218]", value: 28 },
                        { label: "Facial asymmetry [HP:0000324]", value: 22 },
                        { label: "Broad nasal bridge [HP:0000431]", value: 18 },
                        { label: "Low-set ears [HP:0000369]", value: 17 },
                    ],
                    "Growth abnormality [HP:0001507]": [
                        { label: "Failure to thrive [HP:0001508]", value: 24 },
                        { label: "Short stature [HP:0004322]", value: 18 },
                        { label: "Poor weight gain [HP:0004325]", value: 16 },
                        { label: "Microcephaly [HP:0000252]", value: 14 },
                        { label: "Low birth weight [HP:0001518]", value: 11 },
                        { label: "Feeding intolerance [HP:0012531]", value: 8 },
                    ],
                    "Abnormality of the digestive system [HP:0025031]": [
                        { label: "Feeding difficulty [HP:0011968]", value: 33 },
                        { label: "Gastroesophageal reflux [HP:0002020]", value: 22 },
                        { label: "Constipation [HP:0002019]", value: 17 },
                        { label: "Dysphagia [HP:0002015]", value: 13 },
                        { label: "Tube feeding [HP:0033454]", value: 10 },
                    ],
                    "Abnormality of the ear [HP:0000598]": [
                        { label: "Hearing impairment [HP:0000365]", value: 19 },
                        { label: "Recurrent otitis media [HP:0000403]", value: 13 },
                        { label: "Abnormal auditory evoked potentials [HP:0006958]", value: 9 },
                    ],
                },
                demographics: {
                    all: [
                        { label: "0-1", female: 2, male: 3, femaleHeight: "12px", maleHeight: "18px" },
                        { label: "2-4", female: 4, male: 5, femaleHeight: "22px", maleHeight: "28px" },
                        { label: "5-12", female: 8, male: 7, femaleHeight: "44px", maleHeight: "38px" },
                        { label: "13-18", female: 11, male: 9, femaleHeight: "60px", maleHeight: "50px" },
                        { label: "Adult", female: 8, male: 7, femaleHeight: "44px", maleHeight: "38px" },
                    ],
                    proband: [
                        { label: "0-1", female: 1, male: 2, femaleHeight: "10px", maleHeight: "18px" },
                        { label: "2-4", female: 3, male: 4, femaleHeight: "24px", maleHeight: "32px" },
                        { label: "5-12", female: 6, male: 5, femaleHeight: "48px", maleHeight: "40px" },
                        { label: "13-18", female: 8, male: 6, femaleHeight: "64px", maleHeight: "48px" },
                        { label: "Adult", female: 5, male: 4, femaleHeight: "40px", maleHeight: "32px" },
                    ],
                },
                variantDemographics: {
                    all: [
                        { label: "0-1", female: 1, male: 1, femaleHeight: "16px", maleHeight: "16px" },
                        { label: "2-4", female: 2, male: 1, femaleHeight: "30px", maleHeight: "16px" },
                        { label: "5-12", female: 3, male: 2, femaleHeight: "44px", maleHeight: "30px" },
                        { label: "13-18", female: 3, male: 3, femaleHeight: "44px", maleHeight: "44px" },
                        { label: "Adult", female: 1, male: 1, femaleHeight: "16px", maleHeight: "16px" },
                    ],
                    proband: [
                        { label: "0-1", female: 1, male: 0, femaleHeight: "18px", maleHeight: "0px" },
                        { label: "2-4", female: 1, male: 1, femaleHeight: "18px", maleHeight: "18px" },
                        { label: "5-12", female: 2, male: 2, femaleHeight: "36px", maleHeight: "36px" },
                        { label: "13-18", female: 2, male: 2, femaleHeight: "36px", maleHeight: "36px" },
                        { label: "Adult", female: 1, male: 0, femaleHeight: "18px", maleHeight: "0px" },
                    ],
                },
                summaryScopes: {
                    variant: { all: 18, proband: 12, probandPercent: 67, female: 10, male: 8 },
                    gene: { all: 132, proband: 90, probandPercent: 68, female: 74, male: 58 },
                },
                residualGroups: [
                    { name: "All CRDC", low: "16%", width: "40%", median: "37%", selected: "72%", extreme: "top 9.1% vs CRDC" },
                    { name: "Investigator 1", low: "22%", width: "32%", median: "43%", selected: "64%", extreme: "6 carrier samples" },
                    { name: "Investigator 2", low: "28%", width: "42%", median: "57%", selected: "78%", extreme: "8 carrier samples" },
                    { name: "Investigator 3", low: "34%", width: "38%", median: "61%", selected: "82%", extreme: "4 carrier samples" },
                ],
                carrierSamples: [
                    { id: "BCH-12-34567-01", age: "13-18", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-12-34210-01", age: "5-12", group: "Investigator 1", proband: "non-Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-18-01422-01", age: "13-18", group: "Investigator 2", proband: "non-Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-09-88731-02", age: "2-4", group: "Investigator 3", proband: "non-Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-22-11880-01", age: "5-12", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-15-22031-01", age: "13-18", group: "Investigator 1", proband: "non-Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-07-33108-02", age: "Adult", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-03-00412-01", age: "0-1", group: "Investigator 1", proband: "non-Proband", affected: "No", diagnosed: "N/A" },
                    { id: "BCH-21-00084-01", age: "2-4", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-11-01267-02", age: "5-12", group: "Investigator 3", proband: "non-Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-19-01420-01", age: "13-18", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-14-01695-02", age: "Adult", group: "Investigator 1", proband: "non-Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-16-01851-01", age: "5-12", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-20-02177-02", age: "13-18", group: "Investigator 3", proband: "non-Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-02-02440-01", age: "0-1", group: "Investigator 1", proband: "Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-17-02704-01", age: "2-4", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-10-02922-02", age: "5-12", group: "Investigator 3", proband: "non-Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-08-03186-01", age: "13-18", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "N/A" },
                ],
                carrierPhenotypesByCategory: [
                    {
                        category: "Abnormality of the nervous system [HP:0000707]",
                        count: 18,
                        topTerms: ["Developmental delay", "Speech delay", "Seizure"],
                        terms: [
                            "Developmental delay [HP:0001263]",
                            "Speech delay [HP:0000750]",
                            "Intellectual disability [HP:0001249]",
                            "Seizure [HP:0001250]",
                            "EEG abnormality [HP:0002353]",
                            "Autism [HP:0000717]",
                            "Hypotonia [HP:0001252]",
                            "Motor delay [HP:0001270]",
                            "Global developmental delay [HP:0001263]",
                        ],
                    },
                    {
                        category: "Abnormality of head or neck [HP:0000152]",
                        count: 9,
                        topTerms: ["Cleft palate", "Micrognathia", "Low-set ears"],
                        terms: [
                            "Cleft palate [HP:0000175]",
                            "Micrognathia [HP:0000347]",
                            "High palate [HP:0000218]",
                            "Facial asymmetry [HP:0000324]",
                            "Broad nasal bridge [HP:0000431]",
                            "Low-set ears [HP:0000369]",
                            "Macroglossia [HP:0000158]",
                        ],
                    },
                    {
                        category: "Growth abnormality [HP:0001507]",
                        count: 8,
                        topTerms: ["Failure to thrive", "Short stature", "Poor weight gain"],
                        terms: [
                            "Failure to thrive [HP:0001508]",
                            "Short stature [HP:0004322]",
                            "Poor weight gain [HP:0004325]",
                            "Microcephaly [HP:0000252]",
                            "Low birth weight [HP:0001518]",
                            "Feeding intolerance [HP:0012531]",
                        ],
                    },
                    {
                        category: "Abnormality of the digestive system [HP:0025031]",
                        count: 6,
                        topTerms: ["Feeding difficulty", "Reflux", "Constipation"],
                        terms: [
                            "Feeding difficulty [HP:0011968]",
                            "Gastroesophageal reflux [HP:0002020]",
                            "Constipation [HP:0002019]",
                            "Dysphagia [HP:0002015]",
                            "Tube feeding [HP:0033454]",
                            "Vomiting [HP:0002013]",
                        ],
                    },
                    {
                        category: "Abnormality of the ear [HP:0000598]",
                        count: 5,
                        topTerms: ["Hearing impairment", "Otitis media", "Auditory evoked potentials"],
                        terms: [
                            "Hearing impairment [HP:0000365]",
                            "Recurrent otitis media [HP:0000403]",
                            "Abnormal auditory evoked potentials [HP:0006958]",
                        ],
                    },
                ],
                geneCarrierSamples: [
                    { id: "BCH-12-34567-01", age: "13-18", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-12-34210-01", age: "5-12", group: "Investigator 1", proband: "non-Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-05-49312-01", age: "2-4", group: "Investigator 6", proband: "Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-18-01422-01", age: "13-18", group: "Investigator 2", proband: "non-Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-09-88731-02", age: "2-4", group: "Investigator 3", proband: "non-Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-22-11880-01", age: "5-12", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-15-22031-01", age: "13-18", group: "Investigator 1", proband: "non-Proband", affected: "Yes", diagnosed: "Yes" },
                    { id: "BCH-07-33108-02", age: "Adult", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "N/A" },
                    { id: "BCH-03-00412-01", age: "0-1", group: "Investigator 1", proband: "non-Proband", affected: "No", diagnosed: "N/A" },
                    { id: "BCH-21-00084-01", age: "2-4", group: "Investigator 2", proband: "Proband", affected: "Yes", diagnosed: "Yes" },
                ],
                geneResidualGroups: [
                    { name: "All CRDC", low: "18%", width: "42%", median: "40%", selected: "68%", extreme: "top 13.4% vs CRDC" },
                    { name: "Investigator 1", low: "20%", width: "34%", median: "42%", selected: "61%", extreme: "34 gene carriers" },
                    { name: "Investigator 2", low: "30%", width: "44%", median: "58%", selected: "75%", extreme: "48 gene carriers" },
                    { name: "Investigator 3", low: "32%", width: "38%", median: "56%", selected: "72%", extreme: "20 gene carriers" },
                ],
                geneCarrierPhenotypesByCategory: [
                    {
                        category: "Abnormality of the nervous system [HP:0000707]",
                        count: 31,
                        topTerms: ["Developmental delay", "Seizure", "Autism"],
                        terms: [
                            "Developmental delay [HP:0001263]",
                            "Seizure [HP:0001250]",
                            "Autism [HP:0000717]",
                            "Speech delay [HP:0000750]",
                            "Hypotonia [HP:0001252]",
                        ],
                    },
                    {
                        category: "Abnormality of head or neck [HP:0000152]",
                        count: 18,
                        topTerms: ["Micrognathia", "Low-set ears", "Facial asymmetry"],
                        terms: [
                            "Micrognathia [HP:0000347]",
                            "Low-set ears [HP:0000369]",
                            "Facial asymmetry [HP:0000324]",
                            "High palate [HP:0000218]",
                        ],
                    },
                    {
                        category: "Growth abnormality [HP:0001507]",
                        count: 14,
                        topTerms: ["Short stature", "Failure to thrive", "Low birth weight"],
                        terms: [
                            "Short stature [HP:0004322]",
                            "Failure to thrive [HP:0001508]",
                            "Low birth weight [HP:0001518]",
                            "Microcephaly [HP:0000252]",
                        ],
                    },
                ],
            },
        };
    return applyKrVariantFixturePipeline(state);
}
