// Fixture pipeline for pb_Gene
// Generated by: scripts/export_portal_gene_fixture.R <GENE_SYMBOL>

let applyPortalGeneData = null;
try {
    // This optional generated file is local-only. A fresh shared checkout should
    // build without it and fall back to mockData.
    const generatedFixtures = require.context(".", false, /^\.\/portalGeneData\.generated\.js$/);
    if (generatedFixtures.keys().includes("./portalGeneData.generated.js")) {
        const mod = generatedFixtures("./portalGeneData.generated.js");
        applyPortalGeneData = mod.applyPortalGeneData;
    }
} catch (e) {
    // generated file not present — mockData fallback is used
}

export const pbGeneFixturePipeline = applyPortalGeneData
    ? [{ key: "rds-fixture", description: "RDS export for gene page.", apply: applyPortalGeneData }]
    : [];

export const fixtureGeneSymbol = applyPortalGeneData
    ? String(((applyPortalGeneData({}) || {}).geneInfo || {}).symbol || "").trim().toUpperCase()
    : "";

export function applyPbGeneFixturePipeline(baseState, requestedSymbolOverride = null) {
    const requestedSymbol = String(
        requestedSymbolOverride != null
            ? requestedSymbolOverride
            : ((baseState.geneInfo || {}).symbol || "")
    ).trim().toUpperCase();
    return pbGeneFixturePipeline.reduce(
        (state, step) => {
            const next = step.apply(state);
            const fixtureSymbol = String(((next || {}).geneInfo || {}).symbol || "").trim().toUpperCase();
            if (requestedSymbol && fixtureSymbol && requestedSymbol !== fixtureSymbol) {
                return state;
            }
            return next;
        },
        baseState
    );
}

export const fixtureLoaded = applyPortalGeneData !== null;
