<template>
    <div>
        <!-- Header -->
        <page-header
            :disease-group="$parent.diseaseGroup"
            :front-contents="$parent.frontContents"
            :rawPhenotypes="$parent.rawPhenotypes"
        ></page-header>

        <!-- Body -->
        <div class="container-fluid mdkp-body">
            <!-- Page title -->
            <div class="card mdkp-card dataset-page-header">
                <div class="row card-body">
                    <div class="col-md-8">
                        <h2>FALCON: A unified model of direct genetic support</h2>
                    </div>
                    <div class="col-md-4 falcon-cta-wrapper">
                        <a
                            class="btn btn-outline-primary"
                            href="https://d26k96aakgfksz.cloudfront.net/#home"
                            target="_blank"
                            rel="noopener noreferrer"
                        >Explore the full FALCON platform →</a>
                    </div>
                </div>
            </div>

            <!-- Method summary. Deliberately a sibling of the FALCON Zoom card
                 below, never a parent of it, so switching tabs cannot unmount
                 or reload the embedded tool. -->
            <div class="card mdkp-card">
                <div class="card-body">
                    <b-tabs content-class="mt-3 falcon-tab-content">
                        <b-tab title="Abstract" active>
                            <p>
                                Genome-wide association studies identify
                                thousands of variant-trait associations, yet
                                localizing true effector genes and resolving
                                biological pleiotropy remains confounded by
                                systemic cohort biases and linkage
                                disequilibrium. Here, we present FALCON, a
                                unified probabilistic model of direct genetic
                                support, to construct the Genetic Map
                                (G-Map)—a comprehensive, bias-adjusted catalog
                                of human gene-trait associations. By
                                correcting for redundant cohort signals, the
                                G-Map reveals the true distribution of
                                systemic pleiotropy across thousands of
                                phenotypes. We systematically categorize this
                                global genetic architecture into established
                                clinical targets, rapid repurposing
                                opportunities, and strictly novel discoveries.
                                Our analysis highlights heavily burdened
                                biological networks, demonstrating that
                                developmental and immune-linked loci function
                                as highly versatile pleiotropic hubs. By
                                mapping the genetic basis of human disease
                                from validated therapeutics to uncharted
                                biological frontiers, the G-Map provides a
                                robust, highly tractable foundation for novel
                                target prioritization and drug repurposing.
                            </p>
                            <div class="text-center falcon-infographic-wrapper">
                                <img
                                    class="img-fluid falcon-infographic"
                                    src="falcon/falcon_model.svg"
                                    alt="How FALCON works: input data types, FALCON's Bayesian network, and categorized outputs"
                                />
                                <p class="falcon-figure-caption">
                                    <strong>How FALCON works.</strong>
                                    (a) The diverse data types integrated by
                                    the model. (b) FALCON's core, represented
                                    as a Bayesian network — observed variables
                                    (shaded) are the input data, latent
                                    variables (unshaded) are the quantities
                                    the model estimates. (c) The outputs
                                    generated by FALCON.
                                </p>
                            </div>
                        </b-tab>
                        <b-tab title="Documentation">
                            <p>
                                Genome-wide association studies identify
                                thousands of variant-trait associations, yet
                                localizing true effector genes and resolving
                                biological pleiotropy remains confounded by
                                systemic cohort biases and linkage
                                disequilibrium. Here, we present FALCON, a
                                unified probabilistic model of direct genetic
                                support, to construct the Genetic Map
                                (G-Map)—a comprehensive, bias-adjusted catalog
                                of human gene-trait associations. By
                                correcting for redundant cohort signals, the
                                G-Map reveals the true distribution of
                                systemic pleiotropy across thousands of
                                phenotypes. We systematically categorize this
                                global genetic architecture into established
                                clinical targets, rapid repurposing
                                opportunities, and strictly novel discoveries.
                                Our analysis highlights heavily burdened
                                biological networks, demonstrating that
                                developmental and immune-linked loci function
                                as highly versatile pleiotropic hubs. By
                                mapping the genetic basis of human disease
                                from validated therapeutics to uncharted
                                biological frontiers, the G-Map provides a
                                robust, highly tractable foundation for novel
                                target prioritization and drug repurposing.
                            </p>
                            <h4 class="falcon-doc-heading">Overview of FALCON</h4>
                            <p>
                                FALCON is a probabilistic framework designed
                                to model rare and common genetic associations
                                together with epigenomic annotations as a
                                function of an unknown variable quantifying a
                                gene's genetic support, for every known gene.
                                It combines aspects of previous
                                variant-to-function algorithms that each
                                addressed specific data types and biology in
                                isolation. FALCON directly ingests standard
                                association statistics while accounting for
                                linkage disequilibrium and environmental
                                noise, integrating both common and rare
                                variants by tailoring their underlying
                                hyperparameter distributions. To inform its
                                predictive priors, the model combines diverse
                                functional genomic annotations — including
                                accessible chromatin, enhancers and
                                loss-of-function metrics — alongside
                                variant-to-gene (V2G) linkage scores derived
                                from 3D DNA looping and eQTL mapping.
                            </p>
                            <p>
                                FALCON introduces a gene-first approach across
                                the whole genome, in which at each step of the
                                iterative algorithm a gene competes with other
                                nearby candidates to explain all observable
                                data. In brief, it models the observed genetic
                                and genomic data, along with secondary latent
                                variables, as a function of a primary latent
                                variable representing a gene's probability of
                                phenotypic association.
                            </p>
                            <p>
                                The primary output is gene genetic support —
                                the posterior probability that a specific gene
                                is functionally associated with a phenotype,
                                conditioned on all observed data and latent
                                variables. This score, calculated via Gibbs
                                sampling, serves as a standardized metric for
                                evaluating genes within a high-dimensional
                                phenotype space. FALCON's architecture
                                simultaneously yields secondary outputs,
                                including variant causal probability,
                                fine-mapping and fine-linking to identify the
                                most likely target genes. Together these
                                probabilistic outputs generate an end-to-end
                                map translating genetic variation into
                                actionable insight to uncover functional
                                biology.
                            </p>
                        </b-tab>
                        <b-tab title="User guide">
                            <p>
                                The full FALCON platform (linked throughout
                                this page) has three main tools. Each one
                                opens in a new tab:
                            </p>
                            <ol>
                                <li>
                                    <strong>
                                        <a
                                            href="https://d26k96aakgfksz.cloudfront.net/#discover"
                                            target="_blank"
                                            rel="noopener noreferrer"
                                        >Discover →</a>
                                    </strong>
                                    — No gene or trait yet? Explore the
                                    landscape ranked by polygenicity and
                                    pleiotropy, and start from a curated
                                    suggestion.
                                </li>
                                <li>
                                    <strong>
                                        <a
                                            href="https://d26k96aakgfksz.cloudfront.net/#validate"
                                            target="_blank"
                                            rel="noopener noreferrer"
                                        >Validate →</a>
                                    </strong>
                                    — Have a gene and a phenotype? Get the
                                    verdict, the evidence chain, and one click
                                    into full provenance in FALCON Zoom.
                                </li>
                                <li>
                                    <strong>
                                        <a
                                            href="https://d26k96aakgfksz.cloudfront.net/#zoom"
                                            target="_blank"
                                            rel="noopener noreferrer"
                                        >FALCON Zoom →</a>
                                    </strong>
                                    — Try it live below, or open the full
                                    version to search any phenotype or gene,
                                    adjust plot options, inspect individual
                                    variants, and browse the underlying gene,
                                    variant, and LD-partner tables.
                                </li>
                            </ol>
                        </b-tab>
                    </b-tabs>
                </div>
            </div>

            <!-- Feature: FALCON Zoom, the centerpiece of this page. Served from
                 this portal's own public/falcon/zoom/ copy — same origin, no
                 dependency on the FALCON site's deployment. -->
            <div class="card mdkp-card falcon-zoom-card">
                <div class="card-body">
                    <h3>Try FALCON Zoom</h3>
                    <p>
                        Explore FALCON's gene-trait evidence at a single
                        locus — search any phenotype or gene, inspect
                        individual variants, and browse the gene, variant,
                        and LD-partner tables below. Seeded here with ABCA1
                        and LDL cholesterol.
                    </p>
                    <div class="falcon-zoom-iframe-wrapper">
                        <!-- Directory URL, not .../index.html, on purpose: a
                             server doing clean-URL rewrites turns
                             "falcon/zoom/index.html" into "falcon/zoom", and
                             every relative asset inside then resolves one
                             level too high (/falcon/app.js → 404). The
                             trailing slash pins the base to the directory. -->
                        <iframe
                            src="falcon/zoom/?gene=ABCA1&trait=LDL"
                            class="falcon-zoom-iframe"
                            title="FALCON Zoom"
                        ></iframe>
                    </div>
                    <div class="text-center">
                        <a
                            class="btn btn-outline-primary"
                            href="https://d26k96aakgfksz.cloudfront.net/#zoom?gene=ABCA1&trait=LDL"
                            target="_blank"
                            rel="noopener noreferrer"
                        >Open FALCON Zoom in the full app →</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <page-footer :disease-group="$parent.diseaseGroup"></page-footer>
    </div>
</template>
<style scoped>
.falcon-cta-wrapper {
    display: flex;
    align-items: center;
    justify-content: flex-end;
}

.falcon-infographic-wrapper {
    margin: 1.5rem 0;
}

/* Half size — the source figure is 2409px wide, which at full width
   dominates the tab far more than the abstract it illustrates. */
.falcon-infographic {
    max-width: 50%;
}

.falcon-figure-caption {
    max-width: 800px;
    margin: 0.75rem auto 0;
    font-size: 0.85em;
    color: #666;
    text-align: left;
}

.falcon-doc-heading {
    margin-top: 1.5rem;
    font-size: 1.1rem;
    font-weight: 600;
}

/* Keeps the tab card's height constant across the three tabs. Without it,
   switching tabs changes page height, which can add or remove the window
   scrollbar; that changes the iframe's width, and FALCON Zoom has a
   ResizeObserver that redraws its Plotly charts on any width change. Pinning
   the height means tab switching leaves the embedded tool completely alone. */
.falcon-tab-content {
    min-height: 620px;
}

/* The centerpiece of the page: full-width, generous height, and visually
   set apart so FALCON Zoom reads as the main event rather than one card
   among several. */
.falcon-zoom-card {
    border: 2px solid #0077b6;
}

.falcon-zoom-card h3 {
    color: #0077b6;
}

.falcon-zoom-iframe-wrapper {
    width: 100%;
    border-radius: 4px;
    margin-bottom: 1rem;
}

.falcon-zoom-iframe {
    width: 100%;
    height: 2284px;
    border: none;
    display: block;
}
</style>
