export const focusSourceOptions = [
    { key: "none", label: "No context" },
    { key: "orphanet", label: "Orphanet" },
    { key: "omim", label: "OMIM" },
    { key: "mondo", label: "MONDO" },
    { key: "decipher", label: "DECIPHER" },
    { key: "sample", label: "BCH sample ID" },
    { key: "investigator", label: "Investigator" },
    { key: "manual", label: "Manual HPO" },
];

export const mockFocusProfiles = {
    none: {
        source: "none",
        label: "No clinical context",
        sourceDetail: "No clinical context is used. Results are interpreted in discovery mode.",
        queryExample: "",
        sourceInputLabel: "No context",
        sourceInputPlaceholder: "",
        sourceInputHelp: "Search runs without a clinical comparison target.",
        hpoTerms: [],
    },
    orphanet: {
        source: "orphanet",
        label: "Early infantile developmental and epileptic encephalopathy Orphanet HPO profile",
        orphaId: "ORPHA:1934",
        sourceId: "ORPHA:1934",
        sourceDetail: "Mock profile resolved from an Orphanet disease label to disease HPO annotations.",
        queryExample: "Early infantile developmental and epileptic encephalopathy · ORPHA:1934",
        sourceInputLabel: "Orphanet disease",
        sourceInputPlaceholder: "Search disease name or ID, e.g. ORPHA:1934",
        sourceInputHelp: "The disease label resolves to an HPO-term profile before comparison.",
        hpoTerms: [
            { id: "HP:0001249", label: "Intellectual disability" },
            { id: "HP:0001250", label: "Seizure" },
            { id: "HP:0001337", label: "Tremor" },
            { id: "HP:0003323", label: "Progressive muscle weakness" },
        ],
    },
    omim: {
        source: "omim",
        label: "Developmental and epileptic encephalopathy 96 [OMIM:619340] HPO profile",
        sourceId: "OMIM:619340",
        sourceDetail: "Mock profile resolved from OMIM metadata to disease HPO annotations. Future source: phenotype.hpoa.",
        queryExample: "Developmental and epileptic encephalopathy 96 [OMIM:619340]",
        sourceInputLabel: "OMIM disease",
        sourceInputPlaceholder: "Search disease name or ID, e.g. OMIM:619340",
        sourceInputHelp: "OMIM provides the disease identity; comparison uses the resolved HPO profile, not the OMIM name string.",
        hpoTerms: [
            { id: "HP:0001249", label: "Intellectual disability" },
            { id: "HP:0001250", label: "Seizure" },
            { id: "HP:0002187", label: "Generalized tonic-clonic seizures" },
            { id: "HP:0001518", label: "Small for gestational age" },
        ],
    },
    mondo: {
        source: "mondo",
        label: "MONDO disease concept HPO profile",
        mondoId: "MONDO:0000001",
        sourceId: "MONDO:0000001",
        sourceDetail: "Mock profile resolved from a MONDO disease concept to mapped disease HPO annotations.",
        queryExample: "Search MONDO disease concept",
        sourceInputLabel: "MONDO disease concept",
        sourceInputPlaceholder: "Search disease name or ID, e.g. MONDO:...",
        sourceInputHelp: "MONDO provides disease concept mapping; comparison uses the resolved HPO profile, not the concept label alone.",
        hpoTerms: [
            { id: "HP:0001249", label: "Intellectual disability" },
            { id: "HP:0001250", label: "Seizure" },
        ],
    },
    decipher: {
        source: "decipher",
        label: "DECIPHER syndrome / disorder HPO profile",
        decipherId: "DECIPHER:profile",
        sourceId: "DECIPHER:profile",
        sourceDetail: "Mock profile resolved from a DECIPHER syndrome or disorder profile to HPO annotations.",
        queryExample: "Search DECIPHER profile",
        sourceInputLabel: "DECIPHER syndrome / disorder profile",
        sourceInputPlaceholder: "Search disease name or DECIPHER profile ID",
        sourceInputHelp: "DECIPHER provides phenotype context from a syndrome or disorder profile; comparison uses the resolved HPO terms.",
        hpoTerms: [
            { id: "HP:0001249", label: "Intellectual disability" },
            { id: "HP:0001337", label: "Tremor" },
        ],
    },
    sample: {
        source: "sample",
        label: "BCH-12-34210-01 sample HPO profile",
        sourceDetail: "Mock profile resolved from a BCH sample ID to observed sample HPO annotations.",
        queryExample: "BCH-12-34210-01",
        sourceInputLabel: "BCH sample ID",
        sourceInputPlaceholder: "e.g. BCH-12-34210-01",
        sourceInputHelp: "The sample ID resolves to that patient's HPO profile before comparison.",
        hpoTerms: [
            { id: "HP:0001263", label: "Developmental delay" },
            { id: "HP:0000175", label: "Cleft palate" },
            { id: "HP:0000750", label: "Speech delay" },
            { id: "HP:0001249", label: "Intellectual disability" },
        ],
    },
    investigator: {
        source: "investigator",
        label: "Investigator 2 phenotype signature",
        sourceDetail: "Mock profile resolved from an investigator group to an enriched HPO phenotype signature.",
        queryExample: "Investigator 2",
        sourceInputLabel: "Investigator group",
        sourceInputPlaceholder: "e.g. Investigator 2",
        sourceInputHelp: "The investigator group resolves to an enriched phenotype-signature HPO profile.",
        hpoTerms: [
            { id: "HP:0001263", label: "Developmental delay" },
            { id: "HP:0001510", label: "Growth delay" },
            { id: "HP:0011968", label: "Feeding difficulty" },
            { id: "HP:0000347", label: "Micrognathia" },
        ],
    },
    manual: {
        source: "manual",
        label: "Manual HPO context",
        sourceDetail: "User-edited HPO profile.",
        queryExample: "Developmental delay + cleft palate",
        sourceInputLabel: "Manual context label",
        sourceInputPlaceholder: "e.g. neurodevelopmental craniofacial profile",
        sourceInputHelp: "Manual context starts from editable HPO terms below.",
        hpoTerms: [
            { id: "HP:0001263", label: "Developmental delay" },
            { id: "HP:0000175", label: "Cleft palate" },
        ],
    },
};

export function createFocusFromTerms(label, terms) {
    return {
        source: "current-phenotype-query",
        label,
        sourceDetail: "Current phenotype search resolved to HPO query terms.",
        sourceQuery: label,
        hpoTerms: terms.map((term) => ({
            id: term.id,
            label: term.label,
        })),
    };
}
