import { applyPortalSampleData } from "./portalSampleData.generated";

export function createKrSampleState() {
    const state = {
            largeText: false,
            activeTab: "overview",
            referenceSampleId: "BCH-12-34210-01",
            selectedInvestigatorGroup: "Investigator 2",
            affinityMethodOpen: false,
            openPanels: {
                phenotypeProfile: false,
                allHpo: false,
                allGroupAffinity: false,
            },
            openMetrics: {
                "Closest phenotype neighbor": true,
                "Investigator context": false,
                "Public disease profile reference": false,
            },
            openGenotypeGroups: {
                "Same variant": false,
                "Same gene": true,
            },
            openDiseases: {
                "Kabuki syndrome-like": true,
            },
            expandedGenes: {
                KMT2D: true,
            },
            sample: {
                sampleId: "BCH-12-34567-01",
                affected: "Affected",
                proband: "Proband",
                affectedStatus: "Yes",
                probandStatus: "Yes",
                sex: "Female",
                ageGroup: "13-18",
                investigator: "Investigator 2",
                department: "Genetics",
                hpoTotal: 47,
                overviewHpoTermCount: 12,
                rareCodingGenes: 11,
                prioritizedGenes: 3,
                dominantPhenotypeDomain: "Abnormality of the nervous system [HP:0000707]",
                dominantPhenotypeCount: 14,
                overviewDominantHpoGroup: "Neurologic / Developmental",
                contextComparison: {
                    hpoTermCount: 18,
                    dominantHpoGroup: "Neurologic / Craniofacial",
                    overlap: "5 / 12 sample terms",
                    dominantOverlapGroup: "Craniofacial",
                },
                topCandidate: "KMT2D chr12:49,431,208 C>T",
                selectedResidual: "+1.8",
                groupScanSummary: "40 investigator signatures scored with annotation-burden correction",
                gendx: {
                    resultCount: 1,
                    shortStatus: "Yes",
                    status: "Yes · 1 reported panel variant",
                    gene: "KMT2D",
                    variantId: "chr12:49,431,208 C>T",
                    consequence: "missense",
                    pathogenicity: "Likely pathogenic",
                    interpretation: "Existing panel evidence is treated as a reported candidate, not automatic proof. The page checks whether phenotype similarity, similar-patient recurrence, and public disease match support the same interpretation.",
                },
                positionMetrics: [
                    {
                        label: "Closest phenotype neighbor",
                        value: "BCH-12-34210-01 · 91% similar to this sample",
                        text: "The searched sample would be 100% similar to itself and is excluded. BCH-12-34210-01 is the nearest other sample by weighted HPO overlap and semantic phenotype similarity.",
                    },
                    {
                        label: "Investigator context",
                        value: "Investigator 2",
                        text: "This is not a nearest-neighbor count. Each investigator group is summarized into a phenotype signature from enriched HPO terms. BCH-12-34567-01 is scored against all 40 group signatures; Investigator 2 is the strongest match in this mockup.",
                    },
                    {
                        label: "Public disease profile reference",
                        value: "Kabuki syndrome profile · 11 / 18 HPO terms",
                        text: "Public disease profile matching compares this sample's HPO profile with external disease-HPO annotations. This is reference evidence for review, not a clinical conclusion.",
                    },
                ],
                groupAffinityTop: [
                    { rank: "1/40", label: "Investigator 2", zScore: "2.1", dotLeft: "88%" },
                    { rank: "2/40", label: "Investigator 6", zScore: "1.6", dotLeft: "77%" },
                    { rank: "3/40", label: "Investigator 11", zScore: "1.3", dotLeft: "70%" },
                ],
                groupAffinityOther: [
                    { rank: "4/40", label: "Investigator 27", zScore: "1.0", dotLeft: "63%" },
                    { rank: "5/40", label: "Investigator 18", zScore: "0.8", dotLeft: "58%" },
                    { rank: "6/40", label: "Investigator 3", zScore: "0.4", dotLeft: "50%" },
                ],
                phenotypeDomains: [
                    {
                        name: "Abnormality of the nervous system [HP:0000707]",
                        count: 14,
                        width: "100%",
                        representativeTerms: ["Developmental delay [HP:0001263]", "Speech delay [HP:0000750]", "Hypotonia [HP:0001252]"],
                    },
                    {
                        name: "Abnormality of head or neck [HP:0000152]",
                        count: 11,
                        width: "79%",
                        representativeTerms: ["Cleft palate [HP:0000175]", "Micrognathia [HP:0000347]", "High palate [HP:0000218]"],
                    },
                    {
                        name: "Growth abnormality [HP:0001507]",
                        count: 7,
                        width: "50%",
                        representativeTerms: ["Failure to thrive [HP:0001508]", "Short stature [HP:0004322]", "Poor weight gain [HP:0004325]"],
                    },
                    {
                        name: "Abnormality of the digestive system [HP:0025031]",
                        count: 6,
                        width: "43%",
                        representativeTerms: ["Feeding difficulty [HP:0011968]", "Constipation [HP:0002019]", "Gastroesophageal reflux [HP:0002020]"],
                    },
                    {
                        name: "Abnormality of the ear [HP:0000598]",
                        count: 4,
                        width: "29%",
                        representativeTerms: ["Hearing impairment [HP:0000365]", "Conductive hearing impairment [HP:0000405]", "Recurrent otitis media [HP:0000403]"],
                    },
                ],
                fullHpoTerms: [
                    "Cleft palate [HP:0000175]",
                    "Developmental delay [HP:0001263]",
                    "Speech delay [HP:0000750]",
                    "Hypotonia [HP:0001252]",
                    "Micrognathia [HP:0000347]",
                    "Feeding difficulty [HP:0011968]",
                    "Failure to thrive [HP:0001508]",
                    "Hearing impairment [HP:0000365]",
                    "High palate [HP:0000218]",
                    "Short stature [HP:0004322]",
                    "Strabismus [HP:0000486]",
                    "Poor suck [HP:0002033]",
                    "Seizure [HP:0001250]",
                    "EEG abnormality [HP:0002353]",
                    "Autism [HP:0000717]",
                    "Motor delay [HP:0001270]",
                    "Delayed sitting [HP:0025336]",
                    "Delayed walking [HP:0031936]",
                    "Abnormal muscle tone [HP:0003808]",
                    "Ataxia [HP:0001251]",
                    "Poor weight gain [HP:0004325]",
                    "Microcephaly [HP:0000252]",
                    "Low birth weight [HP:0001518]",
                    "Feeding intolerance [HP:0012531]",
                    "Sleep disturbance [HP:0002360]",
                    "Insomnia [HP:0100785]",
                    "Fragmented sleep [HP:5200044]",
                    "Daytime somnolence [HP:0001262]",
                    "Facial asymmetry [HP:0000324]",
                    "Broad nasal bridge [HP:0000431]",
                    "Low-set ears [HP:0000369]",
                    "Macroglossia [HP:0000158]",
                    "Constipation [HP:0002019]",
                    "Gastroesophageal reflux [HP:0002020]",
                    "Recurrent infections [HP:0002719]",
                    "Abnormality of dentition [HP:0000164]",
                    "Joint hypermobility [HP:0001382]",
                    "Scoliosis [HP:0002650]",
                    "Astigmatism [HP:0000483]",
                    "Hypermetropia [HP:0000540]",
                    "Conductive hearing impairment [HP:0000405]",
                    "Recurrent otitis media [HP:0000403]",
                    "Attention deficit hyperactivity disorder [HP:0007018]",
                    "Anxiety [HP:0000739]",
                    "Poor fine motor coordination [HP:0007010]",
                    "Abnormal gait [HP:0001288]",
                    "Muscular hypotonia [HP:0001252]",
                ],
                phenotypeMatches: [
                    {
                        sampleId: "BCH-12-34210-01",
                        similarityRank: "1 · 91%",
                        sharedPhenotypeCount: "12 / 47",
                        sharedHpoTerms: [
                            "Developmental delay [HP:0001263]",
                            "Cleft palate [HP:0000175]",
                            "Microcephaly [HP:0000252]",
                            "Seizure [HP:0001250]",
                            "Hypotonia [HP:0001252]",
                            "Speech delay [HP:0000750]",
                            "Feeding difficulty [HP:0011968]",
                            "Short stature [HP:0004322]",
                            "Hearing impairment [HP:0000365]",
                            "Micrognathia [HP:0000347]",
                            "High palate [HP:0000218]",
                            "Failure to thrive [HP:0001508]",
                        ],
                        bestDisease: "Kabuki syndrome",
                        gene: "KMT2D",
                        sharedGenes: ["KMT2D"],
                        geneticClue: "LoF",
                        topSignalVariantId: "chr12:49,431,208 C>T",
                        investigator: "Investigator 2",
                        sex: "Female",
                        ageBand: "13-18",
                        notes: "Diagnosed reference; strongest phenotype neighbor",
                    },
                    {
                        sampleId: "BCH-18-01422-01",
                        similarityRank: "2 · 84%",
                        sharedPhenotypeCount: "10 / 47",
                        sharedHpoTerms: [
                            "Cleft palate [HP:0000175]",
                            "Hypotonia [HP:0001252]",
                            "Feeding difficulty [HP:0011968]",
                            "Micrognathia [HP:0000347]",
                            "Speech delay [HP:0000750]",
                            "Developmental delay [HP:0001263]",
                            "Short stature [HP:0004322]",
                            "High palate [HP:0000218]",
                            "Poor weight gain [HP:0004325]",
                            "Hearing impairment [HP:0000365]",
                        ],
                        bestDisease: "Kabuki-like",
                        gene: "KMT2D",
                        sharedGenes: ["KMT2D"],
                        geneticClue: "missense",
                        topSignalVariantId: "chr12:49,429,871 G>A",
                        investigator: "Investigator 2",
                        sex: "Female",
                        ageBand: "13-18",
                        notes: "Shares palate and hypotonia features",
                    },
                    {
                        sampleId: "BCH-09-88731-02",
                        similarityRank: "3 · 79%",
                        sharedPhenotypeCount: "9 / 47",
                        sharedHpoTerms: [
                            "Hearing impairment [HP:0000365]",
                            "Cleft palate [HP:0000175]",
                            "Micrognathia [HP:0000347]",
                            "Short stature [HP:0004322]",
                            "Developmental delay [HP:0001263]",
                            "Feeding difficulty [HP:0011968]",
                            "Failure to thrive [HP:0001508]",
                            "High palate [HP:0000218]",
                            "Recurrent otitis media [HP:0000403]",
                        ],
                        bestDisease: "CHARGE-like",
                        gene: "CHD7",
                        sharedGenes: ["CHD7"],
                        geneticClue: "LoF",
                        topSignalVariantId: "chr8:61,755,220 C>T",
                        investigator: "Investigator 11",
                        sex: "Male",
                        ageBand: "6-12",
                        notes: "Hearing and palate overlap",
                    },
                    {
                        sampleId: "BCH-22-11880-01",
                        similarityRank: "4 · 74%",
                        sharedPhenotypeCount: "8 / 47",
                        sharedHpoTerms: [
                            "Speech delay [HP:0000750]",
                            "Cleft palate [HP:0000175]",
                            "Developmental delay [HP:0001263]",
                            "Microcephaly [HP:0000252]",
                            "Poor fine motor coordination [HP:0007010]",
                            "Feeding difficulty [HP:0011968]",
                            "High palate [HP:0000218]",
                            "Micrognathia [HP:0000347]",
                        ],
                        bestDisease: "SATB2-associated syndrome-like",
                        gene: "SATB2",
                        sharedGenes: ["SATB2"],
                        geneticClue: "VUS",
                        topSignalVariantId: "chr2:200,213,443 A>G",
                        investigator: "Investigator 6",
                        sex: "Female",
                        ageBand: "13-18",
                        notes: "Speech delay and craniofacial overlap",
                    },
                ],
                genotypeGroups: [
                    {
                        label: "Same variant",
                        summary: "No exact same variant carriers in the current local fixture",
                        rows: [
                            {
                                sampleId: "none",
                                sampleLabel: "No exact same variant carrier",
                                similarity: "-",
                                sharedGene: "",
                                queryVariantEvidence: "Queried sample: chr12:49,431,208 C>T · missense",
                                matchedVariantEvidence: "Matched sample: none",
                                phenotypeOverlap: "-",
                                phenotypeProfileSimilarityLabel: "-",
                                keyPhenotypes: "-",
                            },
                        ],
                    },
                    {
                        label: "Same gene",
                        summary: "3 patients with KMT2D-related rare variants; 2 diagnosed Kabuki-like",
                        rows: [
                            {
                                sampleId: "BCH-12-34210-01",
                                similarity: "Same gene",
                                sharedGene: "KMT2D",
                                queryVariantEvidence: "Queried sample: chr12:49,431,208 C>T · missense",
                                matchedVariantEvidence: "Matched sample: LoF",
                                phenotypeOverlap: "12 / 47 shared HPO terms",
                                phenotypeProfileSimilarityLabel: "0.41 (0-1)",
                                keyPhenotypes: "Cleft palate; Speech delay; Short stature",
                            },
                            {
                                sampleId: "BCH-18-01422-01",
                                similarity: "Same gene",
                                sharedGene: "KMT2D",
                                queryVariantEvidence: "Queried sample: chr12:49,431,208 C>T · missense",
                                matchedVariantEvidence: "Matched sample: missense",
                                phenotypeOverlap: "10 / 47 shared HPO terms",
                                phenotypeProfileSimilarityLabel: "0.34 (0-1)",
                                keyPhenotypes: "Cleft palate; Hypotonia",
                            },
                            {
                                sampleId: "BCH-17-56004-02",
                                similarity: "Same gene",
                                sharedGene: "KMT2D",
                                queryVariantEvidence: "Queried sample: chr12:49,431,208 C>T · missense",
                                matchedVariantEvidence: "Matched sample: splice-region",
                                phenotypeOverlap: "6 / 47 shared HPO terms",
                                phenotypeProfileSimilarityLabel: "0.18 (0-1)",
                                keyPhenotypes: "Short stature; Characteristic facial features",
                            },
                        ],
                    },
                ],
                diseaseMatches: [
                    {
                        name: "Kabuki syndrome",
                        source: "Orphanet / HPO",
                        matchedHpoCount: 11,
                        totalDiseaseHpoTerms: 18,
                        overlap: "11 / 18",
                        notes: "Craniofacial and developmental terms overlap",
                        matchedHpoTerms: [
                            "Developmental delay [HP:0001263]",
                            "Cleft palate [HP:0000175]",
                            "Hypotonia [HP:0001252]",
                            "Short stature [HP:0004322]",
                            "Feeding difficulties [HP:0011968]",
                            "Microcephaly [HP:0000252]",
                            "Seizure [HP:0001250]",
                            "Intellectual disability [HP:0001249]",
                            "Ptosis [HP:0000508]",
                            "Long palpebral fissure [HP:0000637]",
                            "Abnormal facial shape [HP:0001999]",
                        ],
                    },
                    {
                        name: "CHARGE syndrome",
                        source: "Orphanet / HPO",
                        matchedHpoCount: 6,
                        totalDiseaseHpoTerms: 16,
                        overlap: "6 / 16",
                        notes: "Craniofacial and sensory-domain terms overlap",
                        matchedHpoTerms: [
                            "Cleft palate [HP:0000175]",
                            "Hearing impairment [HP:0000365]",
                            "Feeding difficulties [HP:0011968]",
                            "Growth delay [HP:0001510]",
                            "Developmental delay [HP:0001263]",
                            "Abnormal facial shape [HP:0001999]",
                        ],
                    },
                    {
                        name: "SATB2-associated syndrome",
                        source: "OMIM / HPO",
                        matchedHpoCount: 5,
                        totalDiseaseHpoTerms: 14,
                        overlap: "5 / 14",
                        notes: "Speech and palate terms overlap",
                        matchedHpoTerms: [
                            "Speech delay [HP:0000750]",
                            "Cleft palate [HP:0000175]",
                            "Developmental delay [HP:0001263]",
                            "Hypotonia [HP:0001252]",
                            "Microcephaly [HP:0000252]",
                        ],
                    },
                ],
                candidateGenes: [
                    {
                        gene: "KMT2D",
                        bestVariantId: "chr12:49,431,208 C>T",
                        bestVariant: "chr12:49,431,208 C>T · missense · rare",
                        diseaseLink: "Kabuki syndrome",
                        phenotypeFit: "11 / 18 disease HPO terms",
                        phenotypeFitTerms: [
                            "Developmental delay [HP:0001263]",
                            "Cleft palate [HP:0000175]",
                            "Hypotonia [HP:0001252]",
                            "Short stature [HP:0004322]",
                            "Microcephaly [HP:0000252]",
                            "Seizure [HP:0001250]",
                            "Intellectual disability [HP:0001249]",
                            "Feeding difficulties [HP:0011968]",
                            "Ptosis [HP:0000508]",
                            "Long palpebral fissure [HP:0000637]",
                            "Abnormal facial shape [HP:0001999]",
                        ],
                        internalSupport: "3 same-gene carriers, 2 phenotype-similar",
                        gendxSupport: "supporting evidence",
                        priorityReason: "rare variant + phenotype fit + same-gene recurrence",
                        variantCount: 2,
                        highestConsequence: "missense",
                        bestEvidence: "AlphaMissense 0.94",
                        clinvar: "LP",
                        inheritance: "AD",
                        diseases: "Kabuki syndrome",
                        phenotypeMatch: "11 / 18 public features",
                        similarCarrierSamples: "3 phenotype-similar samples",
                        variants: [
                            { variantId: "chr12:49,431,208 C>T", consequence: "missense", transcript: "NM_003482", gnomad: "0.00002", dp: 42, revel: "0.81", alphaMissense: "0.94", lof: "-", clinvar: "LP", tier: "1", carriers: 8, consistency: "craniofacial + neuro" },
                            { variantId: "chr12:49,512,044 G>A", consequence: "splice region", transcript: "NM_003482", gnomad: "0.00001", dp: 36, revel: "0.69", alphaMissense: "0.71", lof: "-", clinvar: "VUS", tier: "2", carriers: 3, consistency: "neurodevelopmental" },
                        ],
                    },
                    {
                        gene: "CHD7",
                        bestVariantId: "chr8:61,725,430 G>A",
                        bestVariant: "chr8:61,725,430 G>A · stop gained · rare",
                        diseaseLink: "CHARGE syndrome",
                        phenotypeFit: "6 / 16 disease HPO terms",
                        phenotypeFitTerms: [
                            "Cleft palate [HP:0000175]",
                            "Hearing impairment [HP:0000365]",
                            "Feeding difficulties [HP:0011968]",
                            "Developmental delay [HP:0001263]",
                            "Microcephaly [HP:0000252]",
                            "Short stature [HP:0004322]",
                        ],
                        internalSupport: "1 same-gene carrier, 1 phenotype-similar",
                        gendxSupport: "not available",
                        priorityReason: "rare variant + partial phenotype fit",
                        variantCount: 1,
                        highestConsequence: "stop gained",
                        bestEvidence: "LoFTEE HC",
                        clinvar: "P",
                        inheritance: "AD",
                        diseases: "CHARGE syndrome",
                        phenotypeMatch: "6 / 16 public features",
                        similarCarrierSamples: "1 phenotype-similar sample",
                        variants: [
                            { variantId: "chr8:61,725,430 G>A", consequence: "stop gained", transcript: "NM_017780", gnomad: "0", dp: 51, revel: "-", alphaMissense: "-", lof: "HC", clinvar: "P", tier: "1", carriers: 6, consistency: "sensory + craniofacial" },
                        ],
                    },
                    {
                        gene: "SATB2",
                        bestVariantId: "chr2:200,198,401 A>G",
                        bestVariant: "chr2:200,198,401 A>G · missense · rare",
                        diseaseLink: "SATB2-associated syndrome",
                        phenotypeFit: "5 / 14 disease HPO terms",
                        phenotypeFitTerms: [
                            "Speech delay [HP:0000750]",
                            "Cleft palate [HP:0000175]",
                            "Developmental delay [HP:0001263]",
                            "Microcephaly [HP:0000252]",
                            "Hypotonia [HP:0001252]",
                        ],
                        internalSupport: "1 same-gene carrier, 1 phenotype-similar",
                        gendxSupport: "not available",
                        priorityReason: "rare variant + speech and palate overlap",
                        variantCount: 1,
                        highestConsequence: "missense",
                        bestEvidence: "REVEL 0.77",
                        clinvar: "VUS",
                        inheritance: "AD",
                        diseases: "SATB2-associated syndrome",
                        phenotypeMatch: "5 / 14 public features",
                        similarCarrierSamples: "1 phenotype-similar sample",
                        variants: [
                            { variantId: "chr2:200,198,401 A>G", consequence: "missense", transcript: "NM_001172509", gnomad: "0.00004", dp: 29, revel: "0.77", alphaMissense: "0.70", lof: "-", clinvar: "VUS", tier: "2", carriers: 5, consistency: "speech + craniofacial" },
                        ],
                    },
                ],
                comparePreview: [
                    { label: "Phenotype overlap", value: "12 / 15 shared", text: "Shared craniofacial, neurodevelopmental, and growth-domain HPO terms." },
                    { label: "Genetic overlap", value: "same gene", text: "Both samples carry rare KMT2D variants, but not the exact same allele." },
                    { label: "Disease profile reference overlap", value: "Kabuki syndrome profile", text: "Both samples map to the same public disease profile reference." },
                    { label: "Conclusion", value: "related, not final", text: "Similarity supports reviewing the same disease mechanism, not an automatic clinical conclusion." },
                ],
            },
        };
    return applyPortalSampleData(state);
}
