export function createKrSampleState() {
    return {
            largeText: false,
            activeTab: "overview",
            referenceSampleId: "BCH-12-34210-01",
            selectedInvestigatorGroup: "Investigator 2",
            affinityMethodOpen: false,
            openPanels: {
                phenotypeProfile: true,
                allHpo: false,
                allGroupAffinity: false,
            },
            openMetrics: {
                "Closest phenotype neighbor": true,
                "Investigator context": false,
                "Public disease hypothesis": false,
            },
            openGenotypeGroups: {
                "Same variant": false,
                "Same gene": true,
                "Same pathway / mechanism": false,
            },
            openDiseases: {
                "Kabuki syndrome-like": true,
            },
            expandedGenes: {
                KMT2D: true,
            },
            sample: {
                sampleId: "BCH-12-34567-01",
                affected: "Affected",
                proband: "Proband",
                sex: "Female",
                ageGroup: "13-18",
                investigator: "Investigator 2",
                department: "Genetics",
                hpoTotal: 47,
                rareCodingGenes: 11,
                prioritizedGenes: 3,
                dominantPhenotypeDomain: "Abnormality of the nervous system [HP:0000707]",
                dominantPhenotypeCount: 14,
                topCandidate: "KMT2D chr12:49,431,208 C>T",
                selectedResidual: "+1.8",
                groupScanSummary: "40 investigator signatures scored with annotation-burden correction",
                gendx: {
                    shortStatus: "Yes",
                    status: "Yes · reported panel variant",
                    gene: "KMT2D",
                    variantId: "chr12:49,431,208 C>T",
                    pathogenicity: "Likely pathogenic",
                    interpretation: "Existing panel evidence is treated as a reported candidate, not automatic proof. The page checks whether phenotype similarity, similar-patient recurrence, and public disease match support the same interpretation.",
                },
                positionMetrics: [
                    {
                        label: "Closest phenotype neighbor",
                        value: "BCH-12-34210-01 · 91% similar to this sample",
                        text: "The searched sample would be 100% similar to itself and is excluded. BCH-12-34210-01 is the nearest other sample by weighted HPO overlap and semantic phenotype similarity.",
                    },
                    {
                        label: "Investigator context",
                        value: "Investigator 2",
                        text: "This is not a nearest-neighbor count. Each investigator group is summarized into a phenotype signature from enriched HPO terms. BCH-12-34567-01 is scored against all 40 group signatures; Investigator 2 is the strongest match in this mockup.",
                    },
                    {
                        label: "Public disease hypothesis",
                        value: "Kabuki-like · 11 / 18 phenotype features",
                        text: "Phenotype-based public disease matching finds 11 of 18 expected Kabuki-like features in the sample profile. The matched and missing features should be reviewed in the Disease hypotheses tab before interpreting this as diagnostic evidence.",
                    },
                ],
                groupAffinityTop: [
                    { rank: "1/40", label: "Investigator 2", zScore: "2.1", dotLeft: "88%" },
                    { rank: "2/40", label: "Investigator 6", zScore: "1.6", dotLeft: "77%" },
                    { rank: "3/40", label: "Investigator 11", zScore: "1.3", dotLeft: "70%" },
                ],
                groupAffinityOther: [
                    { rank: "4/40", label: "Investigator 27", zScore: "1.0", dotLeft: "63%" },
                    { rank: "5/40", label: "Investigator 18", zScore: "0.8", dotLeft: "58%" },
                    { rank: "6/40", label: "Investigator 3", zScore: "0.4", dotLeft: "50%" },
                ],
                phenotypeDomains: [
                    {
                        name: "Abnormality of the nervous system [HP:0000707]",
                        count: 14,
                        width: "100%",
                        representativeTerms: ["Developmental delay [HP:0001263]", "Speech delay [HP:0000750]", "Hypotonia [HP:0001252]"],
                    },
                    {
                        name: "Abnormality of head or neck [HP:0000152]",
                        count: 11,
                        width: "79%",
                        representativeTerms: ["Cleft palate [HP:0000175]", "Micrognathia [HP:0000347]", "High palate [HP:0000218]"],
                    },
                    {
                        name: "Growth abnormality [HP:0001507]",
                        count: 7,
                        width: "50%",
                        representativeTerms: ["Failure to thrive [HP:0001508]", "Short stature [HP:0004322]", "Poor weight gain [HP:0004325]"],
                    },
                    {
                        name: "Abnormality of the digestive system [HP:0025031]",
                        count: 6,
                        width: "43%",
                        representativeTerms: ["Feeding difficulty [HP:0011968]", "Constipation [HP:0002019]", "Gastroesophageal reflux [HP:0002020]"],
                    },
                    {
                        name: "Abnormality of the ear [HP:0000598]",
                        count: 4,
                        width: "29%",
                        representativeTerms: ["Hearing impairment [HP:0000365]", "Conductive hearing impairment [HP:0000405]", "Recurrent otitis media [HP:0000403]"],
                    },
                ],
                fullHpoTerms: [
                    "Cleft palate [HP:0000175]",
                    "Developmental delay [HP:0001263]",
                    "Speech delay [HP:0000750]",
                    "Hypotonia [HP:0001252]",
                    "Micrognathia [HP:0000347]",
                    "Feeding difficulty [HP:0011968]",
                    "Failure to thrive [HP:0001508]",
                    "Hearing impairment [HP:0000365]",
                    "High palate [HP:0000218]",
                    "Short stature [HP:0004322]",
                    "Strabismus [HP:0000486]",
                    "Poor suck [HP:0002033]",
                    "Seizure [HP:0001250]",
                    "EEG abnormality [HP:0002353]",
                    "Autism [HP:0000717]",
                    "Motor delay [HP:0001270]",
                    "Delayed sitting [HP:0025336]",
                    "Delayed walking [HP:0031936]",
                    "Abnormal muscle tone [HP:0003808]",
                    "Ataxia [HP:0001251]",
                    "Poor weight gain [HP:0004325]",
                    "Microcephaly [HP:0000252]",
                    "Low birth weight [HP:0001518]",
                    "Feeding intolerance [HP:0012531]",
                    "Sleep disturbance [HP:0002360]",
                    "Insomnia [HP:0100785]",
                    "Fragmented sleep [HP:5200044]",
                    "Daytime somnolence [HP:0001262]",
                    "Facial asymmetry [HP:0000324]",
                    "Broad nasal bridge [HP:0000431]",
                    "Low-set ears [HP:0000369]",
                    "Macroglossia [HP:0000158]",
                    "Constipation [HP:0002019]",
                    "Gastroesophageal reflux [HP:0002020]",
                    "Recurrent infections [HP:0002719]",
                    "Abnormality of dentition [HP:0000164]",
                    "Joint hypermobility [HP:0001382]",
                    "Scoliosis [HP:0002650]",
                    "Astigmatism [HP:0000483]",
                    "Hypermetropia [HP:0000540]",
                    "Conductive hearing impairment [HP:0000405]",
                    "Recurrent otitis media [HP:0000403]",
                    "Attention deficit hyperactivity disorder [HP:0007018]",
                    "Anxiety [HP:0000739]",
                    "Poor fine motor coordination [HP:0007010]",
                    "Abnormal gait [HP:0001288]",
                    "Muscular hypotonia [HP:0001252]",
                ],
                phenotypeMatches: [
                    { sampleId: "BCH-12-34210-01", similarityRank: "1 · 91% similar", sharedSymptoms: "12 shared HPO terms from BCH-12-34567-01 profile", diagnosis: "Kabuki syndrome", topSignal: "KMT2D LoF", notes: "diagnosed reference; strongest phenotype neighbor" },
                    { sampleId: "BCH-18-01422-01", similarityRank: "2 · 84% similar", sharedSymptoms: "10 shared HPO terms from BCH-12-34567-01 profile", diagnosis: "unsolved", topSignal: "KMT2D missense", notes: "same investigator-enriched neighbor set" },
                    { sampleId: "BCH-09-88731-02", similarityRank: "3 · 79% similar", sharedSymptoms: "9 shared HPO terms from BCH-12-34567-01 profile", diagnosis: "CHARGE-like", topSignal: "CHD7 LoF", notes: "sensory and palate overlap" },
                    { sampleId: "BCH-22-11880-01", similarityRank: "4 · 74% similar", sharedSymptoms: "8 shared HPO terms from BCH-12-34567-01 profile", diagnosis: "unsolved", topSignal: "SATB2 VUS", notes: "speech and palate overlap" },
                ],
                genotypeGroups: [
                    {
                        label: "Same variant",
                        summary: "No exact same variant carriers in the current local fixture",
                        rows: [
                            { sampleId: "none", similarity: "-", sharedSignal: "no exact match", phenotypeOverlap: "-", diagnosis: "-", keyPhenotypes: "-" },
                        ],
                    },
                    {
                        label: "Same gene",
                        summary: "3 patients with KMT2D-related rare variants; 2 diagnosed Kabuki-like",
                        rows: [
                            { sampleId: "BCH-12-34210-01", similarity: "same gene", sharedSignal: "KMT2D LoF", phenotypeOverlap: "high", diagnosis: "Kabuki syndrome", keyPhenotypes: "palate, speech, growth" },
                            { sampleId: "BCH-18-01422-01", similarity: "same gene", sharedSignal: "KMT2D missense", phenotypeOverlap: "moderate-high", diagnosis: "unsolved", keyPhenotypes: "palate, hypotonia" },
                            { sampleId: "BCH-17-56004-02", similarity: "same gene", sharedSignal: "KMT2D splice region", phenotypeOverlap: "moderate", diagnosis: "Kabuki-like", keyPhenotypes: "growth, facial" },
                        ],
                    },
                    {
                        label: "Same pathway / mechanism",
                        summary: "Chromatin-related genes with overlapping neurodevelopmental and craniofacial profiles",
                        rows: [
                            { sampleId: "BCH-09-88731-02", similarity: "chromatin pathway", sharedSignal: "CHD7 LoF", phenotypeOverlap: "moderate", diagnosis: "CHARGE-like", keyPhenotypes: "hearing, palate" },
                            { sampleId: "BCH-22-11880-01", similarity: "transcription regulation", sharedSignal: "SATB2 VUS", phenotypeOverlap: "moderate", diagnosis: "unsolved", keyPhenotypes: "speech, craniofacial" },
                        ],
                    },
                ],
                diseaseMatches: [
                    {
                        name: "Kabuki syndrome-like",
                        confidence: "moderate-high",
                        matchedPhenotypes: "11 / 18 public disease features",
                        supportingGenes: "KMT2D",
                        source: "OMIM / HPO / ClinVar",
                        matchedDetail: "Cleft palate, developmental delay, hypotonia, feeding difficulty, short stature, and facial morphology match the public disease profile.",
                        discordant: "Hearing loss is not observed in the local fixture, and immune features are not annotated.",
                        interpretation: "This is a disease hypothesis to review, not a confirmed diagnosis. Phenotype similarity, same-gene recurrence, and GenDX evidence all point toward this area.",
                    },
                    {
                        name: "CHARGE-like",
                        confidence: "low-moderate",
                        matchedPhenotypes: "6 / 16 public disease features",
                        supportingGenes: "CHD7",
                        source: "OMIM / Orphanet / HPO",
                        matchedDetail: "Craniofacial and sensory features overlap, but several core CHARGE features are absent or not annotated.",
                        discordant: "No choanal atresia or coloboma annotation in this fixture.",
                        interpretation: "Useful as a comparison group, but weaker than the Kabuki-like hypothesis.",
                    },
                    {
                        name: "SATB2-associated syndrome",
                        confidence: "low",
                        matchedPhenotypes: "5 / 14 public disease features",
                        supportingGenes: "SATB2",
                        source: "OMIM / HPO",
                        matchedDetail: "Speech delay and palate features overlap.",
                        discordant: "Gene evidence is weaker and fewer similar samples carry SATB2 variants.",
                        interpretation: "Keep as a secondary hypothesis if KMT2D evidence is not sufficient.",
                    },
                ],
                candidateGenes: [
                    {
                        gene: "KMT2D",
                        reason: "GenDX evidence, phenotype-similar patients, same-gene recurrence, and public disease match all converge here",
                        variantCount: 2,
                        highestConsequence: "missense",
                        bestEvidence: "AlphaMissense 0.94",
                        clinvar: "LP",
                        inheritance: "AD",
                        diseases: "Kabuki syndrome",
                        phenotypeMatch: "strong · 11 / 18 public features",
                        similarCarrierSamples: "3 phenotype-similar samples",
                        variants: [
                            { variantId: "chr12:49,431,208 C>T", consequence: "missense", transcript: "NM_003482", gnomad: "0.00002", dp: 42, revel: "0.81", alphaMissense: "0.94", lof: "-", clinvar: "LP", tier: "1", carriers: 8, consistency: "craniofacial + neuro" },
                            { variantId: "chr12:49,512,044 G>A", consequence: "splice region", transcript: "NM_003482", gnomad: "0.00001", dp: 36, revel: "0.69", alphaMissense: "0.71", lof: "-", clinvar: "VUS", tier: "2", carriers: 3, consistency: "neurodevelopmental" },
                        ],
                    },
                    {
                        gene: "CHD7",
                        reason: "Genotype-similar carrier set has sensory plus craniofacial overlap, but public disease match is weaker",
                        variantCount: 1,
                        highestConsequence: "stop gained",
                        bestEvidence: "LoFTEE HC",
                        clinvar: "P",
                        inheritance: "AD",
                        diseases: "CHARGE syndrome",
                        phenotypeMatch: "moderate · 6 / 16 public features",
                        similarCarrierSamples: "1 phenotype-similar sample",
                        variants: [
                            { variantId: "chr8:61,725,430 G>A", consequence: "stop gained", transcript: "NM_017780", gnomad: "0", dp: 51, revel: "-", alphaMissense: "-", lof: "HC", clinvar: "P", tier: "1", carriers: 6, consistency: "sensory + craniofacial" },
                        ],
                    },
                    {
                        gene: "SATB2",
                        reason: "Speech and palate overlap, but disease confidence and same-gene recurrence are lower",
                        variantCount: 1,
                        highestConsequence: "missense",
                        bestEvidence: "REVEL 0.77",
                        clinvar: "VUS",
                        inheritance: "AD",
                        diseases: "SATB2-associated syndrome",
                        phenotypeMatch: "low-moderate · 5 / 14 public features",
                        similarCarrierSamples: "1 phenotype-similar sample",
                        variants: [
                            { variantId: "chr2:200,198,401 A>G", consequence: "missense", transcript: "NM_001172509", gnomad: "0.00004", dp: 29, revel: "0.77", alphaMissense: "0.70", lof: "-", clinvar: "VUS", tier: "2", carriers: 5, consistency: "speech + craniofacial" },
                        ],
                    },
                ],
                comparePreview: [
                    { label: "Phenotype overlap", value: "12 / 15 shared", text: "Strong overlap in craniofacial, neurodevelopmental, and growth domains." },
                    { label: "Genetic overlap", value: "same gene", text: "Both samples carry rare KMT2D variants, but not the exact same allele." },
                    { label: "Disease hypothesis overlap", value: "Kabuki-like", text: "Both samples map to the same public disease hypothesis." },
                    { label: "Conclusion", value: "related, not confirmed", text: "Similarity supports reviewing the same disease mechanism, not automatic same diagnosis." },
                ],
            },
        };
}
