const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const inputPath = path.join(repoRoot, "data/reference_db/variant_identifier_reference.tsv");
const outputPath = path.join(repoRoot, "src/views/PbVariant/variantIdentifierReference.generated.js");
const lines = fs.readFileSync(inputPath, "utf8").trimEnd().split(/\r?\n/);
const headers = lines[0].split("\t");
const required = ["rsid", "variant_id", "gene_symbol", "assembly", "source"];
const indexes = Object.fromEntries(required.map(column => [column, headers.indexOf(column)]));

if (Object.values(indexes).some(index => index < 0)) {
    throw new Error("variant_identifier_reference.tsv is missing required columns.");
}

const data = {};
for (const line of lines.slice(1)) {
    const cells = line.split("\t");
    const rsid = String(cells[indexes.rsid] || "").trim().toLowerCase();
    const variantId = String(cells[indexes.variant_id] || "").trim();
    if (!/^rs\d+$/.test(rsid) || !variantId) continue;
    data[rsid] = {
        variantId,
        gene: String(cells[indexes.gene_symbol] || "").trim().toUpperCase(),
        assembly: String(cells[indexes.assembly] || "").trim(),
        source: String(cells[indexes.source] || "").trim(),
    };
}

const output = `// Generated by scripts/build_pb_variant_identifier_reference.js.
// Do not edit this file by hand; update data/reference_db/variant_identifier_reference.tsv.
const PB_VARIANT_IDENTIFIER_REFERENCE = ${JSON.stringify(data, null, 4)};
const PB_VARIANT_IDENTIFIER_BY_VARIANT = Object.fromEntries(
    Object.entries(PB_VARIANT_IDENTIFIER_REFERENCE).map(([rsid, row]) => [
        row.variantId.replace(/^chr/i, "").toUpperCase(),
        { ...row, rsid },
    ])
);

module.exports = { PB_VARIANT_IDENTIFIER_REFERENCE, PB_VARIANT_IDENTIFIER_BY_VARIANT };
`;

fs.writeFileSync(outputPath, output);
console.log(`Wrote ${Object.keys(data).length} GRCh38 rsID mappings to ${outputPath}`);
