const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const inputPath = path.join(repoRoot, "data/reference_db/gene_annotation_summary.tsv");
const outputPath = path.join(repoRoot, "src/views/PbGene/geneAnnotationReference.generated.js");

const keepColumns = [
    "ddg2p_confidence_categories",
    "ddg2p_allelic_requirements",
    "ddg2p_disease_names",
    "has_ddg2p_support",
    "has_panelapp_green_support",
    "green_panel_count",
    "panel_names",
    "modes_of_inheritance",
    "pathway_count",
    "reactome_count",
    "wikipathways_count",
    "pathway_names",
];

function cleanValue(value) {
    if (value == null || value === "" || value === "NA" || value === "NaN") return "";
    return value;
}

function hasAnnotation(row) {
    return row.has_ddg2p_support === "TRUE" ||
        row.has_panelapp_green_support === "TRUE" ||
        Number(row.pathway_count || 0) > 0;
}

const lines = fs.readFileSync(inputPath, "utf8").trimEnd().split(/\r?\n/);
const headers = lines[0].split("\t");
const geneIndex = headers.indexOf("gene_symbol");
const columnIndexes = keepColumns.map(column => headers.indexOf(column));

if (geneIndex < 0 || columnIndexes.some(index => index < 0)) {
    throw new Error("gene_annotation_summary.tsv is missing required columns.");
}

const data = {};
for (const line of lines.slice(1)) {
    const cells = line.split("\t");
    const gene = cleanValue(cells[geneIndex]).toUpperCase();
    if (!gene || gene === "-") continue;

    const row = {};
    keepColumns.forEach((column, i) => {
        row[column] = cleanValue(cells[columnIndexes[i]]);
    });
    if (!hasAnnotation(row)) continue;

    data[gene] = keepColumns.map(column => row[column]);
}

const sortedGenes = Object.keys(data).sort();
const entries = sortedGenes
    .map(gene => `    ${JSON.stringify(gene)}: ${JSON.stringify(data[gene])},`)
    .join("\n");

const output = `// Generated by scripts/build_pb_gene_annotation_reference.js from data/reference_db/gene_annotation_summary.tsv.
// Do not edit this file by hand.
export const PB_GENE_ANNOTATION_COLUMNS = ${JSON.stringify(keepColumns)};

export const PB_GENE_ANNOTATION_REFERENCE = {
${entries}
};
`;

fs.writeFileSync(outputPath, output);
console.log(`Wrote ${sortedGenes.length} annotated genes to ${outputPath}`);
