const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const inputPath = path.join(repoRoot, "data/reference_db/gene_exon_coords.tsv");
const outputPath = path.join(repoRoot, "src/views/PbGene/geneExonReference.generated.js");

const keepColumns = ["chrom", "start", "end", "strand", "exon_number"];

const lines = fs.readFileSync(inputPath, "utf8").trimEnd().split(/\r?\n/);
const headers = lines[0].split("\t");
const indexes = {
    gene: headers.indexOf("gene_symbol"),
};
keepColumns.forEach(column => {
    indexes[column] = headers.indexOf(column);
});

if (indexes.gene < 0 || keepColumns.some(column => indexes[column] < 0)) {
    throw new Error("gene_exon_coords.tsv is missing required columns.");
}

const data = {};
for (const line of lines.slice(1)) {
    const cells = line.split("\t");
    const gene = String(cells[indexes.gene] || "").trim().toUpperCase();
    if (!gene) continue;

    const exon = [
        cells[indexes.chrom],
        Number(cells[indexes.start]),
        Number(cells[indexes.end]),
        Number(cells[indexes.strand]),
        Number(cells[indexes.exon_number]),
    ];
    if (!Number.isFinite(exon[1]) || !Number.isFinite(exon[2])) continue;

    if (!data[gene]) data[gene] = [];
    data[gene].push(exon);
}

Object.keys(data).forEach(gene => {
    data[gene].sort((a, b) => a[1] - b[1] || a[4] - b[4]);
});

const entries = Object.keys(data).sort()
    .map(gene => `    ${JSON.stringify(gene)}: ${JSON.stringify(data[gene])},`)
    .join("\n");

const output = `// Generated by scripts/build_pb_gene_exon_reference.js from data/reference_db/gene_exon_coords.tsv.
// Do not edit this file by hand.
// Value columns: chrom, start, end, strand, exon_number.
export const PB_GENE_EXON_REFERENCE = {
${entries}
};
`;

fs.writeFileSync(outputPath, output);
console.log(`Wrote exon coordinates for ${Object.keys(data).length} genes to ${outputPath}`);
