const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const referenceDir = path.join(root, "data", "reference_db");
const outputPath = path.join(
    root,
    "src",
    "views",
    "KrClinicalFocus",
    "clinicalContextReference.generated.js"
);

function readTsv(filename) {
    const [headerLine, ...rows] = fs
        .readFileSync(path.join(referenceDir, filename), "utf8")
        .trim()
        .split("\n");
    const header = headerLine.split("\t");
    return rows.map((line) => {
        const values = line.split("\t");
        return Object.fromEntries(header.map((name, index) => [name, values[index]]));
    });
}

const hpoTerms = readTsv("hpo_term.tsv")
    .filter((row) => row.is_obsolete !== "TRUE")
    .map((row) => [row.hpo_id, row.hpo_name]);

const orphanetById = new Map();
for (const row of readTsv("hpo_disease_phenotype_positive.tsv")) {
    if (row.disease_source !== "ORPHA" || row.is_negated === "TRUE") continue;
    if (!orphanetById.has(row.source_disease_id)) {
        orphanetById.set(row.source_disease_id, {
            id: row.source_disease_id,
            name: row.disease_name,
            hpoIds: new Set(),
        });
    }
    orphanetById.get(row.source_disease_id).hpoIds.add(row.hpo_id);
}

const orphanetProfiles = [...orphanetById.values()]
    .map((profile) => [profile.id, profile.name, [...profile.hpoIds]])
    .sort((left, right) => left[1].localeCompare(right[1]));

const mondoNames = new Map(
    readTsv("mondo_term.tsv")
        .filter((row) => row.is_obsolete !== "TRUE")
        .map((row) => [row.mondo_id, row.mondo_name])
);
const mondoToOrphanet = new Map();

for (const row of readTsv("mondo_xref.tsv")) {
    if (row.xref_prefix !== "Orphanet") continue;
    const orphaId = `ORPHA:${row.xref_curie.split(":").pop()}`;
    if (!orphanetById.has(orphaId)) continue;
    if (!mondoToOrphanet.has(row.mondo_id)) mondoToOrphanet.set(row.mondo_id, new Set());
    mondoToOrphanet.get(row.mondo_id).add(orphaId);
}

const mondoProfiles = [...mondoToOrphanet].map(([mondoId, orphaIds]) => {
    const hpoIds = new Set();
    for (const orphaId of orphaIds) {
        for (const hpoId of orphanetById.get(orphaId).hpoIds) hpoIds.add(hpoId);
    }
    return [mondoId, mondoNames.get(mondoId) || mondoId, [...hpoIds], [...orphaIds]];
}).sort((left, right) => left[1].localeCompare(right[1]));

const output = [
    "// Generated by scripts/build_pb_front_clinical_context_reference.js.",
    `export const hpoTerms = ${JSON.stringify(hpoTerms)};`,
    `export const orphanetProfiles = ${JSON.stringify(orphanetProfiles)};`,
    `export const mondoProfiles = ${JSON.stringify(mondoProfiles)};`,
    "",
].join("\n");

fs.writeFileSync(outputPath, output);
console.log(
    `PB_FRONT_CONTEXT_REFERENCE_PASS ${hpoTerms.length} HPO terms, ${orphanetProfiles.length} Orphanet profiles, ${mondoProfiles.length} MONDO profiles`
);
