const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const genePath = path.join(repoRoot, "data/reference_db/gene.tsv");
const hgncPath = path.join(repoRoot, "data/reference_db/hgnc_complete_set.txt");
const outputPath = path.join(repoRoot, "src/views/PbGene/geneIdReference.generated.js");

const portalGenes = new Set(
    fs.readFileSync(genePath, "utf8")
        .trimEnd()
        .split(/\r?\n/)
        .slice(1)
        .map(line => line.split("\t")[0].trim().toUpperCase())
        .filter(gene => gene && gene !== "-")
);
const lines = fs.readFileSync(hgncPath, "utf8").trimEnd().split(/\r?\n/);
const headers = lines[0].split("\t");
const indexes = Object.fromEntries(
    ["symbol", "status", "ensembl_gene_id", "omim_id", "refseq_accession", "mane_select"]
        .map(column => [column, headers.indexOf(column)])
);
if (Object.values(indexes).some(index => index < 0)) {
    throw new Error("hgnc_complete_set.txt is missing required gene ID columns.");
}

const data = {};
for (const line of lines.slice(1)) {
    const cells = line.split("\t");
    const gene = String(cells[indexes.symbol] || "").trim().toUpperCase();
    if (!portalGenes.has(gene) || cells[indexes.status] !== "Approved") continue;
    const ensembl = String(cells[indexes.ensembl_gene_id] || "").trim();
    const omim = String(cells[indexes.omim_id] || "").trim().replace(/\|/g, ", ");
    const refseq = String(cells[indexes.refseq_accession] || "").trim().replace(/\|/g, ", ");
    const maneSelect = String(cells[indexes.mane_select] || "").trim().replace(/^"|"$/g, "");
    if (ensembl || omim || refseq || maneSelect) data[gene] = [ensembl, omim, refseq, maneSelect];
}

const entries = Object.keys(data).sort()
    .map(gene => `    ${JSON.stringify(gene)}: ${JSON.stringify(data[gene])},`)
    .join("\n");
const output = `// Generated by scripts/build_pb_gene_id_reference.js from HGNC gene-level identifiers.
// Do not edit this file by hand.
// Value columns: Ensembl gene ID, OMIM gene ID, RefSeq accession, MANE Select pair.
export const PB_GENE_ID_REFERENCE = {
${entries}
};
`;

fs.writeFileSync(outputPath, output);
console.log(`Wrote gene identifiers for ${Object.keys(data).length} portal genes to ${outputPath}`);
