import { applyPortalPhenotypeData } from "./portalPhenotypeData.generated";

export function createKrPhenotypeState() {
    const state = {
            largeText: false,
            activePhenotype: "",
            activeResidualGroup: "Investigator 2",
            activeOutlierSample: "BCH-12-34567-01",
            activeEvidenceTab: "individual",
            activeInsightTab: "disease",
            activePhenotypeAgeRange: "0-17-plus",
            candidateInfoOpen: false,
            activeExactCategory: "Abnormality of the nervous system",
            activeSampleProfileCategory: "Abnormality of the nervous system",
            diagnosisOpen: false,
            scatterMode: "all",
                openPanels: {
                    query: false,
                    semanticPhenotypes: false,
                    samples: false,
                    annotationQc: false,
                    investigatorSupport: false,
                    groups: true,
                phenotypes: true,
                termScore: true,
                disease: true,
                molecular: true,
            },
            phenotype: {
                query: {
                    display: "cleft palate [HP:0000175] + developmental delay [HP:0001263]",
                    subtext: "Reference phenotype profile: 2 exact terms · 3 approximate terms · 1 broad term down-weighted",
                },
                headline: [
                    { label: "Phenotype-similar samples", value: "132 / 904", detail: "raw weighted similarity search" },
                    { label: "Annotation-burden check", value: "Top 6.2% after total HPO-term correction", detail: "Best-matched sample is not explained only by many HPO terms" },
                    { label: "Dominant phenotype structure", value: "craniofacial + neurodevelopmental", detail: "co-observed domains" },
                ],
                candidateEvidenceSummary: [
                    { gene: "KMT2D", sources: ["External", "CRDC"] },
                    { gene: "CHD7", sources: ["External"] },
                    { gene: "SATB2", sources: ["CRDC"] },
                ],
                queryTerms: {
                    exact: [
                        { label: "Cleft palate", id: "HP:0000175", reason: "Entered query term and observed in cohort." },
                        { label: "Developmental delay", id: "HP:0001263", reason: "Entered query term and used in profile score." },
                    ],
                    expanded: [
                        { label: "Abnormal palate morphology", id: "HP:0000174", reason: "Parent term used because exact annotations can be sparse." },
                        { label: "Micrognathia", id: "HP:0000347", reason: "Frequently co-observed in the matched craniofacial cohort." },
                        { label: "Feeding difficulty", id: "HP:0011968", reason: "Co-observed term that strengthens the phenotype cluster." },
                    ],
                    downWeighted: [
                        { label: "Broad developmental abnormality", id: "HP:0000707", reason: "Too common across cohort; lower specificity." },
                    ],
                },
                termContribution: [
                    { label: "Cleft palate", id: "HP:0000175", prevalence: "3.1%", weight: "3.45", used: "query term", contribution: "3.45" },
                    { label: "Developmental delay", id: "HP:0001263", prevalence: "21.4%", weight: "1.53", used: "query term", contribution: "1.53" },
                    { label: "Abnormal palate morphology", id: "HP:0000174", prevalence: "6.7%", weight: "2.69", used: "semantic context", contribution: "not scored" },
                    { label: "Micrognathia", id: "HP:0000347", prevalence: "5.8%", weight: "2.82", used: "semantic context", contribution: "not scored" },
                    { label: "Broad developmental abnormality", id: "HP:0000707", prevalence: "38.0%", weight: "0.97", used: "down-weighted context", contribution: "not scored" },
                ],
                ageBins: [
                    { label: "0-4", female: 10, male: 8, femaleHeight: "28px", maleHeight: "24px" },
                    { label: "5-12", female: 16, male: 13, femaleHeight: "52px", maleHeight: "44px" },
                    { label: "13-18", female: 21, male: 15, femaleHeight: "70px", maleHeight: "58px" },
                    { label: "19-30", female: 19, male: 12, femaleHeight: "60px", maleHeight: "40px" },
                    { label: "30+", female: 11, male: 7, femaleHeight: "36px", maleHeight: "24px" },
                ],
                scorePoints: [
                    { id: "BCH-03-00412-01", group: "background", x: "12%", y: "21%", residual: "+0.2", selected: false },
                    { id: "BCH-02-02440-01", group: "affected", x: "20%", y: "31%", residual: "+0.6", selected: false },
                    { id: "BCH-18-01422-01", group: "background", x: "31%", y: "38%", residual: "+1.5", selected: false, outlier: true },
                    { id: "BCH-12-34210-01", group: "affected", x: "43%", y: "58%", residual: "+1.4", selected: false, outlier: true },
                    { id: "BCH-09-88731-02", group: "proband", x: "54%", y: "49%", residual: "+0.7", selected: false },
                    { id: "BCH-21-00084-01", group: "proband", x: "65%", y: "66%", residual: "+1.5", selected: false },
                    { id: "BCH-12-34567-01", group: "proband", x: "76%", y: "78%", residual: "+1.8", selected: true, outlier: true },
                    { id: "BCH-22-11880-01", group: "background", x: "86%", y: "56%", residual: "+0.5", selected: false },
                ],
                topSamples: [
                    {
                        rank: 1,
                        id: "BCH-12-34567-01",
                        group: "proband · Investigator 2",
                        investigator: "Investigator 2",
                        proband: "Yes",
                        affected: "Yes",
                        sex: "Female",
                        ageBand: "13-18",
                        sexAge: "Female · 13-18",
                        diagnosed: "Yes",
                        diagnosedVariant: "KMT2D chr12:49,431,208 C>T | LP",
                        queryTermsMatched: "2 / 2 query terms",
                        scoringTermsMatched: "4 expanded scoring terms",
                        totalTerms: 38,
                        rawScore: "3.9",
                        expectedScore: "2.1",
                        residual: "+1.8",
                        percentile: "top 6.2%",
                        equalOrHigher: "18 / 904",
                        signals: "KMT2D, CHD7",
                        phenotypeProfile: [
                            { category: "Abnormality of the nervous system", terms: "18 terms", queryPhenotype: "Developmental delay [HP:0001263]", phenotypeTerms: ["Developmental delay [HP:0001263]", "Speech delay [HP:0000750]", "Seizure [HP:0001250]", "Hypotonia [HP:0001252]"] },
                            { category: "Abnormality of head or neck", terms: "9 terms", queryPhenotype: "Cleft palate [HP:0000175]", phenotypeTerms: ["Cleft palate [HP:0000175]", "Micrognathia [HP:0000347]", "Low-set ears [HP:0000369]"] },
                            { category: "Growth abnormality", terms: "8 terms", queryPhenotype: "", phenotypeTerms: ["Failure to thrive [HP:0001508]", "Short stature [HP:0004322]", "Poor weight gain [HP:0004325]"] },
                        ],
                    },
                    {
                        rank: 2,
                        id: "BCH-12-34210-01",
                        group: "affected · Investigator 1",
                        investigator: "Investigator 1",
                        proband: "No",
                        affected: "Yes",
                        sex: "Male",
                        ageBand: "5-12",
                        sexAge: "Male · 5-12",
                        diagnosed: "N/A",
                        diagnosedVariant: "",
                        queryTermsMatched: "2 / 2 query terms",
                        scoringTermsMatched: "4 expanded scoring terms",
                        totalTerms: 31,
                        rawScore: "3.5",
                        expectedScore: "2.1",
                        residual: "+1.4",
                        percentile: "top 9.8%",
                        equalOrHigher: "31 / 904",
                        signals: "SATB2",
                        phenotypeProfile: [
                            { category: "Abnormality of head or neck", terms: "11 terms", queryPhenotype: "Cleft palate [HP:0000175]", phenotypeTerms: ["Cleft palate [HP:0000175]", "Micrognathia [HP:0000347]", "Retrognathia [HP:0000278]"] },
                            { category: "Abnormality of the nervous system", terms: "12 terms", queryPhenotype: "Developmental delay [HP:0001263]", phenotypeTerms: ["Developmental delay [HP:0001263]", "Hypotonia [HP:0001252]", "Speech delay [HP:0000750]"] },
                            { category: "Growth abnormality", terms: "5 terms", queryPhenotype: "", phenotypeTerms: ["Short stature [HP:0004322]", "Poor weight gain [HP:0004325]"] },
                        ],
                    },
                    {
                        rank: 3,
                        id: "BCH-21-00084-01",
                        group: "proband · Investigator 3",
                        investigator: "Investigator 3",
                        proband: "Yes",
                        affected: "Yes",
                        sex: "Female",
                        ageBand: "2-4",
                        sexAge: "Female · 2-4",
                        diagnosed: "N/A",
                        diagnosedVariant: "",
                        queryTermsMatched: "2 / 2 query terms",
                        scoringTermsMatched: "3 expanded scoring terms",
                        totalTerms: 29,
                        rawScore: "3.1",
                        expectedScore: "1.9",
                        residual: "+1.2",
                        percentile: "top 13.4%",
                        equalOrHigher: "47 / 904",
                        signals: "IRF6",
                        phenotypeProfile: [
                            { category: "Abnormality of head or neck", terms: "8 terms", queryPhenotype: "Cleft palate [HP:0000175]", phenotypeTerms: ["Cleft palate [HP:0000175]", "Abnormal palate morphology [HP:0000174]", "Micrognathia [HP:0000347]"] },
                            { category: "Abnormality of the nervous system", terms: "10 terms", queryPhenotype: "Developmental delay [HP:0001263]", phenotypeTerms: ["Developmental delay [HP:0001263]", "Speech delay [HP:0000750]", "Hypotonia [HP:0001252]"] },
                            { category: "Abnormality of the digestive system", terms: "4 terms", queryPhenotype: "", phenotypeTerms: ["Feeding difficulty [HP:0011968]", "Gastroesophageal reflux [HP:0002020]"] },
                        ],
                    },
                ],
                exactQueryMatchedSummary: [
                    {
                        category: "Abnormality of the nervous system",
                        sampleSupport: "88 / 132 (67%)",
                        queryTerms: "Developmental delay",
                        topAdditionalTerms: "Speech delay 46%, Hypotonia 42%, Seizure 33%",
                        phenotypeTerms: ["Speech delay [HP:0000750] · 46%", "Hypotonia [HP:0001252] · 42%", "Seizure [HP:0001250] · 33%", "Motor delay [HP:0001270] · 24%"],
                    },
                    {
                        category: "Abnormality of head or neck",
                        sampleSupport: "74 / 132 (56%)",
                        queryTerms: "Cleft palate",
                        topAdditionalTerms: "Micrognathia 41%, Low-set ears 22%, Retrognathia 18%",
                        phenotypeTerms: ["Micrognathia [HP:0000347] · 41%", "Low-set ears [HP:0000369] · 22%", "Retrognathia [HP:0000278] · 18%", "Abnormal palate morphology [HP:0000174] · 16%"],
                    },
                    {
                        category: "Growth abnormality",
                        sampleSupport: "44 / 132 (33%)",
                        queryTerms: "—",
                        topAdditionalTerms: "Failure to thrive 21%, Short stature 18%",
                        phenotypeTerms: ["Failure to thrive [HP:0001508] · 21%", "Short stature [HP:0004322] · 18%", "Poor weight gain [HP:0004325] · 11%"],
                    },
                    {
                        category: "Abnormality of the digestive system",
                        sampleSupport: "37 / 132 (28%)",
                        queryTerms: "—",
                        topAdditionalTerms: "Feeding difficulty 24%, Reflux 13%",
                        phenotypeTerms: ["Feeding difficulty [HP:0011968] · 24%", "Gastroesophageal reflux [HP:0002020] · 13%", "Constipation [HP:0002019] · 9%"],
                    },
                ],
                residualGroups: [
                    {
                        name: "All CRDC probands",
                        low: "15%",
                        width: "44%",
                        median: "39%",
                        selected: "78%",
                        medianValue: "+0.42",
                        extreme: "18 matched samples",
                        x: "34%",
                        y: "43%",
                        outliers: [
                            { id: "BCH-12-34567-01", status: "proband", score: "+1.8 residual", signal: "KMT2D, CHD7" },
                            { id: "BCH-12-34210-01", status: "affected", score: "+1.4 residual", signal: "SATB2" },
                            { id: "BCH-21-00084-01", status: "proband", score: "+1.2 residual", signal: "IRF6" },
                            { id: "BCH-09-88731-02", status: "affected", score: "+1.1 residual", signal: "CHD7" },
                        ],
                    },
                    {
                        name: "Investigator 1",
                        low: "18%",
                        width: "34%",
                        median: "42%",
                        selected: "66%",
                        medianValue: "+0.51",
                        extreme: "8 matched samples",
                        x: "47%",
                        y: "50%",
                        outliers: [
                            { id: "BCH-12-34210-01", status: "affected", score: "+1.4 residual", signal: "SATB2" },
                            { id: "BCH-02-02440-01", status: "proband", score: "+1.1 residual", signal: "IRF6" },
                            { id: "BCH-17-02704-01", status: "affected", score: "+0.9 residual", signal: "KMT2D" },
                            { id: "BCH-14-01695-02", status: "proband", score: "+0.8 residual", signal: "TBX1" },
                            { id: "BCH-16-01851-01", status: "affected", score: "+0.8 residual", signal: "CHD7" },
                            { id: "BCH-11-01267-02", status: "proband", score: "+0.7 residual", signal: "SATB2" },
                            { id: "BCH-19-01420-01", status: "affected", score: "+0.7 residual", signal: "IRF6" },
                            { id: "BCH-08-03186-01", status: "proband", score: "+0.6 residual", signal: "KMT2D" },
                        ],
                    },
                    {
                        name: "Investigator 2",
                        low: "30%",
                        width: "42%",
                        median: "61%",
                        selected: "78%",
                        medianValue: "+0.94",
                        extreme: "21 matched samples",
                        x: "62%",
                        y: "66%",
                        outliers: [
                            { id: "BCH-12-34567-01", status: "proband", score: "+1.8 residual", signal: "KMT2D, CHD7" },
                            { id: "BCH-18-01422-01", status: "affected", score: "+1.5 residual", signal: "SATB2" },
                            { id: "BCH-09-88731-02", status: "affected", score: "+1.2 residual", signal: "CHD7" },
                            { id: "BCH-22-11880-01", status: "proband", score: "+1.0 residual", signal: "IRF6" },
                            { id: "BCH-15-22031-01", status: "affected", score: "+0.9 residual", signal: "KMT2D" },
                        ],
                    },
                    {
                        name: "Investigator 3",
                        low: "12%",
                        width: "28%",
                        median: "29%",
                        selected: "52%",
                        medianValue: "+0.22",
                        extreme: "7 matched samples",
                        x: "51%",
                        y: "35%",
                        outliers: [
                            { id: "BCH-21-00084-01", status: "proband", score: "+1.2 residual", signal: "IRF6" },
                            { id: "BCH-03-00412-01", status: "affected", score: "+0.9 residual", signal: "SATB2" },
                            { id: "BCH-20-02177-02", status: "proband", score: "+0.7 residual", signal: "KMT2D" },
                        ],
                    },
                    {
                        name: "Craniofacial domain",
                        low: "36%",
                        width: "39%",
                        median: "64%",
                        selected: "81%",
                        medianValue: "+1.08",
                        extreme: "24 matched samples",
                        x: "74%",
                        y: "76%",
                        outliers: [
                            { id: "BCH-12-34567-01", status: "proband", score: "+1.8 residual", signal: "KMT2D, CHD7" },
                            { id: "BCH-12-34210-01", status: "affected", score: "+1.4 residual", signal: "SATB2" },
                            { id: "BCH-02-02440-01", status: "proband", score: "+1.1 residual", signal: "IRF6" },
                        ],
                    },
                ],
                inlineOutliers: [
                    { id: "BCH-12-34567-01", residual: "+1.8" },
                    { id: "BCH-12-34210-01", residual: "+1.4" },
                    { id: "BCH-18-01422-01", residual: "+1.5" },
                ],
                coObserved: [
                    { label: "Feeding difficulty [HP:0011968]", domain: "Digestive / neurodevelopmental", cluster: "Digestive cluster · newly discovered co-phenotype", count: "61 / 132", score: "risk score 0.74", width: "61%", relatedGenes: ["KMT2D", "CHD7", "SATB2"], samples: ["BCH-12-34567-01", "BCH-12-34210-01"], orpha: ["Kabuki syndrome", "CHARGE syndrome"] },
                    { label: "Micrognathia [HP:0000347]", domain: "Craniofacial", cluster: "HeadNeck cluster · specific craniofacial term", count: "54 / 132", score: "risk score 0.69", width: "54%", relatedGenes: ["IRF6", "TBX1"], samples: ["BCH-03-00412-01", "BCH-09-88731-02"], orpha: ["Van der Woude syndrome", "22q11.2 deletion"] },
                    { label: "Speech delay [HP:0000750]", domain: "Neurodevelopmental", cluster: "Nervous cluster · neurodevelopmental support", count: "49 / 132", score: "risk score 0.63", width: "49%", relatedGenes: ["SATB2", "KMT2D"], samples: ["BCH-12-34567-01", "BCH-18-01422-01"], orpha: ["SATB2-associated", "Kabuki syndrome"] },
                    { label: "Hearing impairment [HP:0000365]", domain: "Ear / sensory", cluster: "Ear cluster · sensory co-phenotype", count: "37 / 132", score: "risk score 0.52", width: "37%", relatedGenes: ["CHD7", "EYA1"], samples: ["BCH-18-01422-01", "BCH-22-11880-01"], orpha: ["CHARGE syndrome", "Branchiootorenal spectrum"] },
                    { label: "Growth delay [HP:0001510]", domain: "Growth / developmental", cluster: "Growth cluster · developmental support", count: "33 / 132", score: "risk score 0.48", width: "33%", relatedGenes: ["KMT2D", "SATB2"], samples: ["BCH-09-88731-02", "BCH-15-22031-01"], orpha: ["Kabuki syndrome", "SATB2-associated"] },
                ],
                diseaseCategories: [
                    { category: "Craniofacial syndromes", diseasesWithPhenotype: "18 / 120 diseases", meanScore: "0.82", examples: "Kabuki, Van der Woude, SATB2-associated", why: "Cleft palate, micrognathia, feeding difficulty form a coherent craniofacial cluster." },
                    { category: "Neurodevelopmental disorders", diseasesWithPhenotype: "14 / 166 diseases", meanScore: "0.68", examples: "CHARGE, Smith-Lemli-Opitz, Pitt-Hopkins", why: "Developmental delay and speech delay recur inside the matched cohort." },
                    { category: "Copy-number syndromes", diseasesWithPhenotype: "7 / 58 diseases", meanScore: "0.56", examples: "22q11.2 deletion, 1p36 deletion, 3q29 deletion", why: "Several matched samples show multi-system craniofacial plus developmental patterns." },
                ],
                diseaseCandidates: [
                    { disease: "Kabuki syndrome", profileMatch: "0.82 · 2 exact + 3 related · 18 disease HPO terms", externalAnnotation: "Kabuki syndrome · Orphanet / OMIM / HPOA", crdcEvidence: "KMT2D variants in 22 / 132 phenotype-matched samples", whyMatched: "cleft palate + developmental delay profile overlaps the disease HPO profile", linkedGenes: ["KMT2D"] },
                    { disease: "SATB2-associated syndrome-like profile", profileMatch: "0.77 · 2 exact + 2 related · 14 disease HPO terms", externalAnnotation: "SATB2-associated syndrome · OMIM / HPO", crdcEvidence: "SATB2 variants in 10 / 132 phenotype-matched samples", whyMatched: "craniofacial + neurodevelopmental profile overlaps the reference annotation", linkedGenes: ["SATB2"] },
                    { disease: "CHARGE syndrome spectrum", profileMatch: "0.68 · 1 exact + 3 related · 16 disease HPO terms", externalAnnotation: "CHARGE syndrome · Orphanet / HPO", crdcEvidence: "CHD7 variants in 17 / 132 phenotype-matched samples", whyMatched: "cleft palate plus related craniofacial and sensory terms align with the reference profile", linkedGenes: ["CHD7"] },
                    { disease: "Van der Woude syndrome", profileMatch: "0.61 · 1 exact + 1 related · 9 disease HPO terms", externalAnnotation: "Van der Woude syndrome · OMIM / HPO", crdcEvidence: "IRF6 variants in 15 / 132 phenotype-matched samples", whyMatched: "cleft-focused profile overlaps the external disease-HPO annotation", linkedGenes: ["IRF6"] },
                ],
                geneCandidates: [
                    { gene: "KMT2D", profileMatch: "0.82 · 2 exact + 3 related", externalAnnotation: "Kabuki syndrome · Orphanet/HPOA", cohortCarrierEvidence: "22 / 132 phenotype-matched samples carry rare KMT2D variants", whyMatched: "cleft palate + developmental delay profile overlaps disease HPO profile" },
                    { gene: "SATB2", profileMatch: "0.77 · 2 exact + 2 related", externalAnnotation: "SATB2-associated syndrome · OMIM/HPO", cohortCarrierEvidence: "10 / 132 phenotype-matched samples carry rare SATB2 variants", whyMatched: "craniofacial + neurodevelopmental HPO profile aligns with SATB2-linked annotations" },
                    { gene: "CHD7", profileMatch: "0.68 · 1 exact + 3 related", externalAnnotation: "CHARGE syndrome · Orphanet/HPO", cohortCarrierEvidence: "17 / 132 phenotype-matched samples carry rare CHD7 variants", whyMatched: "cleft palate plus related craniofacial and sensory terms overlap CHD7-linked profiles" },
                    { gene: "IRF6", profileMatch: "0.61 · 1 exact + 1 related", externalAnnotation: "Van der Woude syndrome · OMIM/HPO", cohortCarrierEvidence: "15 / 132 phenotype-matched samples carry rare IRF6 variants", whyMatched: "cleft-focused HPO profile overlaps IRF6-linked disease annotation" },
                ],
                genes: [
                    { gene: "KMT2D", carriers: "22 / 132 carriers", relevance: "0.82", domain: "craniofacial, neurodevelopmental" },
                    { gene: "CHD7", carriers: "17 / 132 carriers", relevance: "0.79", domain: "sensory, craniofacial" },
                    { gene: "SATB2", carriers: "10 / 132 carriers", relevance: "0.77", domain: "craniofacial, speech" },
                    { gene: "IRF6", carriers: "15 / 132 carriers", relevance: "0.74", domain: "cleft phenotype focused" },
                ],
                candidateVariants: [
                    { gene: "KMT2D", id: "chr12:49,431,208 C>T", carriers: "8 / 132 matched samples", coherence: "11 / 18 disease HPO terms", pathogenicity: "Likely pathogenic", link: "/krVariant.html?query=KMT2D" },
                    { gene: "CHD7", id: "chr8:61,725,430 G>A", carriers: "6 / 132 matched samples", coherence: "6 / 16 disease HPO terms", pathogenicity: "Pathogenic", link: "/krVariant.html?query=CHD7" },
                    { gene: "IRF6", id: "chr1:209,989,401 A>G", carriers: "5 / 132 matched samples", coherence: "cleft-focused phenotype fit", pathogenicity: "Likely pathogenic", link: "/krVariant.html?query=IRF6" },
                ],
            },
        };
    return applyPortalPhenotypeData(state);
}
