const PHENOTYPE_MATCH_INVESTIGATORS = ["Investigator B", "Investigator C", "Investigator B", "Investigator D", "Investigator A"];
const PHENOTYPE_MATCHES = Array.from({ length: 50 }, (_, index) => ({
    rank: index + 1,
    sampleId: `BCH-24-${10001 + index}-01`,
    matchedHpo: 84 - Math.floor(index * 29 / 49),
    investigator: PHENOTYPE_MATCH_INVESTIGATORS[index % PHENOTYPE_MATCH_INVESTIGATORS.length],
    age: 5 + (index * 7) % 25,
    sex: index % 2 ? "Male" : "Female",
}));

export const PB_SAMPLE_MOCK = {
    sampleId: "BCH-00-00000-01",
    sex: "Female",
    ageAtEnrollment: "11 years",
    affected: "Yes",
    investigator: "Investigator A",
    familyMembers: [
        { sampleId: "BCH-00-00000-01", role: "case" },
        { sampleId: "BCH-00-00000-02", role: "twin" },
        { sampleId: "BCH-00-00000-03", role: "sibling" },
        { sampleId: "BCH-00-00000-11", role: "mother" },
        { sampleId: "BCH-00-00000-12", role: "father" },
    ],
    phenotypeTotal: 131,
    phenotypeMatchEligibleCount: 12475,
    phenotypeMatches: PHENOTYPE_MATCHES,
    investigatorPhenotypeSummary: [
        { rank: 1, investigator: "Investigator B", medianResidual: 1.42, iqr: "0.88–1.91", n: 1850, currentGroup: false },
        { rank: 2, investigator: "Investigator C", medianResidual: 1.08, iqr: "0.54–1.62", n: 1630, currentGroup: false },
        { rank: 3, investigator: "Investigator A", medianResidual: 0.71, iqr: "0.20–1.18", n: 1516, currentGroup: true },
        { rank: 4, investigator: "Investigator D", medianResidual: 0.48, iqr: "−0.08–0.97", n: 1284, currentGroup: false },
        { rank: 5, investigator: "Investigator E", medianResidual: 0.19, iqr: "−0.31–0.72", n: 1195, currentGroup: false },
        { rank: 6, investigator: "Investigator F", medianResidual: 0.04, iqr: "−0.42–0.59", n: 1100, currentGroup: false },
        { rank: 7, investigator: "Investigator G", medianResidual: -0.11, iqr: "−0.57–0.41", n: 1050, currentGroup: false },
        { rank: 8, investigator: "Investigator H", medianResidual: -0.26, iqr: "−0.69–0.23", n: 1000, currentGroup: false },
        { rank: 9, investigator: "Investigator I", medianResidual: -0.39, iqr: "−0.83–0.08", n: 950, currentGroup: false },
        { rank: 10, investigator: "Investigator J", medianResidual: -0.55, iqr: "−0.98–−0.12", n: 900, currentGroup: false },
    ],
    phenotypeGroups: [
        {
            id: "HP:0000152",
            label: "Abnormality of head or neck",
            count: 31,
            terms: [
                { id: "HP:0000252", label: "Microcephaly" },
                { id: "HP:0000316", label: "Hypertelorism" },
            ],
        },
        {
            id: "HP:0033127",
            label: "Abnormality of the musculoskeletal system",
            count: 27,
            terms: [
                { id: "HP:0011844", label: "Abnormal appendicular skeleton morphology" },
                { id: "HP:0001367", label: "Abnormal joint morphology" },
            ],
        },
        {
            id: "HP:0040064",
            label: "Abnormality of limbs",
            count: 17,
            terms: [
                { id: "HP:0011297", label: "Abnormal digit morphology" },
                { id: "HP:0001167", label: "Abnormal finger morphology" },
            ],
        },
        {
            id: "HP:0002086",
            label: "Abnormality of the respiratory system",
            count: 17,
            terms: [
                { id: "HP:0002088", label: "Abnormal lung morphology" },
                { id: "HP:0006530", label: "Abnormal pulmonary interstitial morphology" },
            ],
        },
        {
            id: "HP:0001626",
            label: "Abnormality of the cardiovascular system",
            count: 15,
            terms: [
                { id: "HP:0001627", label: "Abnormal heart morphology" },
                { id: "HP:0030680", label: "Abnormal cardiovascular system physiology" },
            ],
        },
    ],
    variants: [
        {
            type: "Type 1",
            typeLabel: "ClinVar high-review P/LP · investigator scope MATCH",
            trackClass: "clinical",
            tier: "Tier 1",
            clinvarReview: { stars: 3, label: "reviewed by expert panel" },
            gene: "LCA5",
            id: "chr6:79518824:A:T",
            consequence: "stop gained · LoFTEE HC",
            genotype: "1/1",
            diseases: [
                {
                    id: "ORPHA:364055",
                    matchedHpoCount: 24,
                    diseaseHpoCount: 64,
                    phenotypeCoverage: 37.5,
                    samplePercentile: 90,
                    samplePercentileSuffix: "th",
                    investigatorMeanPercentile: 92,
                    investigatorPercentileSuffix: "nd",
                    differenceLabel: "−2",
                    matchTooltip: "Illustrative residual PheRS 2.14. Percentile 90 among 12,480 disease-specific eligible samples. Investigator A mean: percentile 92 among 216 eligible samples, excluding this sample.",
                },
                {
                    id: "ORPHA:65",
                    matchedHpoCount: 18,
                    diseaseHpoCount: 52,
                    phenotypeCoverage: 34.6,
                    samplePercentile: 76,
                    samplePercentileSuffix: "th",
                    investigatorMeanPercentile: 61,
                    investigatorPercentileSuffix: "st",
                    differenceLabel: "+15",
                    matchTooltip: "Illustrative residual PheRS 1.31. Percentile 76 among 12,480 disease-specific eligible samples. Investigator A mean: percentile 61 among 216 eligible samples, excluding this sample.",
                },
            ],
        },
        {
            type: "Type 3",
            typeLabel: "Known-gene evidence · investigator scope MATCH",
            trackClass: "reanalysis",
            tier: "Tier 2",
            clinvarReview: { stars: 1, label: "criteria provided, single submitter" },
            gene: "LCA5",
            id: "chr6:79519012:G:C",
            consequence: "missense variant",
            genotype: "0/1",
            diseases: [
                {
                    id: "ORPHA:65",
                    matchedHpoCount: 18,
                    diseaseHpoCount: 52,
                    phenotypeCoverage: 34.6,
                    samplePercentile: 76,
                    samplePercentileSuffix: "th",
                    investigatorMeanPercentile: 61,
                    investigatorPercentileSuffix: "st",
                    differenceLabel: "+15",
                    matchTooltip: "Illustrative residual PheRS 1.31. Percentile 76 among 12,480 disease-specific eligible samples. Investigator A mean: percentile 61 among 216 eligible samples, excluding this sample.",
                },
            ],
        },
    ],
    allVariants: [
        {
            id: "chr6:79518824:A:T",
            gene: "LCA5",
            consequence: "stop_gained",
            transcript: "NM_181714.4",
            crdcCarrierFrequency: "Unavailable",
            gnomadAf: "—",
            revel: "—",
            alphaMissense: "—",
            loftee: "HC",
            clinvar: "Pathogenic",
            genotype: "1/1",
            tier: "Tier 1",
            type: "Type 1",
        },
        {
            id: "chr6:79519012:G:C",
            gene: "LCA5",
            consequence: "missense_variant",
            transcript: "NM_181714.4",
            crdcCarrierFrequency: "Unavailable",
            gnomadAf: "0.00002",
            revel: "0.86",
            alphaMissense: "0.91",
            loftee: "—",
            clinvar: "No P/LP RCV",
            genotype: "0/1",
            tier: "Tier 2",
            type: "Type 3",
        },
        {
            id: "chr6:79520510:C:G",
            gene: "LCA5",
            consequence: "synonymous_variant",
            transcript: "NM_181714.4",
            crdcCarrierFrequency: "Unavailable",
            gnomadAf: "0.012",
            revel: "—",
            alphaMissense: "—",
            loftee: "—",
            clinvar: "Benign",
            genotype: "0/1",
            tier: "—",
            type: "",
        },
    ],
};
