export const PB_SAMPLE_MOCK = {
    sampleId: "BCH-00-00000-01",
    sex: "Female",
    ageAtEnrollment: "11 years",
    affected: "Yes",
    investigator: "Investigator A",
    familyMembers: [
        { sampleId: "BCH-00-00000-01", role: "case" },
        { sampleId: "BCH-00-00000-02", role: "twin" },
        { sampleId: "BCH-00-00000-03", role: "sibling" },
        { sampleId: "BCH-00-00000-11", role: "mother" },
        { sampleId: "BCH-00-00000-12", role: "father" },
    ],
    phenotypeTotal: 131,
    phenotypeGroups: [
        {
            id: "HP:0000152",
            label: "Abnormality of head or neck",
            count: 31,
            terms: [
                { id: "HP:0000252", label: "Microcephaly" },
                { id: "HP:0000316", label: "Hypertelorism" },
            ],
        },
        {
            id: "HP:0033127",
            label: "Abnormality of the musculoskeletal system",
            count: 27,
            terms: [
                { id: "HP:0011844", label: "Abnormal appendicular skeleton morphology" },
                { id: "HP:0001367", label: "Abnormal joint morphology" },
            ],
        },
        {
            id: "HP:0040064",
            label: "Abnormality of limbs",
            count: 17,
            terms: [
                { id: "HP:0011297", label: "Abnormal digit morphology" },
                { id: "HP:0001167", label: "Abnormal finger morphology" },
            ],
        },
        {
            id: "HP:0002086",
            label: "Abnormality of the respiratory system",
            count: 17,
            terms: [
                { id: "HP:0002088", label: "Abnormal lung morphology" },
                { id: "HP:0006530", label: "Abnormal pulmonary interstitial morphology" },
            ],
        },
        {
            id: "HP:0001626",
            label: "Abnormality of the cardiovascular system",
            count: 15,
            terms: [
                { id: "HP:0001627", label: "Abnormal heart morphology" },
                { id: "HP:0030680", label: "Abnormal cardiovascular system physiology" },
            ],
        },
    ],
    variants: [
        {
            type: "Type 1",
            typeLabel: "ClinVar high-review P/LP · investigator-cohort HPO match",
            trackClass: "clinical",
            tier: "Tier 1",
            clinvarReview: { stars: 3, label: "reviewed by expert panel" },
            gene: "LCA5",
            id: "chr6:79518824:A:T",
            consequence: "stop gained · LoFTEE HC",
            genotype: "1/1",
            cohortRelation: "Matched by HPO overlap with Investigator A's cohort phenotype profile.",
            diseases: [
                {
                    id: "ORPHA:364055",
                    samplePercentile: 90,
                    investigatorMeanPercentile: 92,
                    differenceLabel: "−2",
                    matchTooltip: "Illustrative residual PheRS 2.14. Percentile 90 among 12,480 disease-specific eligible samples. Investigator A mean: percentile 92 among 216 eligible samples, excluding this sample.",
                },
                {
                    id: "ORPHA:65",
                    samplePercentile: 76,
                    investigatorMeanPercentile: 61,
                    differenceLabel: "+15",
                    matchTooltip: "Illustrative residual PheRS 1.31. Percentile 76 among 12,480 disease-specific eligible samples. Investigator A mean: percentile 61 among 216 eligible samples, excluding this sample.",
                },
            ],
        },
        {
            type: "Type 3",
            typeLabel: "Known-gene evidence · investigator-cohort HPO match",
            trackClass: "reanalysis",
            tier: "Tier 2",
            clinvarReview: { stars: 1, label: "criteria provided, single submitter" },
            gene: "LCA5",
            id: "chr6:79519012:G:C",
            consequence: "missense variant",
            genotype: "0/1",
            cohortRelation: "Matched by HPO overlap with Investigator A's cohort phenotype profile.",
            diseases: [
                {
                    id: "ORPHA:65",
                    samplePercentile: 68,
                    investigatorMeanPercentile: 55,
                    differenceLabel: "+13",
                    matchTooltip: "Illustrative residual PheRS 0.84. Percentile 68 among 12,480 disease-specific eligible samples. Investigator A mean: percentile 55 among 216 eligible samples, excluding this sample.",
                },
            ],
        },
    ],
    allVariants: [
        {
            id: "chr6:79518824:A:T",
            gene: "LCA5",
            consequence: "stop_gained",
            transcript: "NM_181714.4",
            crdcCarrierFrequency: "Unavailable",
            gnomadAf: "—",
            revel: "—",
            alphaMissense: "—",
            loftee: "HC",
            clinvar: "Pathogenic",
            genotype: "1/1",
            tier: "Tier 1",
            type: "Type 1",
        },
        {
            id: "chr6:79519012:G:C",
            gene: "LCA5",
            consequence: "missense_variant",
            transcript: "NM_181714.4",
            crdcCarrierFrequency: "Unavailable",
            gnomadAf: "0.00002",
            revel: "0.86",
            alphaMissense: "0.91",
            loftee: "—",
            clinvar: "No P/LP RCV",
            genotype: "0/1",
            tier: "Tier 2",
            type: "Type 3",
        },
        {
            id: "chr6:79520510:C:G",
            gene: "LCA5",
            consequence: "synonymous_variant",
            transcript: "NM_181714.4",
            crdcCarrierFrequency: "Unavailable",
            gnomadAf: "0.012",
            revel: "—",
            alphaMissense: "—",
            loftee: "—",
            clinvar: "Benign",
            genotype: "0/1",
            tier: "—",
            type: "",
        },
    ],
};
